### ISSUE TITLE
Option to confirm deliveries with uploads

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1000]
Devilry 2.x sent an email confirmation when students made a delivery. After the transition to the feedback dialog model in 3.x that confirmation is no longer sent.

Until notification settings are included in the account settings (issue #995) it would be nice if sysadmins could enforce the old pattern of confirming deliveries.

**Solution**
Add an option for `devilry_settings.py` (something like `DEVILRY_CONFIRM_STUDENT_COMMENT_WITH_FILEUPLOAD`) that if `True` students would get a confirmation email when they make a comment that includes file uploads.

**Comment by StianJul** [comment]
We've simplified this to, whenever a student posts a comment they get a mail(receipt). The content of the mail is similar to both students and examiners, but the key difference is in the subject of the email.

### The student poster
The student that posts the comment receives an email(receipt) of the comment was posted before the deadline with the following email subject: 
`You added a new delivery/comment for <assignment name>` 

If posted after the deadline:
`You added a new comment AFTER THE DEADLINE for <assignment name>` .

### Other students and examiners in the group
Subject for email of comment posted before the deadline:
`A student added a new delivery/comment for <assignment name>`

After the deadline:
`A student added a new comment AFTER THE DEADLINE for <assignment name>`

### Subject of the email when an admin or examiner posts a comment
Admin posts a comment:
`An admin added a new comment for <assignment name>`

Examiner posts a comment:
`An examiner added a new comment for <assignment name>`


### Email body
The email will contain information about who wrote the comment, when it was published and the comment text + a link to the delivery feed.

**Comment by StianJul** [comment]
It will not list the files, only tell the receiver that there are files attached to the comment with a link to the feedbackfeed

**Comment by torgeirl** [comment]
Is there a high complexity increase associated with including the file names, instead of just stating whether there are files associated with the comment or not?

I believe the receipt would feel much more reassuring for students if it also included that.

**Comment by StianJul** [comment]
This shouldn't be a problem. We'll add a list of filenames and their sizes something like this:
 
- testfile1.py (900 bytes)
 - testfile2.py (4 KB)
 - somepdf.pdf (2 MB)

**Comment by torgeirl** [comment]
That's perfect! :tada:

**Comment by StianJul** [comment]
Should both students and examiners get a list of files, only students, or only the student that posted the comment(this is the "receipt")? A sane default I believe would just be to include the files in emails for both students and examiners.

**Comment by torgeirl** [comment]
All students on the assignment should definitely get the file list - if there are more students it's a group assignment and they all depend on the delivered files.

I don't think it does much either way for examiners, but since this doesn't increase or decrease the number of emails they receive (that will hopefully be addressed with a notification settings, issue #995) I would just include the extra information in the examiner emails as well.
