### ISSUE TITLE
Prevent examiners from navigating away from unsubmitted feedback

### ISSUE THREAD

**Issue by petter** [devilry/devilry-django#1007]
Jeg har alt for ofte vært uheldig og hoppet en side tilbake mens jeg skriver tilbakemelding og mistet hele tilbakemeldingen min. Kan dere legge til en alert boks når du prøver å gå ut fra tilbakemeldingen uten å ha submitted den? Altså bare noe slik som dette:
```
$(window).on("beforeunload", function() {
    return "Are you sure? You didn't finish the form!";
});
```

**Comment by torgeirl** [comment]
@G0pi: jeg antar du har opplevd problemet på Devilry 2.0.x (i produksjon på UiO), men jeg ser ikke noe hinder for å «gå fra» tilbakemelding i 3.x.x (under utvikling, i begrenset produksjon på UiO).

I 3.x.x forsvinner ikke tilbakemeldingen min om jeg navigerer frem igjen (Google Chrome), men det er helt klart noe man kan se på da ikke alle nettlesere håndterer navigasjon frem og tilbake like godt.

Jeg vil tro det er veldig liten sannsynlighet for at dette vil bli utbedret for 2.0.x-branchen da man heller vil fokusere på å få 3.x.x helt ferdig.

**Comment by torgeirl** [comment]
> I 3.x.x forsvinner ikke tilbakemeldingen min om jeg navigerer frem igjen (Google Chrome), men det er helt klart noe man kan se på da ikke alle nettlesere håndterer navigasjon frem og tilbake like godt.

Ettersom de fleste nettlesere nå bevarar utfylling ved navigasjon antar jeg at dette er løst og lukker issuet.
