### ISSUE TITLE
Error in "Add new deadline" for manual selection by admins

### ISSUE THREAD

**Issue by tworide** [devilry/devilry-django#1008]
Case.
If a group have made a delivery and is corrected "Failed" and a Course admin create a new deadline through the admin-ui "Add new deadline" with manual selection of the group the `last_deadline` is not updated to the new one and the `devilry_status` is still corrected and group `is_open` is `False`

The workaround is to set the new deadline through the `EXAMINER` ui

**Comment by tworide** [comment]
![image](https://user-images.githubusercontent.com/93136/37913677-bd87ec5c-3115-11e8-9a4a-39c8290c42fb.png)

**Comment by torgeirl** [comment]
I believe this issue didn't carry over to Devilry 3.x, and can be considered solved.
