### ISSUE TITLE
Group split could lead to attributeError

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1014]
Splitting out one student from a project group can result in a 500 server error due to `'NoneType' object has no attribute 'get_anonymous_name'` when trying to view the feedback dialog for the lone student.

I suspect it is due to an error with displaying the actions of the other students (uploads, comments, etc) that no longer is part of the lone delivery. Similar to the non-critical error that causes participants' name to be missing from feedback dialog (issue #961).

**Comment by espenak** [comment]
This will be solved by the fix for #961.
