### ISSUE TITLE
Query optimization to boost rendering performance

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1025]
While the `3.x` UI in general is snappy, it seem we need some optimization to boost loading time for large courses (500+ students).

I have a list of a few really large courses with complex group structures that should work well as performance test cases once we're ready to start implementation.

**Comment by StianJul** [comment]
We've uncovered and optimized a lot of views that have decreased the loading time significantly. This is mainly for the Admin views. 

The tests where done with around 1000 students, 1000 examiners, everyone had comments, some projectgroups etc.

These optimizations also affects some of the examiner views. Now, most of the groundwork here is done, but should you uncover other performance issues, please add another issue, and describe which page/pages this is related to.

**Note:** Some functionality that crunches a lot of data will obviously take some time. If this seems to be an occuring problem, we should consider using RQ to perform these tasks.
