### ISSUE TITLE
Status in Semester results should reflect undelivered assignments

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1029]
It seems to be four types of results in the results overview: `passed (x/y)`, `failed (x/y)`, `Not registered` and `Waiting for feedback`. The two first are self explanatory while `Not registered` means the student hasn't been added to the assignment.

`Waiting for feedback` seems to be a bit misleading on the other hand. I have examples of zero comments and deliveries by the student (or anyone else) having the status `Waiting for feedback`.

This forces admins to have to check up every individual with that status, to make sure there isn't anyone with a delivery actually waiting for a feedback, before exporting the results from Delivery to other systems.

I guess the issue could be related to hard deadlines, and if so, could we switch the status of an assignment with hard deadlines to `No delivery` when the deadline has expired and the student hasn't delivered (aka uploaded) anything?

**Comment by tworide** [comment]
Yes @torgeirl `The waiting for feedback` meaning that the deadline is passed and that the student are waiting for feedback. Even if there is no delivery you still need to fail the students for not delivering anything to the assignment.

Your proposal for clearing this list is very good and we should absolutely have this option for hard deadlines.
