### ISSUE TITLE
Performance issues with 'Find a student'

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1035]
The `Find a student` feature that got introduced in 3.2 to address issue #993 seems to need some optimization. The **initial** loading time for a small installation (~2000 users) is ~3 seconds while it's ~20 seconds for a big installation (~15000 users). Interaction also takes considerable time, making the feature unpleasant to use.

This issue could already be solved in 3.3 with its issue #1025 as @StianJul mentioned those optimizations also would affect other views, but that's hard to say until we test with 3.3 (to be released).

A partial fix could be to not load the unfiltered list of names client-side, as the list of name isn't of much value (unsorted), and rather only load hits as the admin user is typing their search string.

**Comment by StianJul** [comment]
This was resolved in #1025
