### ISSUE TITLE
Anonymous users are named in dialog

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1048]
Anonymous users are named in delivery dialog. All views used for assignment needs to be updated so only show candidate number (and if that is missing, an anonymous placeholder).

**Comment by torgeirl** [comment]
From the examiner's point of view, the students' IDs are hidden from the assignment overview:
![screenshot from 2018-09-05 18-48-01](https://user-images.githubusercontent.com/796053/45108364-b05f7480-b13c-11e8-83e2-132d474dd431.png)

That is also the case for the downloaded archives. Within the feedback feed however, the name is visible:
![screenshot from 2018-09-05 18-48-28](https://user-images.githubusercontent.com/796053/45108507-10eeb180-b13d-11e8-8d18-2faf6c623bd9.png)

**Comment by torgeirl** [comment]
Tested some more, and this is more a glitch / unexpected behavior than a bug.

This issue is limited to users with multiple roles (and therefore reproducible when testing alone). Between different users, the identities are however not revealed.

Is this behavior according to the specifications? If so, this issue can be resolved. Otherwise, would it require much to fix it? If so, it could just be ignored and also closed.

**Comment by StianJul** [comment]
You're right, this only happens if a user has multiple roles (a they can see their own name).

**Comment by torgeirl** [comment]
> You're right, this only happens if a user has multiple roles (a they can see their own name). It's a simple fix to remove this.

We don't need to use time to fix as it only affect users with multiple roles, seeing their own names/usernames.
