### ISSUE TITLE
Examiners should see active periods

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1049]
It would be helpful if examiners could see active periods they are added to, before they get assigned students on an assignment.

The current implementation makes it unclear to the examiner whether they are added until they actually get assigned students, and the uncertainty generates unnecessary questions to department admins.

**Suggested solution**
- if the examiner is added to a semester without a published assignment, create a dummy assignment object on their deshboard titled «coursecode.semestername» with status (usually «Nobody waiting for feedback», etc) «Course admins have yet to publish an assignment on this course»

**Comment by StianJul** [comment]
In the meeting related to milestone 5.5 we agreed that this overview should be added to the user-profile view. We'll add a list for examiners and students to see which active periods they are added to.

Could you confirm this, @torgeirl?

**Comment by torgeirl** [comment]
@StianJul: correct, but I believe we also wanted to add a link between the `I should have had more roles` and `Superuser UI` links titled ~`See your account overview for all active roles` that links to the account page?

**Comment by StianJul** [comment]
@torgeirl:

![Screen Shot 2022-05-09 at 13 13 09](https://user-images.githubusercontent.com/3988175/167399133-7c1cfb0f-a190-4fe3-8f5f-e556a727f796.png)

![Screen Shot 2022-05-09 at 13 16 03](https://user-images.githubusercontent.com/3988175/167399167-3bcb97cf-c62a-46ac-8845-77aca735a8d0.png)

**Comment by torgeirl** [comment]
@StianJul: perfect! :+1:
