### ISSUE TITLE
Group deliveries unviewable in Firefox on Linux

### ISSUE THREAD

**Issue by anjohan** [devilry/devilry-django#1055]
See the attached image.

When clicking on a group delivery as an examiner, I can't see the files (the `Show/hide` button doesn't work), nor the comments. The files are visible when using e.g. Safari/Chrome on OSX.

I am using 'Mozilla Firefox for Arch linux', version 61.0.2.

![image](http://i66.tinypic.com/33tl24n.png)

**Comment by tworide** [comment]
Thanks for the report. We will investigate this further.

**Comment by torgeirl** [comment]
If this isn't just an UI glitch, it could be related to #1012 or #1014 / #961.

**Comment by StianJul** [comment]
Firefox does not support `<event>.srcElement`. This is now fixed and will come with the next release.
