### ISSUE TITLE
Unable to edit comment that was originally empty (as student)

### ISSUE THREAD

**Issue by HumaneWolf** [devilry/devilry-django#1056]
Experienced when trying to edit the text comment of a previously uploaded file (that had no text in it initially).

Regardless what I type, it will give the response "No changes, comment not updated". It does not happen for a comment that had text in it initially.

**Comment details:** 

* Had a file uploaded and attached to it.
* Had an empty text body.
* Delivered by and as a student

A more recent comment that had both files attached and a text body does not have the same issue.

The Devilry instance is running Devilry v3.3.1 (latest version tagged on Github as of typing this).

**Comment by StianJul** [comment]
Will be available with the next release.
