### ISSUE TITLE
Points/Grade not saved with draft / Editing draft box way to small

### ISSUE THREAD

**Issue by LitenApe** [devilry/devilry-django#1057]
1. When drafting a feedback with points, the points are lost. When publishing the feedback, we have to re-insert the points and publish with a empty feedback (which was weird to understand). Anyway, this is a overhead we believe should be eliminated - wasn't that cumbersome in Devilry 2. 

2. The editing box for a drafted message is way to small. Scrolling through a drafted message in a 3 line edit-box is really narrow, at least add a resize option for the edit-box. 

Thanks

**Comment by torgeirl** [comment]
@LitenApe: thanks for your feedback.
----

Until #1040 can be solved, we should make some minor UI tweaks to make the text boxes scale (2) and see if the drafts implementation can be extended to also save the points/grades.

**Comment by torgeirl** [comment]
> As a partial fix to (2) we included a larger text box in `3.3.2`/`3.3.3` (rolled out this week).

A full fix for this issue will be included in #1217 so closing this issue.
