### ISSUE TITLE
'Add student' should display student already added

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1067]
`Add students`, `Select manually` allows you to search among students on the semester not already added to the assignment. It would be an improvement if it also displayed students on the assignments  grayed out or in so other fashion showed that they're already added to it.

**Comment by StianJul** [comment]
@torgeirl, based on how these selectable filter-lists works, we can't easily add other elements within the selectable elements purely for visual purposes.

**Possible solutons**

1. Mix "non-selectable" elements with the selectable elements, and then clean them out when the form is posted. 

_We would probably need to update the core-implementation for these views in cradmin-legacy, and then apply this functionality to Devilry. This would probably also affect way more views where these filter-lists are used. These views are only meant to support adding elements that can be added (like they work now), and I think a better solution would be redesign and implement new functionality with this case in mind. We would probably also need to take into account that a rewrite is necessary for all the views that use these filter-lists._

2. Add the overview of the students already added to the assignment in it's own section below the filter-lists. 

_Shouldn't this also be done for all the other plugins for adding students to the assignment? In any case, this probably can't be done efficiently without implementing custom handling of this section to dynamically fetch students on the assignment and add pagination for large courses._

3. Show the number of students already on the assignment

_Just throwing this in here, but can't really see how this is helpful if the admin needs to see the student "cards"._

I would not recommend doing this within the current implementation, but would rather recommend that we discuss a rewrite for this functionality as this would affect other parts of the system using these filter-lists. Either way, we would need to estimate this task.

**Comment to the issue**

I can't really see why it's necessary to show students already added to the assignment? Students already added to the assignment are available through the "Manage students" view. This is purely here for adding students not already added to the assignment.

I'm just taking the issue-description at face-value, but how is it helpful to see e.g 100+ students already on the assignment when the task at-hand is to add those that are not? Finding out if a particular student is on the assignment or not can be done in the student overview.

**Comment by StianJul** [comment]
There might be a misunderstanding on my part, so feel free to clarify the use-case for this :)

**Comment by StianJul** [comment]
When it comes to solution 1., I think we might be able to mix the students already added the assignment together with the students that are not, but this is something I need to check out before I can say if it actually works. Anyways, most of the queries and form-handling would need to be rewritten and tested again if it works.

I still can't really see how this is an improvement though.

**Comment by torgeirl** [comment]
We have had a few instances when two department admins look to solve the same issue in parallel, and get confused when the student doesn't show up in the search as this suggests the student isn't added to the semester when in reality the student is both added to the semester and already added to the assignment.

It seems to me this is too much work for too little gains so let's drop this.
