### ISSUE TITLE
Prompt students the assignment guidelines

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1068]
Student should be prompted the assignment guidelines once each semester.

**Suggested implementation**
- Add `custom_devilry_templates` support for guideline templates. They should probably have an `updated` value.
- Each semester should have the option to link to one of these guideline templates manually and with a preview option when a guideline has been selected.
- `devilry_periodadd` should have a `--guideline` option for automation.
- The first time a student tries to upload files to an assignment on the semester, they should be prompted the guideline template. Accepting the guidelines should be noted in the database and be displayed in the feedback feed similar to a deadline move.

We made something similar for [Trix2](https://github.com/devilry/trix2) to handle consent due to GDPR requirements, but not as complex as handling different templates for each Department.

**Comment by torgeirl** [comment]
Guidelines should be addressed outside of Devilry, preferable on the course page or in assignment text itself.

**Comment by espenak** [comment]
Mostly done - missing some tests and cleanup. Looks like this:

![image](https://user-images.githubusercontent.com/84501/167411102-b54b13e7-f3ba-4ce7-a149-63323c46a77f.png)

Is configured like this in settings:
```python
DEVILRY_ASSIGNMENT_GUIDELINES = {
    'student': [
        (r'duck10.+', {
            '__default__': {
                'htmltext': 'This is the assignment guidelines for inf10xx courses.',
                'url': 'http://example.com'
            },
        }),
        (r'duck11.+', {
            '__default__': {
                'htmltext': 'This is the assignment guidelines for inf11xx courses.',
                'url': 'http://example.com'
            },
            'nb': {
                'htmltext': 'Dette er retningslinjene for oppgaver i inf11xx kurs',
                'url': 'http://vg.no'
            }
        })
    ]
}
```
Can also add guidelines for examiners, just like for students (just add an ``examiner`` key to the setting with the same structure. 

The ``duck10.+`` etc. strings are regexes that is matched against the period path (``<subject short name>.<period short name>``) using ``re.fullmatch``. They are matched in order, so more explicit matches can be put at the top, and "fallbacks" / more general matches can be further down in the list if needed. The regexes can be tested using the ``python manage.py devilry_show_assignment_guidelines mysubject.myperiod student`` script.

Does this look OK @torgeirl ?

**Comment by espenak** [comment]
Only missing migrations and translations.

**Comment by espenak** [comment]
Should be ready for release. It is currenty in the milestone-5.5 branch.

Docs here https://github.com/devilry/devilry-django/blob/milestone-5.5/not_for_deploy/guides/assignment_guidelines.md.

**Comment by torgeirl** [comment]
> Does this look OK @torgeirl ?

This is exactly what we wanted. :+1:
