### ISSUE TITLE
Error in translation for internal notes

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1069]
**English**
![screenshot from 2018-10-05 15-55-50](https://user-images.githubusercontent.com/796053/46539789-c2f1d880-c8b7-11e8-9dcd-2547eada01e4.png)

**Norwegian**
![screenshot from 2018-10-05 15-55-36](https://user-images.githubusercontent.com/796053/46539792-c5543280-c8b7-11e8-8620-9d2101057631.png)

**Comment by StianJul** [comment]
Fixed. Will come with the next release.
