### ISSUE TITLE
The student search is case-sensitive for names that starts with ÆØÅ

### ISSUE THREAD

**Issue by morteako** [devilry/devilry-django#1077]
"øyvind" does not match "Øyvind", but "martin" matches "Martin".
Seems like a bug
v3.4.4

**Comment by torgeirl** [comment]
Reproducible with Devilry 6.0. We should have fixed this a long time ago; adding to next milestone.

**Comment by Levijatan** [comment]
I could not reproduce this problem inn development, but added a step to make sure the search input has the correct encoding.
