### ISSUE TITLE
Internal notes on group deliveries does not show in delivery history

### ISSUE THREAD

**Issue by Schoyen** [devilry/devilry-django#1087]
When adding an internal note on a delivery this usually shows in blue as part of the history on a delivery. A note saying "Comment added" shows in green at the top of the delivery and mail is also sent to the other examiners assigned to this delivery. This is apparently not the case when the delivery is done by a group. That is, the "Comment added" note is shown and the mail to the other listeners is sent, but the note does not show in the delivery history.

This has been tested for two different users on three different group deliveries consisting of groups with 2 and 3 collaborators.

Note that this is for Devilry v3.4.6.

**Comment by torgeirl** [comment]
@Schoyen: could you please check if the internal comments are hidden on one of the deadlines in the feedback feed, as described in issue #1083 (Pre-merge items in project group should default to 'Show')?

**Comment by torgeirl** [comment]
Could you email me the details for the three examples on my UiO adresse (same username as here)? I'll need to reproduce the issue, and especially find out why the three aren't the same.
