### ISSUE TITLE
Postgres 11 testing

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1091]
Postgres 11 was [released last month](https://www.postgresql.org/docs/devel/release-11.html), and psycopg [seems to support it](http://initd.org/psycopg/features/):

> - Supports PostgreSQL versions from 7.4 to 11

We should still do some testing, starting with our test servers in early December.

**Comment by torgeirl** [comment]
**Suggested solution**
- Upgrade a development server to PostgreSQL 11
- Run all unit tests

If no unit test fails we'll assume this won't be an issue when the production servers updates Q1-2.

**Comment by StianJul** [comment]
Upgraded to PostgreSQL 11.1, all unittest pass.
 I will continue development with this version as this is a great way test it more "in-depth".

Don't close this issue yet!
