### ISSUE TITLE
Adjust 23:59 time field

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1092]
We have a long tradition for using midnight as a deadline (issue #4).

The deadline is more precisely 23:59:00, and this minor detail have actually started to come up for our administration. Would it be possible to adjust the time field so the associated deadline is 23:59:59?

**Comment by tworide** [comment]
#1102

**Comment by StianJul** [comment]
The Deadline-model is deprecated, and not in use anymore. Instead, roughly explained, deadlines are handled as `DateTimeField`s.

Create new assignment
https://github.com/devilry/devilry-django/blob/milestone-5.2/devilry/devilry_admin/views/period/createassignment.py

Update assignment first deadline
https://github.com/devilry/devilry-django/blob/milestone-5.2/devilry/devilry_admin/views/assignment/first_deadline.py

Bulk-moving deadline through the project group overview, moving deadline and giving new attempt per group uses the same functionality for handling deadlines
https://github.com/devilry/devilry-django/blob/milestone-5.2/devilry/devilry_deadlinemanagement/views/manage_deadline_view.py#L80

Suggested deadlines for managing deadlines
https://github.com/devilry/devilry-django/blob/milestone-5.2/devilry/devilry_deadlinemanagement/views/manage_deadline_view.py#L224

Suggested deadlines when creating new assignment
https://github.com/devilry/devilry-django/blob/milestone-5.2/devilry/devilry_admin/views/period/createassignment.py#L195
