### ISSUE TITLE
Update to python3

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#1103]
We can use https://docs.python.org/2/library/2to3.html. Another guide here: http://python3porting.com/2to3.html

NOTE: It is possible to migrate to a codebase both compatible with pyton2 and python3, but we do not need that. When we change to python3, devilry will require python3.6+.

**Comment by torgeirl** [comment]
I assume we want to do this while also upgrading from Django 1.11 LTS to 2.2 LTS (ETA april 2019).

**Comment by espenak** [comment]
Yes, but we will first do the python3 update, and then do the Django2 update as a separate issue.

**Comment by Levijatan** [comment]
Trying to install requirements for python3, but one of the requirements BeautifulSoup3 does not support python3. BeautifulSoup4 does support python3 so it needs updating.

**Comment by Levijatan** [comment]
transifex-client needs to be updated

**Comment by Levijatan** [comment]
flup needs to be updated

**Comment by Levijatan** [comment]
django-simple-rest is dead, and will not be updated for python 3. It needs replacement

**Comment by Levijatan** [comment]
mimeparse is outdated, it might need replacement but I am not sure.

**Comment by Levijatan** [comment]
python-dateutil outdated

**Comment by Levijatan** [comment]
Had to disable devilry_rest since this app is built on django_simple_rest which is not updated to python 3 and is not in development anymore.

**Comment by Levijatan** [comment]
Done

**Comment by torgeirl** [comment]
Re-opening this awaiting commits/PR and, I assume, a beta release?

**Comment by StianJul** [comment]
This might need some more testing before releasing a beta. So, I won't be able to release this week, but will try to get the python3 beta release out early next week.

**Comment by torgeirl** [comment]
No problem, next week sounds good to me. :+1:

**Comment by torgeirl** [comment]
Three+ weeks in production suggests we only missed one issue with `devilry_useradd` (separate issue) during testing.
