### ISSUE TITLE
FieldError at /devilry_resetpassword/begin when trying to reset password from sign in (forgot your password)

### ISSUE THREAD

**Issue by Levijatan** [devilry/devilry-django#1105]
When trying to use forgot your password on an arbitrary mail (asdf@asdf.no) I got a FieldError.
![screenshot from 2019-03-05 14-42-26](https://user-images.githubusercontent.com/4390730/53809673-80f7bc00-3f55-11e9-93f4-b272bd30abbb.png)

**Comment by torgeirl** [comment]
As described in issue #981, including workarounds for current production environment (using Dataporten/Feide authentication).

**Comment by torgeirl** [comment]
This issue is a duplication of #1022 (users can not reset password caused by the base resetpassword view from CrAdmin expecting the user model to have the field `email`).
