### ISSUE TITLE
Finn en student for kursadministratorer og rettere innenfor et gitt kurs

### ISSUE THREAD

**Issue by tworide** [devilry/devilry-django#1112]
Dette behovet er et innspill fra Astrofysisk institutt og vil hjelpe på retterflyten

**Comment by torgeirl** [comment]
Filtere ala 'Manage students' under Assignements, for 'Add/edit students' på semesternivå? :confused:

**Comment by torgeirl** [comment]
> Filtere ala 'Manage students' under Assignements, for 'Add/edit students' på semesternivå? confused

'Add/edit students' på semesternivå har et søkefelt som treffer både brukernavn og (hvis tilgjengelig) navn. Fra rettergrensesnittet har man ikke tilgang på studenter før man tilfedeles de, men også det grensesnittet har søkefunksjonalitet. Antar derfor at dette behovet egentlig er dekket og lukker dette issuet.
