### ISSUE TITLE
Mulighet for å kunne manuelt konfigurere kandidatnummer i kursoppsettet

### ISSUE THREAD

**Issue by tworide** [devilry/devilry-django#1113]
Innspill fra Astrofysisk institutt

**Comment by torgeirl** [comment]
Kan muligens sees i sammenheng med #1051 (ingen indirekte mulighet til å se tildelete kandidatnr).

**Comment by torgeirl** [comment]
Dette dekkes av #792 (Add an UI for importing candidate IDs for a Period) så lukker denne.
