### ISSUE TITLE
Bad norwegian translation in view

### ISSUE THREAD

**Issue by tworide** [devilry/devilry-django#1119]
![image](https://user-images.githubusercontent.com/93136/63103842-28a1fd00-bf7e-11e9-8974-1b5d7675c14a.png)

`Skriv eller lim in e-brukernavnene adskilt med komma(","), mellomrom eller en bruker per linje.`

**Comment by torgeirl** [comment]
This is not solved in `5.4.0rc2`; should be «Skriv eller lim inn brukernavnene adskilt med komma (","), mellomrom eller en bruker per linje.» (double N in `inn`, no `e-` and an added space in `komma(",")`).

**Comment by torgeirl** [comment]
Solved in `5.4.0.rc3`/`5.4.0.rc4`! :+1:
