### ISSUE TITLE
File upload progression glitch for Safari

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1123]
When uploading multiple files using Safari the progression graphic glitch for some of the files.

Reported for Safari 11 (outdated?), but was able to reproduce using Safari 13 (stable).

**Comment by torgeirl** [comment]
New issue report with Safari 14 having a similar upload client-side glitch.

**Comment by espenak** [comment]
How where you able to reproduce this @torgeirl ? I can not reproduce this in Safari 14.0.3.

**Comment by torgeirl** [comment]
> How where you able to reproduce this @torgeirl ? I can not reproduce this in Safari 14.0.3.

The reporter used Safari 11.1.2 on El Capitan 10.11.6, but we were at the time able to reproduce it in Safari 13 (then stable). We just re-run the exact same delivery in Safari 14.0.3 and were unable to reproduce the error now so I assume this issue has been solved by the Safari team.
