### ISSUE TITLE
Tag filtering in examiner view

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1138]
We recently got a feature request where the use case would be satisfied by adding tag filtering in the assignment view for examiners, but Github's 'similar issues' reminded me I highlighted this on February 6, 2018, in issue #949:

> The Examiners view of a given assignment (/devilry_admin/assignment/X/bulk_organize_examiners/manual-add/ - where X is an integer referring to the given subject) lacks a filter for tag.

It lead to fixing another issue, but it seems the lack of tag filtering in the examiner view got left in the mix. Is there a reason why the examiner view can't have such filtering?

**Comment by StianJul** [comment]
@torgeirl, just for clarification, for the view on devilry_admin/assignment/X/bulk_organize_examiners/manual-add/ you are talking about this functionality?
![Screen Shot 2021-04-20 at 11 42 47](https://user-images.githubusercontent.com/3988175/115374976-a1cf0a00-a1cd-11eb-8669-71ac600624e4.png)

**Comment by torgeirl** [comment]
> just for clarification (...) you are talking about this functionality?

No, but I did explain the user request quite bad. They requested that examiners can filter their students by tags from the examiner's assignment overview (`devilry_examiner/assignment/N/`):

![Screenshot from 2021-04-20 12-38-51](https://user-images.githubusercontent.com/796053/115383158-caf39880-a1d5-11eb-8efa-f9ffe9bc44da.png)

One use case is large subjects (500+ students) that combine traditional examiner feedback and feedback from multiple examiners to one student or student group. Since examiners can't see if others (and who else) are providing feedback to a student group the organizers suggested that examiners should be able to filter students by tag and by that mechanism  distinguish between traditional and multi-examiner feedback through a custom tag for student groups that should receive multi-examiner feedback

 Even though this use case is narrow the requested functionality  itself is still generic and could be useful for others.

**Comment by StianJul** [comment]
Ah, got hung-up on the link that pointed to the view for bulk-organizing... Shouldn't be problem adding a filter for student-tags there :)

**Comment by StianJul** [comment]
Fix is in `milestone-5.1`-branch, and will be released when ready.
