### ISSUE TITLE
Files with commas in their filenames are not saved correctly when downloaded

### ISSUE THREAD

**Issue by rantonse** [devilry/devilry-django#1139]
When a file, in this case a PDF-file, has a comma in its filename, it is not saved correctly. The filename becomes whatever is to the left of the comma, sometimes including the comma, sometimes including the extension.

Tested on macOS 10.15.3.

Uploaded filename “IN1150, første innlevering.pdf”:
- Chrome 80.0.3987.87 saves it as “IN1150”
- Firefox 72.0.2 saves it as “IN1150,”
- Safari 13.0.5 saves it as “IN1150.pdf”
- Vivaldi 2.10.1745.27 saves it as “IN1150”

**Comment by StianEb** [comment]
Similar experience here. Trying to download a student's response to an assignment (as an examiner) gives unexpected results. It's a .pdf file with two commas in the name, each with a space behind it.

Chrome 80.0.3987.87 (64-bit) takes me to an error page, saying the following:
devilry.ifi.uio.no sent an invalid response.
ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION.
Firefox 72.0.2 (64-bit) lets me download the file, but only keeps part of the file name: Up to and including the first comma, just like @rantonse.

I'm on Windows 10 Home 64-bit (10.0, Build 18362).
