### ISSUE TITLE
Filter option for student(s) without tag

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1152]
There's currently no filter option for students or examiners without a tag. This would be useful when a group of students wrongly gets imported to a semester or assignments as it's otherwise a lot of work to clean up.

**Comment by StianJul** [comment]
Tag-select supports a "NO TAG" option for students/examiners.

![Screen Shot 2021-04-22 at 12 51 09](https://user-images.githubusercontent.com/3988175/115702643-7719b880-a369-11eb-9f59-dffe7845e83e.png)

Fix is in milestone-5.1-branch, and will be released when ready.
