### ISSUE TITLE
Calendar doesn't render for Safari

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1158]
Reported for Safari 14 on iOS:

![issue-ios](https://user-images.githubusercontent.com/796053/96608423-a76c9580-12f9-11eb-8a68-f0bd35902754.png)

**Comment by torgeirl** [comment]
The issue seems to be present in both Safari and Chrome for iOS.

**Comment by StianJul** [comment]
@torgeirl, this works on Safari and Chrome for both an old iPhone SE and iPhone 11 running version 14.+. We're still looking into it, but what model are we talking about?

![calendar_chrome](https://user-images.githubusercontent.com/3988175/114881678-83e75b00-9e03-11eb-8a8a-2fa5b35560a4.PNG)
![calendar_safari](https://user-images.githubusercontent.com/3988175/114881685-85b11e80-9e03-11eb-9d63-5da2b92860db.PNG)

**Comment by StianJul** [comment]
Seems to be a bug on iPad

**Comment by torgeirl** [comment]
> Seems to be a bug on iPad, or tablets in general

The user reporting the problem was on an iPad.

**Comment by Eskalol** [comment]
Fix is in `milestone-5.1`-branch, and will be released when ready.
