### ISSUE TITLE
Moving deadline after grading should require new attempt

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1160]
In `5.0.0` it's possible to move a deadline after the original delivery has been graded. This can create a lock-situation, where the student can upload a new devilry within the new deadline, while examiners are unable to grade the new delivery.

**Workaround**
- manually add a new attempt with a short deadline, before grading

**Solution**
Enforce granting new attempt when moving a deadline of a graded assignment, either from the feedback feed or deadline management view.

**Comment by StianJul** [comment]
**Solution**
In the feedback-feed, ensure that deadline can not be moved for corrected feedbacksets, and new attemps can not be given if the feedbackset is not corrected. Currently, both new attempt and move deadline are available for corrected feedbacksets.

Note: This is already handled by the bulk "deadline organizer".

**Comment by torgeirl** [comment]
It seems we also need to prevent examiners from moving deadlines after grading to completely solved this issue. I have two examples of an examiner moving the deadline after grading, creating the «grading lock» as described above.

**Comment by StianJul** [comment]
@torgeirl, examiners shouldn't be able to move the deadline if graded, only give a new attempt.

Are the examples groups with multiple students, that have been split and then merged again, maybe with overlapping deadlines etc.? Just looking for possible edgecases that may cause this problem. Do you have any more information regarding the examples?

**Comment by torgeirl** [comment]
> Do you have any more information regarding the examples?

At least one of the examples where without groups and merges, just a lot of extensions and new attempts. I'll gather the details.
