### ISSUE TITLE
'Add student' to semester should prompt admin about previous and ongoing assignments

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1164]
The `Add student` function of semester currently displays «Added "<student's name>".» when a student is added.

It should also indicate it there are finished or ongoing assignments, as a reminder to add the student to those (and handle any extended deadlines that would involve).

**Comment by espenak** [comment]
Solution:

![image](https://user-images.githubusercontent.com/84501/131652768-1bdec5d4-7478-4245-b9d6-841b93f0fed5.png)

Same message from "import students" and "add students".
