### ISSUE TITLE
Poor link purpose for account nav element

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1205]
WCAG 2 success criterion 2.4.4 required that the purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general.

The header link to the account page has two views:
* Wide view: «:person_bald: NN» (initials)
* Narrow view: «:person_bald: Name Namerson»

Using a screen reader this implementation makes the voiceover saying «link, NN», resulting in a poor link purpose.

**Comment by StianJul** [comment]
Since nothing else is specified, it has been updated so that the result for "wide view" is the same as for the narrow view: The display name is read "Name Namerson (email)".
