### ISSUE TITLE
Warn if navigating away before submitting assignment

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1210]
WCAG 2.1 Success Criterion 3.3.4 Error Prevention (Legal, Financial, Data) requires that web pages that cause legal commitments or financial transactions for the user to occur, that modify or delete user-controllable data in data storage systems, or that submit user test responses, at least one of the following is true:
1. **Reversible**
Submissions are reversible.
2. **Checked**
Data entered by the user is checked for input errors and the user is provided an opportunity to correct them.
3. **Confirmed**
A mechanism is available for reviewing, confirming, and correcting information before finalizing the submission.

Devilry's assignment submission mechanism satisfies the third option. In addition, the student will receive an email receipt confirming the submission. But the assignment submission mechanism could be improved by adding extra measures that prevent user error:

- Add a message or warning if the user attempts to navigate away from the page or refresh after uploading a file before submitting.

**Comment by StianJul** [comment]
@torgeirl, since this a suggestion for improvement, I would recommend that we take this into account when we look at replacing the ace-editor. Me and Espen have already loosely discussed possible support for "flipping" the editor to a confirm-box before actually submitting a comment/assignment. I think this would be a proper step towards notifying the users about what's going to happen.

https://github.com/devilry/devilry-django/issues/1211

**Comment by torgeirl** [comment]
> @torgeirl, since this a suggestion for improvement, I would recommend that we take this into account when we look at replacing the ace-editor. Me and Espen have already loosely discussed possible support for "flipping" the editor to a confirm-box before actually submitting a comment/assignment. I think this would be a proper step towards notifying the users about what's going to happen.

@StianJul: agreed! :+1:

**Comment by StianJul** [comment]
A solution has been added to the feedbackfeed that uses the built-in browser confirmation prompt when navigating away or refreshing the page.

**Comment by torgeirl** [comment]
@StianJul: was this solved as part of #1214, or will this have to wait for the 5.5 release?
