### ISSUE TITLE
Incorrect role path in notification template

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1216]
It seems the notification templating incorrectly adds the `/examiner/ ` path to `devilry_email_comment_detail_url` when notifying administrators .

Example: when another administrator comments an assignment the «An admin added a new comment for {assignment name}» notification's `devilry_email_comment_detail_url` will use an `/examiner/ ` path. Unless the admin receiving the notification also is the student group's examiner the URL will give HTTP 403 permission denied.

**Workaround**
The admin can manually replace `/examiner/ ` with `/admin/ `.

**Comment by StianJul** [comment]
@torgeirl, this is now fixed and will be available with the 5.4-release.
