### ISSUE TITLE
Better support for LaTeX and code snippets

### ISSUE THREAD

**Issue by StianJul** [devilry/devilry-django#1220]
Better support for LaTeX and code snippet markdown in editor.

**Comment by espenak** [comment]
https://katex.org/

**Comment by espenak** [comment]
Should be ready for use now:
![image](https://user-images.githubusercontent.com/84501/170687147-502f89f8-65c4-4504-91d0-e4589a38f718.png)

![image](https://user-images.githubusercontent.com/84501/170687180-24e9278c-27fd-4a1f-8f2f-55f1ebfa1843.png)
