### ISSUE TITLE
Too low contrast for warning note

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1222]
The warning when examiners aren't assigned to students seems to have too low contrast according to the web accessibility evaluation tool WAVE: «NOTE: There are examiners on the semester that are not assigned to any students»

**Comment by StianJul** [comment]
The color has been adjusted to comply with both AA and AAA for normal and large text.

Checked with Wave:
![Screen Shot 2022-05-10 at 09 31 46](https://user-images.githubusercontent.com/3988175/167573887-f6d79165-f1d3-421f-9838-9f47cacc482c.png)
