### ISSUE TITLE
Improved export of qualified for final exam results

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1224]
The qualified for final exam module currently only presents the results in simple lists. We're currently looking into standardizing the results registration process, and would like to extend qualified for final exam to look more like the results module's download function.

**Solutions**
a) ~~Excel sheet export similar to what «Overview of all results» offers today~~ (Maybe later)
b) ~~PDF sheet~~ Print-friendly page that has similar layout to «godkjentlister» in FS:

```
EMNEKODE YYYY semester, dato og tidspunkt liste ble opprettet i Devilry

------------------------------------------------------------------------
GODKJENT
ETTERNAVN   FORNAVN   BRUKERNAVN KAN GÅ OPP TIL EKSAMEN NOTE
Amundsen    Roald     roaldamu   Ja                     [ ]
Nansen      Fridtjof  frinase    Ja                     [ ]
(...)


------------------------------------------------------------------------
IKKE GODKJENT
ETTERNAVN   FORNAVN   BRUKERNAVN KAN GÅ OPP TIL EKSAMEN NOTE
Shackleton  Ernest    erntshan   Nei                    [ ]
(...)
                      robertfs   Nei                    [ ]

```

Important details:
- candidates that can and can not take the finale exam must be listed separately
- the sections should be sorted sort by lastname/first name/username
- candidates missing name fields (not imported with names, and never logged into system via Feide) should come last in both sections
- headers should repeat on each page of the PDF/printed pages

**Comment by Levijatan** [comment]
Pushed up a commit for this on the 6.1 milestone branch.
