### ISSUE TITLE
List required assignments in qualified for final exams

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1230]
When producing the qualified for final exams list an administrator will select which assignments are required to be qualified for final exams. The selection is however not displayed anywhere else making it hard to debug.

**Suggested solutions**
a) List the required assignments in the admin UI
b) List the required assignments in the superuser UI

a) is preferred, but b) should be sufficient if this is time consuming to add to the regular UI.

**Comment by torgeirl** [comment]
We should look at this when reworking the export of qualified for final exam results (#1224).

**Comment by Levijatan** [comment]
a2550e4 now lists up required assignments at the status view. But only for statuses created after this update since the information was never retained so added a json field on the Status model save extra data from plugins.
