### ISSUE TITLE
Additional filters for self-assign

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1238]
Courses with flexible deadlines need an additional filter and an additional sorting to make the self-assign feature (#1218) useful to them:
* filter: whether the assignment have a delivery (contains an attached or not)
* sort: delivery time (time of comments made with files attached to them)

**Comment by Levijatan** [comment]
Added the filter, but there was no good way to do the sorting based only on comments made with files attached to them so sorted on last comment instead. c3c7b23

**Comment by Levijatan** [comment]
The waiting-for-feedback filter already does 1. so added sorting on delivery time.

**Comment by torgeirl** [comment]
Fixed in 72e57b6dff7eeb489691a48e0a51f5efac520700 / eff0f7cd36d6bc4e9cc6f038ebdc3847d1f2e7dd.
