### ISSUE TITLE
Terms "group" and "student" are not used consistently

### ISSUE THREAD

**Issue by larstvei** [devilry/devilry-django#1244]
Hi!

When viewing "Manage students" (in the administrator interface) for an assignment, the terms "group" and "student" cause some confusion, and report incorrect information.

An example from my course:

* At the "Overview"-tab (where we can click "Manage students") it says there are "527 students organized in 431 project groups".
* In the "Manage students" tab, it says "Found 431 of 431 students" (note "students", not "groups")
* When filtering on activity "Has file(s) from student", it says "Found 192 of 431 students" (note again "student" not "group")
* If I click "Load all" and open the console and enter `document.getElementsByClassName("devilry-user-verbose-inline-shortname").length` I get 372. 
  * I am fairly sure this is the number of students (not groups!) who has delivered something.
  * 192 corresponds to the number of groups (for instance `document.getElementsByClassName("devilry-cradmin-groupitemvalue").length` gives 192).

This confusion of terms gives reason for serious concern, as it looks as if half of the students have given up the course. So from a "user experience" point of view, this is a pretty serious bug.

**Comment by torgeirl** [comment]
@larstvei: thanks for filing this issue, seems er need to clean up the UI when we get the chance.

**Comment by Levijatan** [comment]
Added fix for this inn 8866a1a
