### ISSUE TITLE
Escape HTML tags in comments

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1275]
After the introduction of the updated comment editor in Devilry 5.5 we have had a few examples of certain HTML tags in comments causing client-side rendering issues.

**Suggested solution**
a) Either strip away HTML tags in comment texts if they are missing surrounding single grave accents (ie. ``` `<table>` ```) , or
b) auto-encapsule them with single grave accents if they are missing

**Comment by Levijatan** [comment]
Created a milestone-6.2 branch and pushed up a fix for this. Ended up with using html-sanitizer to remove all not allowed tags, luckely it escapes tags inside code blocks instead of removing them so it was quite easy to sanitize after the markdown to html conversion step.

**Comment by torgeirl** [comment]
Added in 0363c95e3469a5267ae39687be761ca9a7c3c075.
