### ISSUE TITLE
Latex math in feedback is broken

### ISSUE THREAD

**Issue by rakfisk1** [devilry/devilry-django#1281]
When trying to give feedback using either `$math$ $\math$` or `$mathblock$ $\mathblock$` the entire contents of the block become invisible in preview and feedback. 

Pictures:
Write mode: 
<img width="410" alt="Screenshot 2024-01-28 at 10 29 10" src="https://github.com/devilry/devilry-django/assets/98320633/c8312472-d55b-4e79-852a-3783a72e36a9">

Preview: 
<img width="1151" alt="Screenshot 2024-01-28 at 10 30 58" src="https://github.com/devilry/devilry-django/assets/98320633/4b01a04e-e61a-4487-b4b4-bd7336f1a208">

**Comment by torgeirl** [comment]
It looks like the HTML sanitizer introduced in v6.2 with #1275 also escapes `$math$`/`$mathblock$` for Devilry's `latex_math` modules.

**Comment by torgeirl** [comment]
Solved in v6.2.4.
