### ISSUE TITLE
Add S3 storage backend support for archive creation

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1282]
It looks like `batchframework_admin_compress_assignment` is missing an implementation of `DeliveryStoreInterface` that supports S3 as a storage backend (ie. `storages.backends.s3.S3Storage`) for it to enable the creation of ZIP files while S3 is the storage backend. 

Currently, delivery uploads seems to work fine while ZIP creation fails due to a `PermissionError` when the batch framework attempts to store on a local path instead of the S3 bucket.

**Comment by Levijatan** [comment]
With the new stream-zip based zip generation it does not need to store the zip localy, but could look into this if necessary

**Comment by Levijatan** [comment]
With 4b7965e it does not use local storage to create zips.
