### ISSUE TITLE
Gracefully insert social accounts for existing users

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1283]
If a social account gathered with Django Allauth is missing upon login, it will simply be re-created.

It does however cause an `AssertionError` in `allauth/account/utils.py` in `setup_user_email()`, line 331:
```
assert not EmailAddress.objects.filter(user=user).exists()
```

**Comment by espenak** [comment]
Probably something similar to https://github.com/devilry/trix2/issues/128

**Comment by torgeirl** [comment]
Unable to reproduce the issue with v6.2.2 so it seems this fixed it. :+1:
