### ISSUE TITLE
Updates to background tasks

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1290]
**Issues**
- failure handling for background tasks seem to need a re-work since tasks that failed due to errors such as #1292 don't get listed in [the Django Admin UI](https://github.com/devilry/devilry-django/blob/6.3.1/devilry/devilry_message/admin.py) (should have been listed, and with `Status=Error`)
- we need support tor TLS communication between Gunicorn/RQ worker and the Redis server. [Redis v6 introduced SSL/TLS support](https://redis.io/docs/latest/operate/oss_and_stack/management/security/encryption/) so it looks like this will require Devilry's dependencies to be updated to work with [redis-py](https://github.com/redis/redis-py) 4.0.0+?
- we need support for Redis Sentinel 

**Suggested solution**
- Update [`rq`](https://github.com/rq/rq), [`django-rq`](https://github.com/rq/django-rq) and [`redis`](https://github.com/redis/redis-py) dependencies to releases that support Redis server somewhere from 6.0 (first with TLS support) to 7.2.4 (last Redis release under an open source license)
- do adjustments for Devilry and its RQ Worker to work with Redis Sentinel (if any)
- improve how the background process handles errors
- improve or remove [utils/rq_setup.py](https://github.com/devilry/devilry-django/blob/6.3.0/devilry/utils/rq_setup.py) (no longer needed?)
- update [RQ docs](not_for_deploy/docs/sysadmin/rq.rst) accordingly

**What versions should we aim for**
- `redis` 5.0.0+ [supports Redis server 5.0 to 7.2+ while 4.5.0+ supports Redis server 5.0-7.0](https://github.com/redis/redis-py#supported-redis-versions)
- `rq` 1.15 requires `redis` 4.0.0+, but [due to changes with how its errors are captured by Sentry with probably want 1.16](https://github.com/getsentry/sentry-python/issues/2310)
- `django-rq` 2.8.1 requires `rq` 1.14+ (and 2.8.0 added support for `USERNAME` and `SENTINEL_KWARGS`)

So perhaps `redis==5.0.*`+ `rq==1.16.*` + `django-rq==2.8.*` is an OK place to start while we are on Django 4.2?

**Comment by espenak** [comment]
Only missing some updates to the rq_setup module - need to update it or just document how to setup manually

**Comment by espenak** [comment]
I just kept the quick setup module (rq_setup), but updated the docs for RQ setup with hints for more complex setups like sentinel and https.
