### ISSUE TITLE
Changelogs in official docs for 6.0.1-6.3.1 are missing

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1291]
[not_for_deploy/docs/user/changelog](https://github.com/devilry/devilry-django/tree/6.3.0/not_for_deploy/docs/user/changelog) hasn't be updated since 6.0.0, causing [the official docs](https://devilry.readthedocs.io/en/master/user/changelog_overview.html) to not list the latest changes.

Missing releases:
- 6.0.1
- 6.1.0
- 6.1.1
- 6.2.0
- 6.2.1
- 6.2.2
- 6.2.3
- 6.2.4
- 6.3.0
- 6.3.1

Most of the changes are described in [CHANGELOG.md](https://github.com/devilry/devilry-django/blob/6.3.1/CHANGELOG.md).

**Comment by Levijatan** [comment]
Added them in eef47e5.
