### ISSUE TITLE
Remove old delivery models

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#1304]
We have some old models that was previously used to store deliveries. These are no longer in use:
- ``Delivery``
- ``FileMeta``
- ``Deadline``
- ``StaticFeedback``
- ``UploadedDeliveryFile``
- ``FeedbackDraft``
- ``devilry_gradingsystem`` app:
    - replaced by code in:
        - ``devilry/devilry_admin/views/assignment/gradingconfiguration.py``
        - ``devilry/devilry_group/views/examiner/feedbackfeed_examiner.py``
        - etc..
    - Includes these related apps:
        - devilry.devilry_gradingsystem
        - devilry.devilry_gradingsystemplugin_points
        - devilry.devilry_gradingsystemplugin_approved
        - devilry_gradeform??
- ``devilry/apps/core/deliverystore.py`` (used by the old models)

## Need to include in migration guide
- Removed settings:
   - ``DEVILRY_FSHIERDELIVERYSTORE_ROOT``
   - ``DEVILRY_DELIVERY_STORE_BACKEND``
   - ``DEVILRY_FSHIERDELIVERYSTORE_INTERVAL``
- Changed required settings:
   - ``STORAGES`` (**TODO:** document the required settings and how it fits together)
- Remove from INSTALLED_APPS:
   - ``devilry.devilry_import_v2database``
    - ``devilry.devilry_gradingsystem``
    - ``devilry.devilry_gradingsystemplugin_points``
    - ``devilry.devilry_gradingsystemplugin_approved``

### All student views:
- [x] Add delivery (files) and some comments
- [x] Download delivered files

### All examiner views:
- [x] Add comment
- [x] Add feedback
- [x] Add draft comment
- [x] Add comment not visible to student
- [x] Add self as examiner
- [x] Bulk feedback
- [x] Download delivered assignments
- [x] simple bulk handling of feedback
- [x] Handle deadlines
- [x] Publish drafted message

### All admin views:
- [x] Create Course
- [x] Create Semester
- [x] Create Task

**Comment by espenak** [comment]
@Levijatan this is ready for testing in the ``feature/remove-old-delivery-models/main`` branch.

**Comment by Levijatan** [comment]
Currently it fails to download delivered files because of 
`Failed to generate zip archive from feedbackset 25
Traceback (most recent call last):
  File "/Users/asmundrosendahl/work/devilry-django/devilry/devilry_group/tasks.py", line 23, in execute
    print_memory_usage('Start of RQ task')
  File "/Users/asmundrosendahl/work/devilry-django/devilry/utils/memorydebug.py", line 33, in print_memory_usage
    import humanize
ModuleNotFoundError: No module named 'humanize'`

**Comment by Levijatan** [comment]
Student dashboard says "(4st forsøk)" for the fourth try in Norwegian

**Comment by espenak** [comment]
> Currently it fails to download delivered files because of `Failed to generate zip archive from feedbackset 25 Traceback (most recent call last): File "/Users/asmundrosendahl/work/devilry-django/devilry/devilry_group/tasks.py", line 23, in execute print_memory_usage('Start of RQ task') File "/Users/asmundrosendahl/work/devilry-django/devilry/utils/memorydebug.py", line 33, in print_memory_usage import humanize ModuleNotFoundError: No module named 'humanize'`

Just change
```
DEVILRY_MEMORY_DEBUG_ENABLED = True
```
to ``False`` to avoid that @Levijatan. It should be False, but I must have comitted it as True.

**Comment by Levijatan** [comment]
There are some weirdness around tries but this is hopefully fixed when the fix for #1301 is merged inn. On the fourth try it said "4st forsøk" but on the fifth it says "fjerde forsøk", but the fourth try was given before the third try had been given feedback. The fifth was given through bulk. The fix for #1301 makes it so if there is no feedback given the try deadline is moved instead of creating a new try.

**Comment by Levijatan** [comment]
Getting "Automatisk anonym ID mangler" when "Half anonymization" is enabled. Except when the student and examiner is the same user then it just showes the name of the user.

**Comment by espenak** [comment]
> Getting "Automatisk anonym ID mangler" when "Half anonymization" is enabled. Except when the student and examiner is the same user then it just showes the name of the user.

I do not think this is an issue, just a result of how the anonymization utils / template tags work. It makes sense that you are not anonymized from yourself, AND it makes absolutely no sense to be your own examiner, especially when anonymized (which is typically an exam). The "Automatisk anonym ID mangler" is probably just because of setup in the dev database.
