### ISSUE TITLE
Uploading file implies delivery

### ISSUE THREAD

**Issue by kristahi** [devilry/devilry-django#194]
Again, sorry if this is some strange Ifi-site-specific issue.

Since the file delivery form does not allow you to remove a file that has been uploaded, and since upload begins automatically upon file pick, wrongfully picked files cannot be removed from a delivery.

Furthermore, once at least one file is uploaded, it appears the delivery is, implicitly, irrevocably made, even though the user has not confirmed it by pressing the "Deliver" button. Attempting to interrupt the delivery by browsing to another view, logging out or leaving the site by some other means does not abort or invalidate the delivery.

It is unintuitive and unclear that uploading is basically the same as delivering.
This is unfortunate since users may accidentally upload wrong files, perhaps even containing information they do not wish to share with the examiner/institution.

This could cause some other annoyances, too. At Ifi, for instance, delivery of mandatory assignments implies that the user accepts some guidelines regarding authorship of the assignments and so on, and with this behaviour it could be argued that a seemingly delivered files was not intended to be delivered and that these guidelines were not actually agreed to.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
