### ISSUE TITLE
Make related users the only available users on a period

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#271]
When we get an admin interface where related students and examiners can be administered by a period admin, we should make the related students and examiners the only available students and examiners within that period.
## Advantages:
- Users can be autocompleted from a list with a sane amount of matches.
- Users can be selected from lists.
- We will not get the confusing situation where students on an assignment is not a related student.
## Disadvantages
- Have to add students "twice".
  - I belive this is outweighed by an easier to use admin interface for assignments.
  - Normally related students are dumped in from the syncsystem.
## Other results of the change
- We will be able to refuse non-related students to add deliveries:
  - The use-case is when a student has quit a course mid-semester.
## What happens when we remove a student from related
- The student will, of course, not show up in any views using related. This means:
  - Dropouts are students on an assignment but not in related, which is useful for statistics.
- It will not be possible to add non-related students and examiners to new assignmentgroups, however they will not be removed from existing assignmentgroups.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
