### ISSUE TITLE
Option to keep assignments in sync with related users

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#273]
Related users are examiners and students that an administrator has added to a period. These students are is supposed to be the set of students available for registration on assignments (with #271 this relation will be enforced).
## Why is not related students automatically registered on assignments?

In most cases, all related students on a period will deliverer all assignments on the assignment. However there are some exceptions to this:
- Cooperation on an assignment. In this case, students must be grouped manually.
- Not all students on a period takes the same set of assignments.
## A compromise

Since the reasons listed above are far from the most common cases, I propose that we make keeping related students in sync with assignments two optional features that is enabled by default: the `keep_students_in_sync_with_syncsystem` and `keep_examiners_in_sync_with_syncsystem` attributes of Assignment.
### What should happen when adding new related students:
- On Assignments with `keep_students_in_sync_with_syncsystem==True`:
  - NEVER remove any students or groups from existing AssignmentGroups.
  - Add students that are not on any AssignmentGroup to their own AssignmentGroup automatically.
  - Tag handling:
    - NEVER update tags on AssignmentGroups with the `tags_manually_updated==True`.
    - Update all tags on any AssignmentGroup where `tags_manually_updated==False`.
### What should happen when adding new related examiners:
- On Assignments with `keep_examiners_in_sync_with_syncsystem==True`:
  - NEVER change examiners on any AssignmentGroup with `examiners_manually_changed==True`.
  - On AssignmentGroup with `examiners_manually_changed==False`, add related-examiners on any AssignmentGroup with at least one tag in common with the related-examiner.
### When the keep_XXX_in_sync_with_syncsystem attributes change:

If an `keep_XXX_in_sync_with_syncsystem` is changed from `False` to `True`, the logic in the appropriate of the two previous sections should be executed.
### Attributes added to core

The _Assignment_ model will need two new attributes: `keep_students_in_sync_with_syncsystem` and `keep_students_in_sync_with_syncsystem`

The _AssignmentGroup_ model will need two new attributes: `examiners_manually_changed`, `tags_manually_updated`.
### Apps

Should be implemented as two separate Django applications: One for the students logic and one for the examiner logic.

This approach makes it possible to opt out of one or both of these hooks. This makes it easy to replace this logic with something else if we find weaknesses with this approach, or if these hooks are inappropriate for some educational institution (they can make their own Django app(s) with their logic).

Since disabling these apps will make the new core attributes useless, we may consider using a one-to-one relation for them instead. However, I believe that they are general enough to deserve an attirbute in the core, and they should be usable by an alternative to these apps, since they do not express any logic, just state or desire for a broadly defined feature.
### UI integration

Since we will need to add options for `keep_students_in_sync_with_syncsystem` and `keep_students_in_sync_with_syncsystem` in the user interface, we will need to create plugins for the _subjectadmin_ app in each of the apps that adds the field when the app is enabled.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
