### ISSUE TITLE
Handle multiple input formats

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#280]
We should be able to handle multiple input formats for feedback. Plone (http://plone.org) handles this smoothly, so we should probably just more or less copy their solution:
- Default to a very user friendly format. We should probably use a WYSIWYG html editor as default.
- Allow users to change the input format, but that will clear the current input.
  - We assume that the common use case is to change format _before_ we start editing.
  - Avoid data loss by saving a draft before changing the format. The can then copy over anything they want from the draft. This requires #282 to be implemented first.
- Allow users to change their preferred default input format in their settings.
## Avoiding the unlimited number of input formats mess

When we allow multiple input formats we can easily end up with a lot of formats where none of them are supported 100%. To avoid this I propose that any new format should have a clear use case. To start with this should be:
- HTML (WYSIWYG) for simple feedback.
- Markdown for power-features like LaTeX math and code syntax highlighting.
  - Should add a markdown plugin suitable for pasting plain text. Indenting it 4 spaces is not optimal. Something like the github flavored markdown solution with 4 spaces **and** an alternative that does not required indent is better.
- Plain text. Displayed as it is shown in the _textarea_, with monospace font and line wrapping.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
