### ISSUE TITLE
Commandline client

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#339]
We have had several attempts at creating a good command-line client. I believe the cli should have the following properties:
- Simple and plugin-based. This means that users should be able to put their own extensions in a local folder.
- Should make it easy to provide feedback for simple grade editors (like approved/not approved).
- Complex grade editors should be handled by plugins, and the default fallback should be to open a browser.
- Should work like a VCS:
  - Sync data from the Devilry server to a local file hierarchy.
  - Add feedback
  - Commit the changes back to the Devilry server.
## Building blocks

The command line client should use [devilryrestfullib](https://github.com/devilry/devilryrestfullib). A lot of code for the client is already completed in [devilry-cliscripts](https://github.com/devilry/devilry-cliscripts) in the `devilryclient/` folder. The `devilryclient`-folder includes code to sync data from the Devilry server into a local file hierarchy (which probably is the hardest part of developing the client).

**Comment by olejorgenb** [comment]
Could the wiki page https://github.com/devilry/devilry-django/wiki/Commandline-client please be removed if I understand correctly that that project is totally abandoned and might not even work (never got that far as it seems to need python2.6?)

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
