### ISSUE TITLE
Download all deliveries as course admin

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#401]
Course admins should be able to download all deliveries for each of their assignments.
## Solution

I suggest that we simply allow admins to access the "download all deliveries" API used by the Examiner UI, and add a link to that from the assignment overview page for admins.
## Workaround while we fix this issue

The workaround is to add yourself as examiner for all students on each assignment.
1. Navigate to the assignment overview for your assignment.
2. Click the _Students_ link.
3. At the top of the list of groups, click `Select->Select all`.
4. Select **Add** examiners, and add yourself as examiner. Follow the link in the help-text if you need to add yourself as examiner on the semester (depends on how your course is configured).
5. Use the breadcrumbs in the header to navigate back to the assignment overview (click the assignment name). Then use black button labeled _Go to examiner interface_ in the dark blue box between the links and the _dangerous actions_ box.
6. Click the _Download all deliveries_ button in the upper right corner.

**Comment by espenak** [comment]
We need to solve this for 3.0. Should be possible with the same new file download system that we use for examiner bulk downloads, but if it does not scale well to 1000 students, we may need to add an API and CLI utility as a workaround for 3.0.

**Comment by torgeirl** [comment]
Fixed in v3.3.2 :tada:
