### ISSUE TITLE
UI to detect good system maintenance times

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#409]
Sysadmins should have an UI that groups upcoming deadlines in a way that makes it easy to see when it is practical to perform system maintenance tasks, like updates.

I think a list of the next 30 days should be sufficient (with an option to show more days). Each day should list deadlines and the number of students and courses on each deadline.

We should also provide a list of good maintenance windows. I believe any time with more than 30min after a deadline, and more than 4 hours before another deadline would be a good default, at least for quick maintenance tasks.

It should also be possible to choose a timespan for maintenance, and get a list of affected assignments/deadlines, and a way to notify the administrators on the affected courses so they can move their deadlines. The UI should also have an option to notify all affected students (use case: critical problems, like security bug patching).

**Comment by torgeirl** [comment]
@espenak: how about making this more generic than a maintenance-window identification tool just for sysadmins (#399 suggest it should be including it the superuser UI), and rather make it a view available for both system and department administrators from the administrator view? I imagine something like the contributions graphic here on Github, but for the current and following four weeks, the number of students with a deadline intensifies the color of the day (the number of deadlines is less important than the number of students with deadlines).

- For department administrators, concatenate the deadlines of all subjects on the department (multiple graphs in the rare instance a n user has the role of department administrators at multiple departments).
- For system administrators, show one that concatenate all deadlines and one for each department.

Hovering/clicking the day could say how many students with deadline that day, and list the deadlines and the shortname of the subjects on that deadline. Ie.:

- 850 deliveries total
- 12:00 (150): SUB4321
- 15:00 (100): SUB2020
- 23:59 (600): SUB2010, SUB4000

**Comment by torgeirl** [comment]
No longer relevant.
