### ISSUE TITLE
Candiate ID editor on assignments

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#413]
We need to be able to:
- Edit candidate IDs on individual candidates.
- Edit candidate IDs in bulk.
- Import candidate IDs from CSV.

Note that this does not have the highest priority, because the preferred and most efficient method is to set candidate IDs on a semester, and re-use that when adding students to assignments (which happens automatically by default with the create new assignment wizard).

Bulk import for semesters will be implemented in #381. We may want to skip bulk editing and CSV import in favor of a _Sync candidate IDs from the semester_ wizard.

**Comment by torgeirl** [comment]
There is currently no need to handle candidate IDs on assignments; it's only relevant on the semester (issue #792).
