### ISSUE TITLE
Removing students from groups does not work when HARD deadlines have expired

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#414]
This is basically the same issue as #407. When we split a group, we copy all deliveries made by  student into a new group. That means we have to create new deliveries, and the Delivery-model checks for expired HARD deadlines.

We can solve this in two ways:
1. Work around the issue for this case only.
2. Move hard-deadline checking to the add-delivery API.

I believe the second solution is best, because it allows us to let admins and examiner APIs ignore hard deadlines. Using the second solution also solves the examiner API issue in #407 that we had to postpone because the the UI uses old frozen APIs.

**Comment by torgeirl** [comment]
This should no longer be an issue with the current release.
