### ISSUE TITLE
More specific list of code block language support

### ISSUE THREAD

**Issue by patrisk** [devilry/devilry-django#421]
In the course INF2270 students have a mandatory assignment where they have to program in x86-assembler. The help for code block links to pygments which only lists support for "Assembly (Various)" without specifying which assembler languages they support. 

It would be nice if devilry listed every supported language without linking to a third-party site (And what the keyword for each language is).

**Comment by torgeirl** [comment]
I believe this was partly solved in Devilry 3.x, and we're currently working on replacing the Devilry 3.x editor (#1217) with something that also should support code and math block even better.
