### ISSUE TITLE
Parts of feedback not showing in feedback with LaTeX math

### ISSUE THREAD

**Issue by Sardtok** [devilry/devilry-django#425]
This seems to be a MathJAX + jQuery problem. The box containing the feedback is sized upon first rendering the text, then MathJAX converts LaTeX, which may increase the size of the feedback so it disappears behind the bottom edge.

Resizing the window (or making the window resized by opening the debugger) or switching tabs, will force it to render again, which will make the box get the appropriate size showing the rest of the content.

I suggest adding a callback to have jQuery re-render the box when MathJAX is done or wait until MathJAX is done before rendering.

**Comment by torgeirl** [comment]
I assume this was solved somewhere between Devilry 1.2.x and 3.x, and if not it should be solved by replacing the ACE editor (issue #1217).
