### ISSUE TITLE
Make it impossible to get unsuccessful/incomplete deliveries

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#427]
Today, students have to first upload their files, and then click _Submit delivery_. Some students (a very low percent, but it happens), forget to click submit delivery. We should be able to avoid this.
## Solution

We assume that students actually want to add any delivery that they have added, so the default should be to mark the delivery as successful. However, we want students to be able to add multiple files, so we can not mark it as `successful` (which also implies completed) at once. We can solve this as follows:
- We change the `successful`-attribute to a timestamp named `publish_timestamp`.
- Each time a student adds a file on a delivery, `publish_timestamp` is set a couple of minutes in the future.
- After at least one file has been uploaded, the UI shows the student a message with something like this text:
  
  ```
  Your delivery will be submitted automatically in
  [X] minutes and  [Y] seconds unless you add more
  files, or choose to abort the delivery. Click
  *Submit delivery* to submit at once.
  ```
- The UI must, of course, also show the implied big red _Abort delivery_ and big green _Submit delivery_ buttons.
- All examiner and admin APIs must be updated to filter on `now > published_timestamp` instead of `successful==True`

**Comment by torgeirl** [comment]
Solved in #1210 / #1217.
