### ISSUE TITLE
Drag and drop feedback into Devilry

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#428]
I belive it would be very useful for examiners to drag and drop files into Devilry. This would make it possible to:
1. Drag a file containing the course name and some info about the student, like `duck1010 oblig1 Peter Pan.pdf`, into the examiner UI
2. Confirm that this is feedback for DUCK1010 oblig1 for Peter Pan, and select a grade.
## Optimizations/intelligent selection

When browsing a specific assignment, we will assume that the file is feedback for that assignment, in which case `Peter Pan` would be all the information needed in the filename.

When browsing a specific group (student), any file dragged into the window will be assumed to be a feedback.
## Who will this help?

This will help users who write their feedback text in external programs, like LaTeX, Word, etc.

It may also be useful for people who work in the terminal, because they can do all the work in the local filesystem (white `.txt` or `.md` files), and just drag the results into Devilry when it is convenient.
## Who is this not for

This is not for new users with no prior experience, it is for users with advanced requirements and lots of assignments.
## Multifile drag and drop

I belive HTML5 makes it possible to drag many files, and even folders. This should make it possible to drag an entire folder of feedback texts into the Examiner UI, confirm them all, and be done with creating feedback.
## Automatic grade discovery

We can also autosuggest the grade from the filename for simple grading systems (E.g.: `duck1010 oblig1 Peter Pan (approved).pdf`).
## Summing it up in a workflow
1. Examiner downloads all deliveries on an assignment.
2. For each delivery, they write a feedback text in a separate folder (lets call it `feedback duck1010 oblig1/`. The filename of each file contains the name, username or candidate ID of the student and, optionally, the grade.
3. The examiner drags the `feedback duck1010 oblig1/` into the browser, confirms, and the job is done.

**Comment by torgeirl** [comment]
No longer relevant.
