### ISSUE TITLE
Make it hard to not include a message when adding or moving a deadline

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#435]
It is usually a good idea to give a message when adding, and especially when moving a deadline. To make this a natural part of the workflow, we may want to force the user to actively choose _not_ to include a message.

Note that this should only be implemented in the client code for some views, not in the core.
## Mockup

This mockup shows how it could look when adding a deadline as administrator. The same checkbox should be available when moving/editing a deadline, and we should include it in the examiner UI when we update that later this year.

![add_deadline_no_message](https://f.cloud.github.com/assets/84501/918444/c84926e4-feb4-11e2-91db-22860ecb11ff.png)
## Details

Clicking the checkbox should toggle show/hide of the text input field above it. Unless the user checks the checkbox, they should not be able to save without a deadline message.

**Comment by torgeirl** [comment]
This should be fixed in the current release.
