### ISSUE TITLE
Permission cache

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#450]
We should maintain a permission cache which makes lookups for permission on any object in core be max one query, and often hit the Memcache cache.

I think something quite close to the Django permission system is good, but with good object permission support. Each entry in the cache should have these fields:
- `user_or_group`: Generic foreign key to a user or a group.
- `object`: A generic foreign key to the object.
- `permission`: A string, like `can_add`, `can_edit`, etc.

These operations need to be very efficient:
- Check if a user has some `permission` on an object.
- Filter all objects within a list of objects or objects IDs where a user has some `permission`.
## How

Each time a user or group is added or removed from an object, they need to be synked into the permission cache. This is easy with Django `post_save` hooks.

**Comment by torgeirl** [comment]
No longer relevant.
