### ISSUE TITLE
Multiple uploads in one dialog (OS X)

### ISSUE THREAD

**Issue by anton164** [devilry/devilry-django#451]
When uploading files to Devilry it says that 'You can upload multiple files.', which is true, however at the moment it is not possible to select multiple files in one dialog with either SHIFT or CMD/CTRL-clicks. 

This small enhancement would make uploading many files much less tedious.

-Anton

**Comment by espenak** [comment]
Seems we forgot to close this issue when Devilry 2.0 was released with a solution.
