### ISSUE TITLE
Problem with search function for students in semester

### ISSUE THREAD

**Issue by eigilhs** [devilry/devilry-django#452]
Through the following work flow as course administrator, a get a problem with the search function for students in a semester:

Going to a semester -> students on semester -> searching for 'something' -> going back to the semester -> opening an assignment -> opening students on the assignment -> going back to the semester -> showing students on semester

Now i get the matches for 'something' no matter what I type in the search field. I now have to go to the Devilry front page and back to make it work again.

**Comment by torgeirl** [comment]
No longer relevant.
