### ISSUE TITLE
Use Django sentry

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#456]
[https://github.com/getsentry/sentry](Sentry) is a logging server developed by DISQUS and others. If we log everything happening in Devilry (which we mostly do already), this will:
- Be a huge help to administrators trying to track down complains from users (because searching up failed uploads and the like will be quick and easy).
- Help us visualize daily "load", which can be a big help in cases like #409. Unlike  pure system load tracing, I think Sentry will enable us to vizualize only delivery load, by filtering just that log.
- Avoid having to give people read-write access to the server to access logs. It may be natural to allow some administrative people access to the Devilry logs, but not to the servers running Devilry. This could of course be solved with a write only shared filesystem too.
- Generate browser stats (http://sentry.readthedocs.org/en/latest/plugins/).
- Far better debugging experience because Sentry stores the version of all packages _at the time of the log_.

**Comment by torgeirl** [comment]
We're using Sentry in our production environment. I'll make some updates to the docs on Sentry and (for issue #474) how to configure logging in `settings.py`.
