### ISSUE TITLE
Nested-reset within the bootstrap css class/scope

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#459]
We use the `bootstrap` css class on all ExtJS components that uses bootstrap. This works OK now, but it will work a lot cleaner and less vulnerable to changes to the ExtJS css if we use a nested reset within the `bootstrap` class.
## Problems

The only problem is that it will most likely break small things in the layout of a few views, most notably the group manager in the subjectadmin UI.
## Advantages
- Allows us to use all of bootstrap.
- Makes it far less likely that the ExtJS styles will break the bootstrap styles.
- Makes it much easier to update to bootstrap3.

**Comment by torgeirl** [comment]
No longer relevant.
