### ISSUE TITLE
Plugin-based delivery

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#466]
Deliveries should be plugin-based, just like grading system plugins. I think we should use our experiences after we have created #465 to create such a system.
## What kind of plugins have been discussed?
- File upload like today.
- Forms (answer questions). Should support freetext and choice from a set of possible answers. Suggested by Roger Antonsen(@rantonse) and Jørgen Trømborg.
- Automatic grading and smart suggestions. This would be a fairly compex plugin, but it would enable courses to design assignments where students is not just graded, but also get help to improve themselves. Suggested by Professor Anders Malthe-Sørenssen.

This means that a delivery plugins would need to be able to do more or less anything, as long as they end up creating a Delivery-object in the core data structure. Ideally, a delivery plugin should be a Django app that hooks itself up using fairly simple APIs, with layers of complexity for the complex plugins like _Automatic grading_.

**Comment by torgeirl** [comment]
> * Forms (answer questions). Should support freetext and choice from a set of possible answers. Suggested by Roger Antonsen(@rantonse) and Jørgen Trømborg.

The sector already have other systems that handles form data (ie Nettskjema), and it's probably best to use those instead of adding more complexity to Devilry.

> * Automatic grading and smart suggestions. This would be a fairly compex plugin, but it would enable courses to design assignments where students is not just graded, but also get help to improve themselves. Suggested by Professor Anders Malthe-Sørenssen.

I believe this is better covered by #1136 (Rubric-based assessment).

Another related issue is #990 (Git repo as delivery type).

Closing this issue since this is covered by other, more recent issues.
