### ISSUE TITLE
A general purpose notification system

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#471]
We should have a system for sending messages to users that:
- Send through a queue.
- Stores all sent messages in the database.
- Supports multiple endpoints, where email is one endpoint.
## Endpoints

Endpoints must use a plugin architecture, and it must be possible to use multiple endpoints. Examples of possible endpoints:
- Email
- SMS
- iOS notifications
- Other message queues (push a notification to a system embedding Devilry each time a new assignment is added).
## Message structure

I think each message should have the following fields:
- `sender` - A User.
- `subject` - In many cases, a subject may be the topic name (explained below), but that should be up to the programmer.
- `body`
- `bodyformat` (plaintext, html, markdown)
- `topic` (explained below)
## Topics - let users choose what to receive, and where to receive it

I think each message should have a `Topic`. A `Topic` is a description of the type of message. Examples of topics:
- `"New feedback"`
- `"New delivery from student where you are examiner"`
- `"New delivery from student where you are admin"`
- `"One or more of your courses need to mark students as qualified for exams"`

A user can choose which _endpoint_ to receive each topic on.
### Required and optional topics

An admin chooses if a topic is required or not. If a topic is required, users are required to select an endpoint for it, but if it is not required, they can disable notifications for that topic.
## Notification - How to notify a user about a message

To actually send a notification to a user, we create a `Notification`. A Notification has the following fields:
- `message`
- `user`
- `sent_datetime`

When the notification is added to the database, users will be able to view the notification through their inbox on the web, but it is not sent to an enpoint. That part is handled by the `MessageSender`.
## MessageSender - How to send a message to an endpoint

`MessageSender` is an abstract base-class for message senders. A message sender gets a notification, and has to send it to the appropriate endpoints. The default `MessageSender` does that directly, but we should implement a `CeleryQueueMessageSender` that adds each notification to a background queue, and process+sends them in the background.
## Show unread messages?

A challenge with a distributed notification system is that we do not know if a notification has been read or not. Most messages will have a link back to the system with details, so we could wrap those links in a redirect that marks a message a _read_. I think this is unneeded complexity. Should be enough that users get notification on their chosen endpoints, and that they can see their full notification history through the web.

**Comment by torgeirl** [comment]
No longer relevant.
