### ISSUE TITLE
Ability to press return in deadline text field

### ISSUE THREAD

**Issue by eigilhs** [devilry/devilry-django#475]
As it is now, return publishes the text instead of adding a newline. I have had to copy-paste a newline character. Is there a better way?

Also, it would be helpful to make it clear somewhere that the field supports HTML-formatting, and even more helpful if you could add the text when creating an assignment in the first place.

**Comment by torgeirl** [comment]
Since this issue predates Devilry 3.x (huge UI overhaul) I assume this problem has been solved.
