### ISSUE TITLE
Improved group/student listing

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#482]
The student/group listing on assignments could use some improvements:
- It is not optimal on huge courses (it works, but it is a bit slow).
- We may want to split it in two:
  - One optimized listing view where we have much more actions, filters, sort and search options than today. Should probably be a grid of some sort.
  - One details view.
- We should implement it in native HTML components. ExtJS grid is simply to slow.
- We may want to sort in the REST-API because localeCompare has the problem that you get english sort if you have an english browser. When Devilry is running in a non-english country, you will normally want to sort with the locale of that country, because most users will have names with letters from that locale.

**Comment by torgeirl** [comment]
No longer relevant.
