### ISSUE TITLE
Let students delete their own deliveries

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#484]
Students should be able to delete deliveries from Devilry. They need to be given a huge warning that the delete is permannent.
## Challenges

Handle deliveries with feedback and comments (comming in the next major version).
## Implementation

I think we should implement this as a boolean on delivery coupled with removing any files. We will leave the delivery, but it will only be a placeholder. Any feedback and comments will still be available, but the delivery will be shown as:

> This delivery was deleted by **user**

On anonymous assignments, we should show something like this:

> This delivery was deleted by **the student that uploaded it**
## Permissions

Only the user that uploaded the delivery should be able to delete it. This will avoid sabotage from a student on a project group. It will also make it very easy to blame the person that deleted the delivery (they will still be the `uploaded_by`-user).

**Comment by torgeirl** [comment]
I believe this functionality is not needed, and there are a lot of issues its implementation could introduce so I think we should leave this as-is.
