### ISSUE TITLE
Examiner statistics should not use pie charts to illustrate the numbers for individua examiners

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#490]
When we have the very common case that all students are corrected and no one is waiting for feedback or for deadlines to expire, we get overlapping text for the empty cake pieces. I think it would be better with a bar chart where each column represents the numbers currently in the pie chart.

We may also want to show a chart with the grades of all students the examiner has corrected, and illustrate the average number of points with a horizontal line. This may be a very heavy operation for huge courses, so this should probably be a chart that the user has to click a button to render.

**Comment by torgeirl** [comment]
No longer relevant.
