### ISSUE TITLE
Store status on the AssignmentGroup database model

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#492]
We already have the logic for this in the `get_status` method. `get_status` implements the following algorithm:

```
- If open:
    - If before deadline:
        - ``waiting-for-deliveries``
    - If after deadline:
        - ``waiting-for-feedback``
    - If no deadlines
        - ``no-deadlines``
- If closed:
    - If feedback:
        - ``corrected``
    - If not:
        - ``closed-without-feedback``
```

The only issue is that `waiting-for-feedback` and `waiting-for-deliveries` is relative to the current time. Therefore we should add the following statuses to the database:
- `no-deadlines`
- `corrected`
- `closed-without-feedback`
- `waiting-for-something`

To filter the `waiting-for-feecback` and `waiting-for-deliveries` statuses from these _static_ statuses stored in the database, we should add a `filter_by_status` method to the `AssignmentGroupQueryset` as outlined in #491.

**Comment by torgeirl** [comment]
No longer relevant.
