### ISSUE TITLE
StaticFeedback history view on a delivery

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#494]
We should have a view that the delivery workspace (#461) uses to list all feedbacks. This view should:
- Show if a feedback was published or not
- Enable examiners to view the diff between two feedbacks (should be a separate view).
- Enable examiners to revert to a previous feedback.

This is very important when we get autosave, because it will allow examiners to loose more or less no work even if the browser crashes. If we get an offline mode this will be even more important because the easiest methot of handling resume after offline is just to add a new staticfeedback, and as long as examiners can revert, that will not destroy anything they may have changed on another machine in the meantime.

**Comment by torgeirl** [comment]
No longer relevant.
