### ISSUE TITLE
Some way to close groups without any deliveries.

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#504]
They are currently shown as _waiting for feedback_, and an examiner needs to be able to close them. We should handle this as follows:
- For groups without deliveries, instead of linking to the latest delivery from the `allgroupsoverview`, we should link to `singlegroupoverview`.
- We should show a message with a button in ``singlegroupoverview:
  
  > This group has no deliveries, and their deadline has expired. Would you like to fail the students on this assignment?
- We should have view for listing groups without deliveres. This view should make it possible to fail (close) all groups with no deliveries and no deadlines. I do not think we need to provide the ability to select a subset of groups in this tab. The natural way of handling that should be to add a new deadline to the exceptions, and come back to the view to close/fail the rest of the groups.
- We should show a message in the `allgroupsview` _waiting for feedback_ tab if we have any groups without deliveries, with a link to the _groups without deliveries_ view.

**Comment by torgeirl** [comment]
This has been possible for some years now by giving feedback to multiple groups filtered for groups without uploads.
