### ISSUE TITLE
Response templates for examiners

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#507]
## Basic idea

Inspired by the _Canned responses_ gmail labs addon. Should provide the ability to save the current feedback currently beeing edited as a template. Available as a button at the top of the editor (just like italic, bold, etc.).
## Most recent feedbacks available by default?

We should also provide the ability to copy recent feedbacks (something like the last 10). I think this should be implemented like this:

``` python
StaticFeedback.objects.filter_examine_has_access(user).order_by('-save_timestamp')[:10]
```

**Comment by torgeirl** [comment]
No longer relevant.
