### ISSUE TITLE
Test with screenreaders and gamepads

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#508]
We want our UI to be universally available. We already test all new UIs on touch devices in addition to traditional screens/input devices. We should extend this to testing with:
- Screenreaders (or with accessibility enabled)
- Gamepads
## Gamepads??

Gamepads may seem like a stretch. I do NOT suggest this because I think a major part of our users will use the Playstation4 or Xbox One browsers with Devilry, it is simply a check to ensure that our UI is structured logically and semantically correct.
## Amount of work?

This will only require us to be more strict to semantics. It should not cost us anything extra as soon as we get in the habit (it will be just like responsive designs, which is second nature by now).

**Comment by torgeirl** [comment]
Testing with screen readers and voice-over was included in the universal accessibility testing we were involved in last June. It  revealed some points for improvement.
