### ISSUE TITLE
Core support for cooperative grading (multiple examiners on one delivery)

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#509]
We need to support multiple examiners correcting the same delivery.
## Providing feedback as normal

Examiner should to provide feedback just like they do when there is a single examiner.
## Modes

We need to support different modes of grading (`feedback_publish_mode` attribute on `devilry.apps.core.models.Assignment`).
### Mode: Last published by any examiner

The _Last published by any examiner_ mode, works as it does today. The last published feedback by any examiner on a group is their final grade on that assignment.
### Mode: Forced agreement

We need a mode that requires all examiners on a group to agree on the grade before it is published.

Devilry should be able to calculate a grade from the average number of points provided by the examiners. This should be limited by a maximum number of point difference in points allowed - defined by a course admin. Examples:
1. Examiner1 gives 72 points and examiner2 gives 80 points, the maximum point difference is 10 points, so the system automatically calculates the final grade a 76 points.
2. Examiner1 gives 72 points and examiner2 gives 80 points, the maximum point difference is 5 points. The system detects that this is to great a difference, and asks both examiners to revaluate their results, informing them of the number of points provided by the other examiner.

Examiners can still adjust their feedback after a feedback has been published, but it will still be limited by the feedback provided by the other examiner(s).
### Mode: Course admin has to confirm

In this mode, examiners can _publish internally_, but the feedback is only published when a course admin has confirmed. This is just a suggestion that we may want to implement if the need arises. We have no actual courses requesting this feature at this time.
## Required features in the grading system

The new version of the grading system (#465) needs the following features for this to work:
- A grading system needs a method to calculate the grade from a number of points. This is required if we are to be able to calculate an average number of points and create a final grade from that average. **This solves itself with #511, because we decouple the point-to-grade mapping from the grading plugins**.
## Required changes to the feedback system

We need a layer in the grading system framework or in the core where we can save _internally published_ feedbacks from a single examiner. I think this belongs in the grading system framework because the core should only contain the important data (published grades), not drafts.

I think we can make this easy to handle:

> When a `FeedbackDraft` is published, we check the `feedback_publish_mode`. We only create a `StaticFeedback` if the requirements for the current `feedback_publish_mode` is met.
## Showing examiners that the grade is published by them, but waiting for other examiners?

We should also have some efficent way of showing examiners that the grade is published internally. I think this should be handled using the `delivery_state` field on `AssignmentGroup`. The only problem with this is that we create a tight coupling **from** the core to the grading system framework. To avoid this, I suggest a new `feedback_status` field on Delivery, which we update each time a `FeedbackDraft` is published. The `feedback_status` is then used to update `AssignmentGroup.delivery_status`.

**Comment by espenak** [comment]
#765 will add a subset of these features, and we will most likely extend that to cover everything in this proposal.

**Comment by torgeirl** [comment]
No longer relevant.
