### ISSUE TITLE
Better documentation for how deadlines should be used

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#515]
We need to make it clear (in the bulk add deadlines views) that deadlines should be added _when needed_, and not added beforehand. What we need to explain:
- If adding 3 deadline, the latest deadline will be used, and the older deadlines will just take up space in the UI without ever getting any deliveries.
- Examiners can give students as many chances as they like by adding another deadline if they give students a failing grade.

**Comment by torgeirl** [comment]
No longer relevant.
