### ISSUE TITLE
Create project groups in bulk from CSV, YAML and JSON

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#525]
We should make it possible import project group setups in bulk. This has two use cases:
1. Import from other systems.
2. Import from manually maintained lists (typically in a spreadsheat).
### YAML

The YAML format is well suited for import from dumps from other systems, but it is also well suited to write manually:

``` yaml
-
  name: The gods
  students:
    - thor
    - loki
-
  students:
    - dewey
    - louie
    - huey
-
  name: The awesome project
  students:
    - daisy
    - clarabelle
```
### JSON

The json should basically be the same as the YAML format, and it is intended for import of dumps from other systems:

``` json
[
    {
        "name": "The gods",
        "students": ["thor", "loki"]
    },
    {
        "students": ["dewey", "louie", "huey"]
    },
    {
        "name": "The awesome project",
        "students": ["daisy", "clarabelle"]
    }
]
```
### CSV

I think the CSV format should be:

```
username1,username2,...,usernameN,#<group name>(optional)
```

Note that the group name is prefixed with `#` to separate it from usernames. Example:

```
thor,loki,#The gods
dewey,louie,huey
daisy,clarabelle,#The awesome project
```
## Implementation

The YAML and JSON imports are very straigtforward; the formats parse to the same Python representation. We just need a small wrapper that convert the CSV into the same internal representation that the YAML and JSON formats use.

To actually create the groups, I think we should do the following:
1. Split up any existing groups where any of the students in the import is a member. The UI should show a warning before doing this. After this, each group should be in a group alone.
2. Loop through all the project groups in the import. For each project group in the import:
   1. Merge the groups for all the students in the imported project group.
   2. Set the name if the imported project group has a name.

See also #526.

**Comment by torgeirl** [comment]
No longer relevant.
