### ISSUE TITLE
Error in status (No Deliveries)

### ISSUE THREAD

**Issue by tworide** [devilry/devilry-django#541]
Gives an error messages saying that the delivery is not the last one made on the assignment.

![selection_040](https://f.cloud.github.com/assets/93136/2180356/48e483c8-9714-11e3-8b2f-50e08df2c446.png)

![selection_039](https://f.cloud.github.com/assets/93136/2180352/10415bea-9714-11e3-8d74-02b826f6b418.png)

**Comment by torgeirl** [comment]
I seems this was solved in the Spring of 2014.
