### ISSUE TITLE
Unable to delete a group or student after they have delivered an assignment.

### ISSUE THREAD

**Issue by realmunk** [devilry/devilry-django#550]
After confirming the delete, the left hand interface is stuck in "Saving ..." .

Log from console: 
Failed to load resource: the server responded with a status of 403 (FORBIDDEN) https://devilry.ifi.uio.no/devilry_subjectadmin/rest/group/1291/?_dc=1393598720782&format=json&examinersOnly=&tagsOnly=
Uncaught TypeError: Cannot call method 'setLoading' of undefined

**Comment by torgeirl** [comment]
> We should mark this as a bug, not because of the default behavior, but because of the error in the console.

The current behavior should be correct now and this issue can be set as solved.
