### ISSUE TITLE
Possible for examiners to change the status of a group

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#558]
It is possible to get the wrong status via this workflow:
1. Create a new deadline
2. Add feedback to a delivery that is not on the newly created deadline

The status will be "corrected" after this, but the examiner does most likely mean that the deadline added in step 1 should be the active deadline, and that the status should be "corrected". I suggest that we show a message with a button to "re-activate" the deadline in the case when status is corrected and active deadline has no deliveries.

**Comment by torgeirl** [comment]
No longer relevant.
