### ISSUE TITLE
Calendar overview of important events in a period

### ISSUE THREAD

**Issue by tworide** [devilry/devilry-django#559]
In it's simplest form this should be a plain calendar view with the events marked. For maintenance administrators updating the system the calendar can map out dates with low activity and avoid downtime when the system are heavily used as when several assignments have deadline.

This will be expanded so that course administrators can find optimal deadlines for their assignments. Also with extra logic handling optimal dates within the constraints of how the other courses with the same generation of students are setting their deadlines.

**Comment by torgeirl** [comment]
No longer relevant.
