### ISSUE TITLE
The Next-button is disabled in "create new non-electronic assignment"

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#561]
To reproduce this:
1. Click "Create new assignment"
2. Fill in the fields in order (name, short name, and select "Not using Devilry").
3. The Next button should still be disabled.

This seems to be because the "Submission date" field does not validate.
## Workaround

You just need to fill in a valid "Submission date" before the field is hidden. I.E.:
1. Click "Create new assignment"
2. Leave _Using devilry_ selected in _How do students add deliveries_, and fill in all the other fields, including a valid "Submission date".
3. Select _Not using devilry_.
4. The Next button should now be enabled.

**Comment by torgeirl** [comment]
No longer relevant.
