### ISSUE TITLE
Better handling of non-electronic assignments and conversion to electronic assignment

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#562]
Non-electronic deliveries should be created when an examiner adds feedback. This will make them work exactly as they do on electronic assignments. This will enable us to convert between electronic and non-electronic assignments.

The only remaining challenge when converting between non-electronic and electronic assignment is handling of deadlines. On non-electronic assignmets, we create a "fake" deadline where we add deliveries. We may have to ask the user to define a datetime for this fake deadline during conversion.

**Comment by torgeirl** [comment]
No longer relevant.
