### ISSUE TITLE
Preview project group before confirming merge

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#564]
I think we should add preview of groups after the merge, and more obvious confirmation handling:
- User must always confirm when creating a group --- mostly like it is is now with the addition of the preview.
- When any of the groups have deliveries, require the user to type "YES" into a confirm box.
- When merging more than 5 groups: Use "danger" style (currently big red box) for the confirm box.

**Comment by torgeirl** [comment]
No longer relevant.
