### ISSUE TITLE
Document how to create, update and remove objects in core

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#573]
We are building an efficient higher level API for creating and updating objects in the core, starting with #554. We will add some cached fields and workarounds to get the performance we need, and that means that it is _very_ important to:
1. Document these cases with a warning in the docstring for the data model. I.E.:
   
   ``` python
   class MyModel(models.Model):
       """
       Something...
   
       .. warning::
   
           Unless you know exactly what you are doing, NEVER create objects
           of this model in the normal Django way. This model uses cached fields
           for higher performance. This is handled by
           :meth:`MyModelManager.bulkadd_mymodel`.
       """
   ```
2. Add a _Creating core data_ guide with examples and links.
## Models that needs to be in the guide

This list is incomplete:
- Candidate (Candidate.objects.bulkadd_candidates_to_groups)
- Examiner (Examiner.objects.bulkadd_examiners_to_groups)

**Comment by torgeirl** [comment]
No longer relevant.
