### ISSUE TITLE
Order listings by last name

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#575]
This is needed (at least at UiO) for integration with legacy systems where all listings are ordered by the last name of the user. We could do something like http://stackoverflow.com/a/3053767, but it does not work in SQLITE. That may not matter? We could check for supported database backends (mysql and postgres should work) in those few places where this is required, and just exclude the option to order by last name when the database does not support splitting on whitespace.

Other options:
- Perform the sort clientside. Bad because it requires us to fetch all results to sort them (can not page).
- Cached field (in devilryuserprofile) just for unsupported databases.

**Comment by torgeirl** [comment]
No longer relevant.
