### ISSUE TITLE
Updated name and email-addresses

### ISSUE THREAD

**Issue by tworide** [devilry/devilry-django#579]
Løsning: Kan fås fra Weblogin eller FEIDE. Devilry må undersøke om de, som leverandør, har anledning til å bruke Weblogin eller søke om å bli tjenesteleverandør med tilknytning til FEIDE. FEIDE framstår som en fremtidsrettet løsning for Devilry, siden den brukes av hele sektoren, mens Weblogin er kun for UiO.

source: http://www.usit.uio.no/om/organisasjon/uav/admit/uait/moter/2014/Devilry-status-behov

**Comment by torgeirl** [comment]
This has later been added in our Oauth 2.0 authentication implimentation: a Feide authentication will return both name and email, and Devilry will update the user. It works quite well, and save sysadmins from having to update users manually when someone changes their name.
