### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by krisbrox** [devilry/devilry-django#586]
Please consider adding a keyboard shortcut to preview feedback after entering text (e.g. <ctrl-Enter>). 
Additionally, a similar shortcut to publish feedback (from the preview screen) would be greatly appreciated (I would suggest <Enter>).

**Comment by torgeirl** [comment]
I seems we didn't move forward on adding keyboard shortcuts during Devilry 2.x, and since we are unlikely to do so now I'll go ahead and close this issue.
