### ISSUE TITLE
Distribution of groups to examiners

### ISSUE THREAD

**Issue by eigilhs** [devilry/devilry-django#590]
After using «setup examiners by tags», I usually end up with a very unbalanced workload for the different examiners. To remedy this, I manually move students around to make sure the groups are distributed evenly among the examiners. This assures that *most* students have their TA as examiner. Would it be possible to add a feature that does this for the course admin?

Additionally there are usually some students that prefer to know that they'll always be corrected by their TA, so I maintain a list of these so as not to move them when I move students around. This is not as important as the previous part, but it would be a nice addition if this was possible to implement in some way as well.

**Comment by espenak** [comment]
This is solved in 3.0 by letting you copy the examiner configuration from another assignment both when creating an assignment and at any time after that. So the typical new workflow would be:
- Setup the first assignment and organize examiners for that assignment.
- When creating assignment 2, copy the setup from assignment 1 (copy from the previous assignment is the default choice when creating a new assignment).
