### ISSUE TITLE
Bulk publish feedback

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#591]
We should make it possible to bulk publish feedback. This should be available to both examiners and admins.
## Implementation for examiners

Examiners simply needs to have a bulk action in their assignment overview where they can publish the last draft for all or some groups.
## Implementation for course admins

We have discussed this previously, and as far as I remember, we ended on the following suggested solution:

> A course admin can enable "bulk publish". This will change the publishing pipeline so that the user does not get access to an assignment when it is published by the examiner. They have to wait for a course admin to select "publish results" via the course admin UI.
## Input?

This was recently requested by Heine Nygard Riise. Heine, please let us know (via a comment here, or via email) if the solution above does not make sense to you. We are, as always, very happy if anyone else has any suggestions.

**Comment by torgeirl** [comment]
Bulk feedback is currently available.
