### ISSUE TITLE
Error in syntax highlighting over multiple lines in java.

### ISSUE THREAD

**Issue by larstvei** [devilry/devilry-django#592]
In the second code-block you can see that multiple lines of comments are interpreted as a single line comment.

![10578849_10154652121560484_1162312719_o](https://cloud.githubusercontent.com/assets/2478638/4457104/de26d032-4892-11e4-9b50-c3df0c524d82.jpg)

**Comment by torgeirl** [comment]
I believe this issue got handled in the UI overhaul included in Devilry 3.x (released January 2018), and if not we're currently in the process of replacing the editor included in Devilry 3.x (#1217) with the intention of also improving both code and math block notation.
