### ISSUE TITLE
Closing multiple groups without deliveries

### ISSUE THREAD

**Issue by krisbrox** [devilry/devilry-django#593]
Jeg er gruppelærer i et kurs hvor det på hver innlevering er mange grupper som ikke har levert flere innleveringer. Jeg kan velge "write feedback" på hver enkelt gruppe (det er en student i per gruppe), for så å velge "close group without feedback (they should have delivered, but did not do so)". 

Det hadde vært veldig praktisk å kunne gjøre dette med flere på en gang, men knappen "write feedback to selected" fungerer ikke når jeg har valgt flere grupper (jeg får feilmeldingen "Error: One or more of the selected groups has no deliveries.").

**Comment by torgeirl** [comment]
Dette har vært på plass i noen år, lukker issuet.
