### ISSUE TITLE
Preserving edited feedback after login redirect

### ISSUE THREAD

**Issue by eigilhs** [devilry/devilry-django#594]
I had the Edit feedback view open on a student after the login cookie had expired, then edited the feedback and pressed Preview. I was prompted to log in, and was returned to the Edit feedback view with all of the edited feedback gone. Would it be possible to preserve the edits after the redirect?

**Comment by torgeirl** [comment]
I believe this issue more or less was solved in 2018, when we adjusted the login time and adjusted the token time. Combined with how browsers currently preserve field data between page switches this should no longer be an issue.
