### ISSUE TITLE
Add search to the examiner assignment overview list.

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#607]
Should be a search much like the issue search on GitHub and Gmail, where you can search loosely accross all fields by just typing text, but be more specific with `<keyword>:<searchterm>` (E.g.: `tags:group1,group3`).

Needs to be able to search for:
- Tags
- Name, username, email of students.
- Name, username, email of examiners.

Should consider using https://github.com/alex/django-filter.

**Comment by torgeirl** [comment]
No longer relevant.
