### ISSUE TITLE
Add a detail mode to the examiner assignment overview (showing examiner, tags, ...)

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#610]
The detail should show all examiners, tags, and generally as much info as possible for each group. I think we should store this in a cookie, so if you go into “detail mode”, you stay there until you select “Simple mode”. I think the choices should be presented as “Show the essential information” and “Show detailed information”.

Do anyone have any specific request for information in detail mode (in addition to tags and examiners)?

**Comment by torgeirl** [comment]
No longer relevant.
