### ISSUE TITLE
More metadata about the delivery in the notification mails sent to students

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#611]
We should consider adding a bit more information about the delivery in the delivery receipt email and new feedback email.

The challenge with this is that the feedback text quite often contains information that the student needs read, and there is a real danger of missing that kind of information if the students see that their assignment is graded "Passed". Typical edge cases (these are all fairly common):
- Assignment is approved, but some parts of it needs to be fixed before the next assignment (typically if assignment 2 extends assignment 1).
- Assignment is barely approved (insert reason here), with a message that the next assignment needs to be much better.

**Comment by torgeirl** [comment]
The email notification templates were reworked in both 3.x (ie #1000) and 4.x, so this should more or less be solved by now.
