### ISSUE TITLE
PDF and plaintext annotation support

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#615]
We need to be able to annotate/comment in the sidebar for PDFs and plaintext (programming code, etc.) deliveries.
## How to do this for PDFs

For PDFs, we will convert the PDF to images and show them in the browser with clear page indicators. Comments will get a page number and an X,Y coordinate within the page. The coordinate will be the point where the examiner clicked/tapped to add the comment.

We should make the PDF to image conversion interchangable (global setting), and the default should use [Poppler](http://poppler.freedesktop.org/). Poppler is fast (converts a typical 100 page master assignment with figures in under a second), and easy to use.
## How to do this for plaintext formats

For plain text formats, we should syntax highlight the files, and store a reference to the line number and character number where the user tapped to add a comment. In the future we may extend this to allow users to select a block of text.

This will also solve #392 for most use-cases since we will get a full PDF view right in the browser.

**Comment by torgeirl** [comment]
No longer relevant.
