### ISSUE TITLE
More powerful approved previous semester

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#622]
The current approved previous semester/period solution just matches the `short_name` of assignments for all previous periods/semesters within the same course. This has two obvious weaknesses:
1. Most educational institutions have rules about how old an assignment can be and still be considered "valid/usable" if a student re-takes a course.
2. Many courses change their assignments, so they need to map have a way of saying something like:
   
   ```
   spring2010.oblig2 == spring2011.oblig3 == (spring2012.week2 and spring2012.week3)
   ```

**Comment by torgeirl** [comment]
No longer relevant.
