### ISSUE TITLE
Advanced plugin for "qualifies for final exams"

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#623]
We need an advanced plugin for "qualified for final exams" where admins can setup more complex rules.

Known use cases:
- A student needs X points in total for 3 assignments, and they need to get a passing grade on 2 other assignments.
- A student needs to complete one of 3 distinct sets of assignments, each one with their own requirements. This basically means that the rules must be recursive.

We need make a plugin where you can build logical queries just like you do in any programming language. We need `>`, `<`, `==`, `and`, `or`, and we need to be able to be recursive. Basically, something like this should be possible:

``` python
(week1.points+week2.points+week3.points > 10 and oblig1.is_passing_grade and oblig2.is_passing_grade)
or
(huge_project.is_passing_grade)
or
(small_project1.is_passing_grade and week1.points+week2.points+week3.points > 10)
```
## Complexity?

I think we can make a plugin like this fairly easily as long as we require the admins with these needs to read some docs and express their rules using some plain-text language in the first version.

**Comment by torgeirl** [comment]
No longer relevant.
