### ISSUE TITLE
The user import script resets tags and possibly examiners

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#642]
The user import scripts resets tags for all users. This makes period-level tagging unusable.

**Comment by espenak** [comment]
Should just have to change ``devilry/devilry_superadmin/management/commands/devilry_periodsetrelatedexaminers.py`` so that it merges instead of replacing tags.

**Comment by espenak** [comment]
The script might be resetting examiners too.

**Comment by espenak** [comment]
The problem with tags is no longer an issue i 3.0, but we still need to make sure it does not reset examiners (should deactivate them instead).

**Comment by torgeirl** [comment]
No longer relevant.
