### ISSUE TITLE
Remove the last_deadline cached attribute from AssignmentGroup

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#647]
Will require us to make a raw SQL query that does the same thing, and it will require us to update code in multiple places:
- Make sure we do not use `last_deadline` in the new student UI.
- The examiner UI at least uses this when creating new deadlines and when adding non-electronic deliveries (in `AssignmentGroup.add_nonelectronic_delivery`).
- We will have to update some of the REST APIs in the subject admin UI.

**Comment by espenak** [comment]
We will not prioritize this for v2.0 since setting the last deadline is fairly cheap in terms of performance.

**Comment by torgeirl** [comment]
No longer relevant.
