### ISSUE TITLE
Setting 20 examiners on 700 students takes hours

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#678]
This is a fairly extreme case (creating 700*20 examiners), but I think we should be able do that in very short time. Should be optimized as a bulk_create query and that should make it run fairly quickly. Note that this may also be something in the UI/API communication.

**Comment by espenak** [comment]
This is very strange. I just added 3 examiners to 2000 students locally, and it took less than 30 sec. The API does this very inefficienty (running 2000x3 inserts), and that should mean that 700*20 should take a bit more than twice this time. This means that it could be one of the following:

1. Postgres is vastly less efficient at inserts than SQLite. The opposite is my experience, but I will have to test this will local postgres to be sure.
2. The Postgres server is very slow or overworked.
3. The communication between the Devilry django server and the postgres server is very slow.

**Comment by espenak** [comment]
A possible solution to this problem is to make this the first step towards a new student-management UI (#680). We can release a fully working but limited beta version that handles the most common and most performance intensive tasks.

**Comment by torgeirl** [comment]
No longer relevant.
