### ISSUE TITLE
New students on assignment view

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#680]
The students (groups) on an assignment view should be replaced with one or views that is:
- More powerful. It should support better filtering/searching, group by examiner, group by deadline.
- Much faster. Should be able to handle assignments with thousands of students and tens of examiners. All operations should be fairly instant if that is possible. We may want to use some form of eventual consistency to achieve this.
- More intuitive. The selection model is a bit untraditional, especially when coupled with searching. Ideally we want users to be able to filter and search what they see in the list, select what they need, and have the selection be persistent when they change the search/filters.
- Easier for complete beginners. We may want to consider a easy and advanced mode.

**Comment by torgeirl** [comment]
No longer relevant.
