### ISSUE TITLE
Find a better name for node admins?

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#686]
I think we should find a better name for node administrators. Node administrators are admins on something in the node-hierarchy above the courses. The node-hiearchy can be used to emulate almost any structure, but I think we can choose something a bit less vague and generic than node-administrator. Typical real world names for node admins are:

- Faculty administrator.
- Institute administrator.
- School administrator.

But we can not choose any of those since none of them fits as a generic term.

Note that _superuser_ is already taken.

One idea is *Toplevel admin*.

Another idea is to rename course administrator to _course manager_, and simply call a node admin an _administrator_.

**Comment by apparator** [comment]
I think "Another idea is to rename course administrator to course manager, and simply call a node admin an administrator." is a great idea!

**Comment by espenak** [comment]
After discussing this with @apprator and @tworide, we all agree that _Course manager_ and _Administrator_ is better names than _Course administrator_ and _Node administrator_. This will be changed as part of #676.
