### ISSUE TITLE
Consider if we want to re-introduce the HelpLink system

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#688]
We have a HelpLink model in the devilry_helplink app. It works by letting users setup links to help guides based on the role of the user. I wonder if this is the best way to handle this. We have seen that sysadmins usually already have some help system in place.

I think we may be better of with a help-link setting for each of the roles, and show that on the frontpage for each role:
- We already have a system in place that can handle this with translations and all (https://github.com/devilry/devilry-django/blob/master/devilry/django_decoupled_docs/README.rst).
- The help should be more like the help for examiners - It should ask a question that makes sense for the user in the context they are in. So when they create a new assignment, they should be presented with guides for that use-case.

**Comment by torgeirl** [comment]
No longer relevant.
