### ISSUE TITLE
User frienly name for Period?

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#690]
With the old term-system we translated Period into Semester in the higher education dialect. What should we call it now that we have to choose a single name? Some suggestions:

- Timeperiod (this is what it actually is - a timespan where you group assignments).
- Semester (this is what it usually is in higher education)

Any ideas or thoughts on this?

**Comment by apparator** [comment]
Not just "Term"?

> An academic term (or simply "term") is a portion of an academic year, the time during which an educational institution holds classes.

http://en.wikipedia.org/wiki/Academic_term

**Comment by espenak** [comment]
"Term" should work nicely!

**Comment by espenak** [comment]
We will go for "Term". This will be included in #676.
