### ISSUE TITLE
Send notification when a new deadline is created

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#695]
A new deadline is usually created for the following two reasons:
- A student is added to an assignment.
- A student received a failing grade on an assignment and has been given another chance.

In both cases, the notification should not be sent right away. The first case often happens when an assignment is created, and admins often adjust stuff like deadlines right after they create an assignment.

The second case should ideally be notfied alongside the failing feedback, but that may be difficult since an examiner may add failing feedback for many students and then go back and decide who should be given a seconds chance.

**Comment by torgeirl** [comment]
No longer relevant.
