### ISSUE TITLE
Changes does not appear until reloaded; "Qualified for final exams", "Students must pass ALL assignments"

### ISSUE THREAD

**Issue by toneapp** [devilry/devilry-django#713]
This issue is for a "Course manager".
In a selected course, when you choose "Qualified for final exams" and "Students must pass ALL assignments" the list of students appear, but when pressing "Save" nothing happens.
But if you leave that site (press one of the earlier "pages" in the line "Course manager/All my courses/duck1100.springcur/Qualified for final exams") and go into that site again, the change has happened - and you can print out the list and so on.
BUT if you then choose "Change status" to "Retract - .bla..bla.", write something the appearing window and press "OK", nothing happens (again!)
And it's the save as before, if you go out and in again, the change has happened!

**Comment by torgeirl** [comment]
No longer relevant.
