### ISSUE TITLE
Changes does not appear, when reloaded an ERRORmessage; "Qualified for final exams", "Students must get a minimum number of points"

### ISSUE THREAD

**Issue by toneapp** [devilry/devilry-django#715]
This issue is for a "Course manager".
In a selected course, when you choose "Qualified for final exams" and "Students must get a minimum number of points", you get to choose a number of points, and the list of students appear, and when you press "Save" nothing happens. But if you leave that site (press one of the earlier "pages" in the line "Course manager/All my courses/duck1100.springcur/Qualified for final exams") and go into that site again, you get a red messagebox that says:
"The server responded with error message 500: INTERNAL SERVER ERROR when we made a GET-request to URL /devilry_qualifiesforexam/rest/status/18?_dc=1423847338052."

**Comment by torgeirl** [comment]
No longer relevant.
