### ISSUE TITLE
Changes does not appear, when reloaded a TypeError-site; "Qualified for final exams", "Select manually" 

### ISSUE THREAD

**Issue by toneapp** [devilry/devilry-django#716]
This issue is for a "Course manager".
In a selected course, when you choose "Qualified for final exams" and "Select manually" the list of students appear, and you can choose students. But if you select "Next", a site with this on the top appears:
"TypeError at /devilry_qualifiesforexam_select/select
set([128, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]) is not JSON serializable"

**Comment by torgeirl** [comment]
No longer relevant.
