### ISSUE TITLE
Examiner, select multiple students, "Write feedback", one or more has not delivered anything - ERROR and no "back"-button

### ISSUE THREAD

**Issue by toneapp** [devilry/devilry-django#717]
This issue is for examiners.
If you're correcting assignments, choose multiple students at once, select "Write feedback", and one or more of the selected students has not delivered anything, you get an ERROR.
But there is no "back"/"return" button, and your only choise is to press the blue "Examiner"-box that takes you to the "Start"-page, and you must go back again.

**Comment by torgeirl** [comment]
No longer relevant.
