### ISSUE TITLE
Track merging and splitting of groups and make it possible to split wrongly merged groups

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#719]
It would be convenient if a superuser could undo a merge of groups. This will require some kind of history about the groups to work for all use cases.

In most cases it would be enough to simply put all the students on the group in individual groups, and move deliveries to the student that made the delivery.

**Comment by espenak** [comment]
We should create a model with:
- a ForeignKey to the AssignmentGroup that the groups was merged into
- a JSONB field that describes the merge
- a datetime for the merge

**Comment by torgeirl** [comment]
Groups can be split so I assume this was solved in some other fashion down the way.
