### ISSUE TITLE
Update (old and inconsistent) management-commands

### ISSUE THREAD

**Issue by vegarang** [devilry/devilry-django#733]
These docs: https://devilry.readthedocs.org/en/latest/sysadmin/managementcommands.html
need to be updated. Managements commands should be updated to reflect how they work today, example here:
https://devilry.readthedocs.org/en/latest/sysadmin/gettingstarted.html#if-you-do-not-have-an-existing-database-add-some-data

**Comment by torgeirl** [comment]
No longer relevant.
