### ISSUE TITLE
Føles ut som om hjelpemidler for eldre har blitt skrudd på

### ISSUE THREAD

**Issue by ehatle** [devilry/devilry-django#734]
Værsåsnill og senk størrelsen på fontene deres igjen. Føles mye mindre oversiktilig når jeg bare kan se 60% av det jeg kunne tidligere på skjermen.
# student #examiner #courseAdmin

**Comment by espenak** [comment]
Hvilket UI opplever du dette i? Student, retter, eller kursadmin? I hvilket view? Hvordan skjermoppløsning og DPI bruker du? Ta gjerne et skjermbilde og send det inn her.

I våre tester på et relativt bredt utvalg av ulike skjermer og devices fungerer fontstørrelsen vi har nå bra. Årsaker bak valget av fontstørrelse:

- Optimalisert for HD+ oppløsning slik man har på de fleste nye laptops telefoner og tablets. Altså vil fonten bli noe stor hvis man har stor skjerm med dårlig oppløsning (f.eks. 26" med 1080p).
- Optimalisert for at alters-spennet på målgruppen er veldig stor, og dermed en ganske stor andel med bittelitt synsvansker.
- Optimalisert for å være en default som de aller fleste kan bruke uten å behøve å forstørre teksten manuelt.

Jeg mener ikke at vi ikke kan justere dette altså, men vil bare gjøre det tydelig at dette ikke er et tilfeldig valg, og at vi derfor ikke bare kan endre dette uten videre gjennomtanke og god grunn.

**Comment by ehatle** [comment]
Det gjør jeg egentlig på alle. Dette er vel egentlig mer en klage enn en faktisk bug. Problemet mitt er at på sider med mye informajson blir det rett og slett lite lesbart da skriften er for stor. Et eksempel på dette er ved oversikten over studenter som er registrert på en oblig.

 Jeg har en macbook pro (early 2011) som har en oppløsning på 1440x900. 
![screen shot 2015-03-24 at 17 41 16](https://cloud.githubusercontent.com/assets/3341171/6807183/3f7513fa-d24d-11e4-9f58-da7b966638ff.png).

**Comment by torgeirl** [comment]
UI-et har endret seg veldig mye siden våren 2015 så dette er ikke relevant lenger.
