### ISSUE TITLE
Time stamp for delivery deadline missing.

### ISSUE THREAD

**Issue by hvaara** [devilry/devilry-django#735]
As a student it is impossible to see exact deadline for delivery. The estimate is off by ± 15 minutes. Please bring back the ISO 8601 format. At least make it an optional setting. Some assignment texts does not include deadline for delivery which makes it impossible to know the exact deadline.

**Comment by blt950** [comment]
+1 This needs to be added back

**Comment by espenak** [comment]
Fixed (see #754).
