### ISSUE TITLE
Feedback for ny UI

### ISSUE THREAD

**Issue by blt950** [devilry/devilry-django#736]
Den nye UIen har blitt mer "moderne", men tyngre å bruke, i form av antall klikk og oversikt.

Bakgrunn: Student og bare studentrettigheter.
### Oversikt

Her burde man endre bredden på en levering til mindre enn 90% av hele skjermen. På store skjermer (2560x1440) tar dette alt for mye plass og man må bevege hode bare for å få med navn, kurs, og leveringstid. Dette burde ha mye mindre bredde, litt mindre skrift skader ikke, og ikke minst: nøyaktig tid for leveranse slik #735 påpeker.

Oversikten burde være mer enn en oversikt av bare leveransene, jeg likte veldig godt å se en liten oversikt over tidligere leveranser og resultat.
### Leveranse/Delivery

Her burde en nøyaktig tidsfrist være skrevet også. Det er nå mulig å laste opp flere filer på en gang- hurra! Det har jeg savnet mye. Selve "lever" knappen er merkelig plassert nede med en firkant svart avrundet firkant som er mye større enn knappen selv, virker som det skulle være flere knapper der, men det er ikke tilfelle.

![screenshot 2015-03-27 14 48 54](https://cloud.githubusercontent.com/assets/2505044/6868990/8cdc495c-d490-11e4-99c6-0189b6012108.png)

"Upload as many files as you like." er også litt merkelig på leveringer, den tar jo kjempemye plass! Men det er bare en statisk tekst som ikke forandrer seg eller bruker arealet/boksen den er inn i på noen måte - som jeg har erfart i hvert fall.

Vi har en del gruppeoppgaver, før stod det fint hvem er det som jobber på oppgaven, og hvem som retter den. Nå må jeg faktisk klikke på "Contact Examiners" for å finne ut av dette, og her står ikke hvem jeg jobber på gruppe med..?

Jeg må også klikke på "Deliveries" for å finne ut om det ligger en leveranse inne fra før eller ikke. Dette gjelder oversikten også, her må jeg klikke på Oppgaven > På "Deliveries" (som er i bold og virker som det er jeg er nå, men det er jeg jo ikke) > Og her ser jeg faktisk om jeg har levert eller ikke. Forrige versjon så jeg antall leveringer på oversikten, få dette tilbake også.

Nå skal jeg tilbake til oversikt. Hvor skal jeg klikke? "Overview" høres mest logisk ut, nei vent, det er oversikt over leveringen. Navnet på kurset jeg tar, tja kanskje det får meg et steg nermere - nei det gir meg oversikt over kurset, logisk nok. "Student" da helt oppe - Uff da, kom jeg på hjem skjermen igjen, og må klikke at jeg er Student, der var oversikten jeg hadde lyst på ja!
### Oppsummering

Oppsumert så er det fint meg moderne UI og alt dette, men det har blitt mye mer tungvint å gjøre enkle ting som å bare sjekke antall leveringer og siste status uten å klikke inn på alt mulig. Noen menyer har ulogiske navn eller leder deg til et sted som ikke var helt hvor du tenkte deg. På store skjermer føles det ut man har strukket i alt for å bruke mest mulig av skjermen, men det resulterer i at ting tar veldig mye plass.

Designmessig fin oppdatering, men lite gjennomtenkt. Foretrekker forrige UI mye mer, mer intuitive og raskere å bruke. Denne UIen burde ha blitt testet bedre.

**Comment by tworide** [comment]
Hjertelig takk for detaljert tilbakemelding. Dette skal vi ta en skikkelig gjennomgang av

**Comment by espenak** [comment]
Slenger meg på @tworide og takker for veldig gode tilbakemeldinger. Noen innspill:

- Navigasjons-strukturen bør vi gjøre noe med, og du oppsummerer veldig godt hvor det ikke henger helt bra sammen. Dette skal vi få ryddet opp i.
- Samme gjelder ordbruk. Ser f.eks at "Overview" er uheldig. Bør nok heller stå _About the assignment_, og vi bør nok koste på oss litt mer informasjon på den siden.
- Dette med bruk av plassen som er tilgjengelig på store skjermer er en interressant utfordring når vi skal få ting til å fungere bra på alt fra smart-telefoner til 2560x1440. Vi har ikke optimalisert for så god oppløsning med nettleseren i fullskjerm. Vi bør nok gjøre noen visuelle justeringer slik som å gjøre menyen bredere og skjemaet noe bredere, men vi kan ikke strekke komponenter med mye tekst til full bredde ettersom tekst leses best i spalter på opp mot ca. 800px. Det betyr at vi uansett vil ende opp med tomrom enten i en ende eller på begge sider av UIet. Vi kan muligens etterhvert bruke det tomrommet til å vise flere detaljer om innleveringen, eller annen ikke-kritisk informasjon, men jeg ser for meg at det koster litt mye å vedlikeholde noe slikt for de få brukerne som sitter på HD+ oppløsning med nettleseren i full skjermbredde.
- "Upload as many files as you like." er hjelptekst til leveringsboksen. Den tar såpass mye plass ettersom vi ikke har optimalisert for 2560x1440.
- Den litt rare boksen rundt "Add delivery" skal vi fjerne, og knappen vil nok heller bli en godt synlig knapp rett under boksen for å laste opp filer. Vi bruker et underliggende system der dette er standard stil, og vi har ikke fått laget en stil for sider der dette ikke passer (altså når man har såpass små skjema og bare en knapp).
- Årsaken til at ikke all informasjonen om en oppgave ikke lenger er samlet i en side er at brukertester og tilbakemeldinger viser at dette er overveldende - spesielt for nye brukere. Det er også veldig vanskelig å utvide et slikt design med ekstra informasjon og spesial-funksjonalitet som kun brukes i noen tilfeller (f.eks. gruppesamarbeid). Derfor har vi gått mot en struktur der informasjonen for hver oppgave er delt inn i flere sider, der hver side aller helst kun gjør en ting. Altså har vi sidene: Oversikt, Innleveringer, Kontakt retter + andre sider som kun brukes i noen tilfeller slik som "Prosjektgruppe". Jeg vil tro du får en bedre opplevelse av dette når punkene ovenfor er ryddet opp.
- Årsaken til at du ikke ser noe info om de du jobber sammen med i prosjektgrupper er dessverre en bug. Se #737 for bilde av hvordan det skal se ut når feilen blir fikset.

Dette UIet har blitt testet på et godt utvalg av testere i ulike aldersgrupper og med ulike mengder av erfaring med Devilry fra tidlgere. Noen av de tingene du påpeker, slik som optimalisering for veldig høy oppløsning og styling av "Add delivery" knappen, kom opp under testingen, men ble ikke vurdert som kritiske nok til at de ikke kunne fikses i en senere oppdatering. En del ting er vanskelig å oppdage før man får brukt systemet i daglige gjøremål, og en del ting går på smak, behag og prioriteringer. Ingen av testerne reagerte på navigansstrukturen, men nå som du har gjort oss oppmerksomme noen svakheter ved den skal det være en smal sak å rydde opp:-)

**Comment by blt950** [comment]
Takk for svar på det uansett. Det er vel bare min mening på hvordan det ser ut som.
Slik du forteller det, så virker det som det blir bedre etter neste oppdatering når dere får fikset det meste. 

Nå synes jeg det er bedre med litt mer informasjon på en side enn det er nå, det blir så mange klikk bare for å finne ut noe enkelt som rettere, gruppemedlemmer, leveranser osv. Selv om kanskje deres tester viser det motsatte, kunne kanskje vært en instilling å få mer detaljert informasjon på en side hvis man ønsket det, det hadde vært flott.

**Comment by espenak** [comment]
Dette skal vi nok klare å finne et godt komprimiss på tror jeg. Må tenke litt på dette, men jeg vil tro at vi kan legge til litt ekstra oppsummerende info her og der, og få den effekten du er ute etter. Min første tanke er en av følgende:

1. Vis en rast oppsummering av oppgaven på "legg til innlevering" siden. F.eks.: "Innleveringsfrist 25 mai 2015 23:59. Gruppemedlemmer: Peter Parker, Clark Kent. Retter: Mr Miyagi. 3 innleveringer.", der hver av disse korte setningene er en link videre til detaljsiden for akkurat den informasjonen. Denne oppsummeringen kan også vises på oversiktsiden for oppgaven.
2. Gjør "menyen" bredere, og legg til setningene fra punkt (1) i menyen. Da får vi f.eks. noe slikt:

    > About the assignment
    > Deadline 25/5 2015 23:59, Waiting for deliveries
    >
    > Deliveries (3)
    >
    > Rettere
    > Mr Miyagi, Clark Ken ...
    
Noen som har noen tanker om dette eller andre idéer?

**Comment by blt950** [comment]
Det høres bra ut, da får man i hvert fall informasjonen og blir sendt videre hvis du ønsker mer utdypning.
Burde kanskje stå "Deliveries: 3" istedenfor (3).

**Comment by torgeirl** [comment]
Lukker dette issuet da dette har blitt tatt med i utviklingen av Devilry 3.x som kom i junuar 2018.
