### ISSUE TITLE
Projectgroup page is not visible unless admins have enabled "Students can form project groups"

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#737]
This view must be available if there are more than one student in a group. We should simply disable all invite features unless admins has enabled that.

**Comment by espenak** [comment]
![add delivery](https://cloud.githubusercontent.com/assets/84501/6870013/8c3e6bf2-d499-11e4-8da1-177a1a60de32.png)

**Comment by espenak** [comment]
![project group](https://cloud.githubusercontent.com/assets/84501/6870055/c4840b34-d499-11e4-80b7-2e470d573db4.png)

**Comment by Christopherruud** [comment]
Me too. there are several issues when preset groups cannot monitor their own members for slackers or dropouts.

**Comment by torgeirl** [comment]
No longer relevant.
