### ISSUE TITLE
"Duplicate headers received from server" on delivery download

### ISSUE THREAD

**Issue by andeplane** [devilry/devilry-django#738]
Devilry username: anderhaf
Course: FYS2140
Mandatory assignment: Oblig 5
OS: Mac OSX 10.9.5
Browser: Chrome 41.0.2272.104 (64-bit)
Workaround: Yes, see bottom.

<b>Reproduction steps:</b>
Trying to download delivery with id 145696:
https://devilry.ifi.uio.no/devilry_examiner/singledelivery/145696
which gives download link:
https://devilry.ifi.uio.no/devilry_student/show-delivery/filedownload/215645
which in turn gives error
Error code: ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

<b>Workaround</b>
One can use Download all deliveries button to download the delivery.

**Comment by andeplane** [comment]
Additional info:
This also happens with another delivery (oblig 6) from the same student:
https://devilry.ifi.uio.no/devilry_student/show-delivery/filedownload/222880
but not all students. 

Possible reason can be the way the PDF is generated?

**Comment by espenak** [comment]
We have looked into this, and we think this has something to with Apache web server settings and streaming of large files. We have not been able to reproduce this in the test environment, so we will continue debugging this tomorrow.

**Comment by Christopherruud** [comment]
I have had this happen, particularly with deliveries that contain non-ascii characters and long titles.

**Comment by torgeirl** [comment]
> We have looked into this, and we think this has something to with Apache web server settings and streaming of large files.

Unsure when and how this was solved, but either way this is no longer an issue.
