### ISSUE TITLE
Möjlighet att välja bort kvittering

### ISSUE THREAD

**Issue by rungitta** [devilry/devilry-django#740]
Jag hittar inte inställningen där jag kan välja att slippa få kvittering från devilry. Finns det en sådan inställning? Om hade det varit fint om det kunde ordnas.

**Comment by tworide** [comment]
Hei.

Vi har ikke lagt til noen mulighet for å fjerne epost-kvitteringer fra Devilry. Det er ønskelig fra studieledelsen at en slik kvittering skal nå studentene for å være sikre på at innlevering er levert og mottatt. Det er ditt bevis på at alt er i orden dersom det skulle oppstå misforståelse i etterkant. 

All epost fra Devilry sendes til UiO-mail kontoen din og du kan enkelt lage filtre for å sortere ut den posten du ønsker. 

Mer informasjon finner du her.
http://www.uio.no/tjenester/it/e-post-kalender/epost-kalender/filtrere-e-post.html
