### ISSUE TITLE
Edit mode: Quick missing passed/failed dropdown

### ISSUE THREAD

**Issue by andeplane** [devilry/devilry-django#741]
Seems like the passed/failed dropdown (<select> tag) is gone in "Edit mode: Quick".

**Comment by tworide** [comment]
Do you experience this in general or on a spesific assignment?

Please provide some additional information to help us solve the issue.

**Comment by andeplane** [comment]
I'm sorry, for assignments that have deliveries, the dropdown is there. My bad.

I'll change this to a feature request:
In FYS2140 most of our students deliver non-electronic versions, so it would be nice to be able to choose passed/failed without having to add a non-electronic delivery for each student.

So suggestion: the passed/failed dropdown menu could be there also for students without any delivery, and if I choose passed/failed, a non-electronic delivery will automatically be added.

**Comment by torgeirl** [comment]
This issue predates the release of Devilry 3.x, which included a major UI overhaul.
