### ISSUE TITLE
Added examiners disappear between obligs

### ISSUE THREAD

**Issue by anakkerud** [devilry/devilry-django#742]
I've had this problem before, and thought I had submitted an issue before, but could not find it.

I added Agnar Skinlo as examiner for INF2080, spring 2015. I could then set him as examiner for all students. I don't know when he disappeared from the list of available examiners, but by the time I wanted to select examiners for Oblig 2 (I selected "Do not set examiners at this time" when creating the oblig), he was gone. I readded him, and set him as examiner. I had to repeat for Oblig 3, as he had again disappeared from the list. He never lost examiner status for existing obligs. I always chose to set examiners later, because I often set examiners only for students with deliveries.

**Comment by tworide** [comment]
This seems strange. I created oblig4 on your course now with ("Do not set examiners") when I went to the student listing to se examiner Agnar Skinlo was available as a choice.

The available examiners are defined on the subject level. Please notify us if you experience this again, we have not received other complaints about this.

I have deleted oblig4.

**Comment by anakkerud** [comment]
He is gone again. Tried to add examiners for Oblig 3 and Agnar is not there.

**Comment by tworide** [comment]
Ok. We will look deeper into this problem. Very strange. I added Agnar Skinlo manually to the list of available examiners now, hope you will ble able to assign him to students. 

Sorry for the inconvenience but we have never experienced this before. 

We will report back as soon as we have looked into this.

**Comment by anakkerud** [comment]
He is not there now, so he has disappeared again over the weekend. I'll add him myself and assign students.

**Comment by torgeirl** [comment]
This issue was probably solved before or with the release of Devilry 3.x in January 2018, and is no longer an issue.
