### ISSUE TITLE
Creating new deadline for selection from student list as Course Manager

### ISSUE THREAD

**Issue by anakkerud** [devilry/devilry-django#743]
As a Course Manager, I often need to set a new deadline for a selection of students. Sometimes, I can generate this selection in the Student-list within the relevant oblig. I would very much like the ability to create new deadlines from within the student list of each oblig (as seen by the Course Manager).

It would be very useful to select Has Deliveries, and then remove Feedback -> Passed, and apply a new deadline to all those who has a failed delivery.

**Comment by tworide** [comment]
I agree. It would be a good workflow to bulk create new deadlines for a selected group of students.

I will put this on our Devilry 2.1.0 milestone which will be released before next semester

**Comment by espenak** [comment]
Should most likely be part of #749.

**Comment by torgeirl** [comment]
This issue predates the release of Devilry 3.x, which included a major UI overhaul.
