### ISSUE TITLE
Narrowing student selection for Course Manager

### ISSUE THREAD

**Issue by anakkerud** [devilry/devilry-django#744]
In the student lists for obligs, it would be very useful to narrow an existing selection by intersection, not just difference. If I want every student failed by a certain examiner, it is useful not to have to remove all the others one by one. There are also more complicated intersections that could be very useful.

Basically, I want the filter option "Narrow selection", beside "Add to ..." and "Replace ...".

**Comment by espenak** [comment]
Sounds like a good idea to me. Should most likely be part of #749.

**Comment by torgeirl** [comment]
This issue predates the release of Devilry 3.x, which included a major UI overhaul.
