### ISSUE TITLE
The option for the course-representative (owner) to upload the task file

### ISSUE THREAD

**Issue by T1Lervik** [devilry/devilry-django#745]
What I mean : Option for course-owner when creating a new hand-in to add the task file.
Then allowing students to download the task file directly from devilry.

Currently : I have to go to course homepage to find the taskfile instead of finding the task directly in devilry

**Comment by espenak** [comment]
This has been considered multiple times, and so far the answer has always been that this can easily end with something that other systems solve much better (Content Management Systems). With that said, I think we should consider a very simple solution for adding the task file to Devilry:

I think we should allow admins to define a single flat page describing the assignment. On this page should be written just like a feedback text is written today (and just like an issue is added here on GitHub):
- An optional Markdown formatted text supporting LaTeX math and code highlighting.
- An optional attachment (typically a pdf).

This should be fairly easy to add to the admin pages, but I do not know exactly where we should add it on the student pages. It needs to be fairly visible without taking the focus away from adding deliveries.

**Comment by espenak** [comment]
- We should use the PDF previewer that we are developing for #615.
- When we get a comment system in place, students, examiners and admins should probably be able to comment on the task-text. Some info about the planned comment system in #97.

**Comment by torgeirl** [comment]
> This has been considered multiple times, and so far the answer has always been that this can easily end with something that other systems solve much better (Content Management Systems). 

It is still considered best-practice to organize task files along with the curriculum on the course page, and not in the delivery system itself.
