### ISSUE TITLE
Innleveringsfrister

### ISSUE THREAD

**Issue by kjesvale** [devilry/devilry-django#746]
Hei! Jeg savner å kunne se nøyaktig tidspunkt for innleveringsfrister i den nyeste versjonen av Devilry. 

Hilsen Kjetil

**Comment by sjurtf** [comment]
Det er blitt fjernet fra undersider, og kan nå kun ses på forsiden.
Enig i at dette også burde komme frem på sidene til individuelle kurs, og individuelle oppgaver.

**Comment by tworide** [comment]
Det er vi enige i. Vi skal få ut en fix på dette så fort det lar seg gjøre, og vi må beklage at det har tatt tid.
