### ISSUE TITLE
leverering från kommandolinjen

### ISSUE THREAD

**Issue by rungitta** [devilry/devilry-django#747]
Kan ni göra det möjligt att leverera från kommandolinjen som student i tillägg till att leverera i browser?

**Comment by espenak** [comment]
Dette har vi hatt i planene lenge, men vi har ikke fått tid til å prioritere det. Det første som må gjøres er å lage et skikkelig API for studenter, deretter bør en kommandolinjeklient være ganske enkelt å fikse.

Ting som allerede har blitt diskutert relatert til dette:
- #130
- #339 
- @tworide og jeg har gjort en enkel evaluering av http://www.pyinvoke.org/, og vi tror det kan være lurt å basere kommandolinjeklienten på PyInvoke.

**Comment by olejorgenb** [comment]
Could the wiki page https://github.com/devilry/devilry-django/wiki/Commandline-client please be removed if I understand correctly that that project is totally abandoned and might not even work (never got that far as it seems to need python2.6?)

**Comment by torgeirl** [comment]
Vi har dessverre ikke lenger planer om å lage en terminalklient.
