### ISSUE TITLE
Split the current "do anything with students on the assignment" view into multiple more focused views

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#749]
We currently have one page where you can organize all the students on an assignment. This works OK, but it ha a couple of problems:
- All new features need to be forced into the same workflow. This works great for some things, and not so good for others.
- It is slow with 250+ students because we need to load data for any task instead of the data needed for a specific task. For most tasks we could have used paging, but we have some use cases where this is not possible, so we are left slowing down all tasks.
- Some tasks, such as assigning students to examiners, could be much more user friendly with a more focused UI.

We should keep the current view for now, but slowly add new views. These new views should be designed to solve one task, and solve it as efficiently (from the users perspective) as possible.

**Comment by torgeirl** [comment]
No longer relevant.
