### ISSUE TITLE
Grading-schema plugin for v2 of the gradingsystem plugin architecture

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#751]
**I think we may already have an issue for this, but I can not find it.**

We need a grading schema (think google forms light) plugin for #465. This must be ready for fall 2015. We need:
- Good structure - we need to be able to fetch statistics out the dataset, and we need to be able to show "diffs" for cooperative grading (#509).
- Sections, and perhaps subsections. Could be flat like HTML (just different font-sizes, not real logical sectioning).
- Different data types for input:
  - Checkboxes (boolean)
  - Number input (int)
  - Select from a list (int)
## Add the schema data to StaticFeedback?

I think we should consider adding a JSON or JSONB field to StaticFeedback, and standardize the schema format. Then we can have one, or perhaps multiple grading system plugins that can edit the schema format. Remember that JSON and JSONB fields can be queried via the database query language, but it will make devilry depend on PostgreSQL. This is not really a big issue, and the alternatives (such as using MongoDB for the JSON data) has the same problems.

One advantage of this approach is that StaticFeedback will have the full history of this fairly important information instead of just a HTML rendering of the result. Adding this to StaticFeedback means that the JSON data should contain a version number to ensure we can maintain compatibility as the format grows and changes.

**Comment by torgeirl** [comment]
No longer relevant.
