### ISSUE TITLE
Show number of allready delivered on student group overview page

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#755]
If I have delivered something on an assignment allready, I would like a text that tells me the number of deliveries I have made. 

The first time I opened this page after having delivered, I thought the delivery had failed.

Example of text change, from:
"This assignment is open for deliveries. Add delivery."
to:
"This assignment is open for deliveries. You have added N. Add another delivery."

**Comment by apparator** [comment]
Or, maybe even better. List current deliveries below.

**Comment by torgeirl** [comment]
No longer relevant.
