### ISSUE TITLE
When doing exam evaluation, i need to be able to store a "feedback text" for examiners only

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#756]
When evaluating exams, I need to be able to write notes that are not sent to the student. 

These notes should be available to all examiners (maybe to course admin too). 

"Show feedback to examiners only" could be a setting on the assignement maybe?

**Comment by espenak** [comment]
This is at least somewhat related to these issues:
- #509
- #591
I think we need to adjust some things in the core to make all of these desired features easy to implement and use.

**Comment by espenak** [comment]
The needs of @apparator with this issue will be fixed by #765 and #764, and the broader issue of taking notes should be solved by the comment system (#97).

**Comment by torgeirl** [comment]
No longer relevant.
