### ISSUE TITLE
A more scalable and portable method of handling "download all files"

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#757]
We currently create a zip file on demand via the local file system. This does not scale well:
1. It requires a physical file system or (potentially) a huge amount of memory.
2. It makes it hard to know the amount of resources required to handle a given load because many people downloading a zip can lead to worker thread starvation. This is what is delaying #739 from beeing implemented.

I think this should be handled in a background task and cached. Ideally, it should work like this:
- If no zipfile file exists, create one in a background task (Celery). Try to wait for celery to complete creating the zip file, but fall back on telling the user that they will get a notification (email) when the zip has been created.
- If a zipfile exists in the cache, simply send it to the user directly.
- The zip-backend should be configurable. This means that it should be easy to use any zip implementation, including a cloud based one.
## Is this a general purpose requirement?

I guess this is a set of features required by any set of files needing to be converted to another format, such as PDF/Word to images for preview. Perhaps we should generalize this caching workflow?

**Comment by torgeirl** [comment]
No longer relevant.
