### ISSUE TITLE
Move examiner UI to django-cradmin

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#758]
This should be fairly straight forward, for each view:
- Inherit from Django cradmin view classes instead of the Django view classes. Remember that the cradmin view classes are just subclasses of the ones we already use from Django, so this is a small change that usually just removes boilerplate code.
- Inherit from django-cradmin templates. Will mostly just mean moving template code around a bit (rename blocks and move some things not in blocks into blocks).
- Run the tests, and se what breaks.

The only view that require a bit more work is the one where we show an overview of an entire assignment. This will need a rewrite into a cradmin instance with one app for each item in the sidebar. This change will just make the code clearer, and give us access to all the features of ObjectTableView in cradmin.

**Comment by torgeirl** [comment]
No longer relevant.
