### ISSUE TITLE
Make a general purpose abstract view for bulk import of users from a comma separated list

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#760]
Should support a list of emails, usernames or names. Should disable username support if the auth backend uses emails (we have a django setting from django-cradmin for this). Should provide a workflow like this:
1. Show a texarea where users paste/type emails, usernames or full names separated by comma or newline.
2. Show a preview, and ask for any missing nformation (if we only get a full name, and that name matches multiple users, or the user does not exist, highlight the row in the preview table in warning color, and provide an input field (in the column of the table where the missing data belongs).
3. On the third page, it should be easy to extend the POST method. The view for the third page should provide a post method that creates the required users, but that method should also call empty "post_create_users()" and "pre_create_users()" methods where views like bulk add users to an assignment can insert their code.

@vegarang ha already created an API and a superuser view as a starting point for this workflow.

**Comment by torgeirl** [comment]
No longer relevant.
