### ISSUE TITLE
Create an examiner workflow where multiple examiners can cooperatively create a single feedback

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#764]
This workflow assumes trust and coordination between the examiners. They share the same feedback drafts, and the last draft for the group is used (unlike the default where each examiner has their own private drafts).

This workflow makes it impossible for an examiner to publish their feedback, they can only save drafts. When the course admin is notified by the examiners that they are finished, the admin must go into the admin UI for the assignment and click a button to publish all feedback drafts.

**Comment by espenak** [comment]
Requires #591.

**Comment by torgeirl** [comment]
No longer relevant.
