### ISSUE TITLE
Use ElasticSearch as a document cache

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#769]
We have discussed using a nosql database as a read-cache for Devilry several times, but the ones we have checked out (MongoDB, CouchDB) have been to slow at queries. ElasticSearch is a nosql document store with really strong search, filtering and aggregation support. We would most likely speed up all of our listings if we used ElasticSearch instead of database queries. The reason for the speedup is fairly simple:
- We store everything needed for the listings in the document store (ElasticSearch). This means that we do not need any joins or subqueries. This is a really important because we have some truly horribly heavy queries for things like:
  
  > Get me all AssignmentGroups where a given user is Examiner. Add information about the latest deadline, the lastest delivery, the latest feedback, the latest feedback draft, number of deliveries, ...
  
  This is hard to make fast in PostgreSQL with our current tree-structure, but at the same time we need the relyability of an ACID database. For ElasticSearch the same query would be simple - we just need an index with all of the information in a single document.
- ElasticSearch is optimized for read speed and for searching and analyzing data. This is what we do in more or less all except our single-object detail views and our create/update/delete views.
## Downsides?

None as far as I can tell. We already add all of this to ElasticSearch via Haystack, but it is only used for search.
## Implementation?

We should most likely go for a pyelasticsearch approach instead of using Haystack as we are today. Haystack is optimized for full text search, not for using ElasticSearch as a document store. It would work, but we will be working through an extra layer that just makes optimizing for ElasticSearch more complicated.
## Complexity

This can be introduced gradually. I would start using it for #749 and #758. That would require adding ElasticSearch support to cradmins ObjectTableView, or to add something similar to ObjectTableView for ElasticSearch.

**Comment by torgeirl** [comment]
I believe PostgreSQL fulltext search replaced the use of ElasticSearch in Devilry 3.x (see #927), and that this is no longer relevant.
