### ISSUE TITLE
As an examiner, using the "next"-student button on the top right should show all deliveries

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#772]
As an examiner, if I use the "next"-student-button on the top right, I am taken directly to the last delivery on the task. If the student have added multiple files for the delivery in separate uploads, it may lead to the examiner thinking that some files are missing. 
### Suggestion 1:

If the group has more than one delivery, redirect the user to the list of deliveries.
### Suggestion 2:

If the group has more than one delivery, show a (warning) message that informs the examiner that this user has more than one delivery.

**Comment by torgeirl** [comment]
No longer relevant.
