### ISSUE TITLE
Displaying a list of group members on a delivery

### ISSUE THREAD

**Issue by NotoriousBIB** [devilry/devilry-django#773]
It would be nice to have a list of other group members when looking at open assignments, deliveries and feedbacks. Or at least an icon indicating that this is a group delivery.

**Comment by espenak** [comment]
This is a duplicate of #737. #737 will be fixed during the summer.

**Comment by espenak** [comment]
Ahh or perhaps you mean in the examiner UI?

**Comment by torgeirl** [comment]
We still need to make group and individual assignments more visually distinguishable from the student perceptive, but that is handled in #915 so closing this issue.
