### ISSUE TITLE
Show clearly and proactivly if the delivery has a delivery

### ISSUE THREAD

**Issue by blt950** [devilry/devilry-django#774]
(Student UI)
There should be a possibility to see without clicking on each delivery if you've delivered something to it. For example a number of amount of deliveries or just a tiny green/red dot next to the name to indicate if this assignment has been delivered or not.

**Comment by espenak** [comment]
I agree, and I think the number of deliveries would be a good solution. Adding this to 2.4.0 milestone.

**Comment by torgeirl** [comment]
This issue predates the release of Devilry 3.x in January 2018, where the UI got a major overhaul.
