### ISSUE TITLE
Create a mockup of updated examiner UI using django-cradmin

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#776]
We will be moving the examiner UI over to django-cradmin (which is also developed by the Devilry development team).
## Why a "new" ui?

We have several examiner UI issues that would be trivial using Django cradmin, and would require a lot of boilerplate code that we get for free from django-cradmin. We are changing some fairly major things in the core to support #615 and #509, so the most complex parts except for the listings (which cradmin gives us more or less for free) must be rewritten.
## Requirements

We should keep the overall workflow, but:
- Have a much more powerful overview of a single assignment.
- Have a better workflow for multiple tries.
- Have a flatter navigation structure. The default should be to provide feedback. Getting a full overview of all deliveries should require an extra click (or be a secondary button like "Write feedback" is today since clicking the link is the most natural navigation choice).
- Have much more natural support for correcting non-electronic deliveries. Will most likely require different UIs (perhaps separate views) some places in the UI.
- Use the ElasticSearch cache for all listing operations. We will adjust the cache to contain exactly what we need for this UI.

Make sure we keep:
- The ability to create feedback in bulk.
- The ability to work on feedback as a todo list, but use cookies (django session) to save the filters that make up the TODO list. In the current examiner UI, the TODO list is all waiting for feedback, but what about filtering on everyone on their first deadline (have 1 deadline), or filter by everyone I have already given feedback to?

**Comment by torgeirl** [comment]
No longer relevant.
