### ISSUE TITLE
Create a logging framework that can log all dangerous/important changes

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#777]
This logging system will serve 2 roles:
- Provide a personal overview over what you have done.
- Provide superusers with a detailed low-level log where they can dig for information when something strange happens. Typically to protect students from things like an admin changing the grade without providing a reason.
## Design

Create a `devilry_log` Django app with a model named `LogEntry` that has the following attributes:
- `user`: The use that performed the action (the student that made a delivery, the examiner that added /changed the feedback, the admin that changed the grading system config, etc.)
- `message`: A message that explains the change in the language of the `user` (a translated string). Typically something like:
  
  > Updated the comment #c:412421321# for delivery #d:13241#.
  
  The `#<something>` are links that we will autolink when listing the log in the UI.
- `messagetype`: Each message should have a type that we can use to group comments. Should be an indexed CharField with a well defined set of choices.
- `affected_object`: The primary object affected by the logged change (generic foreign key). Can be NULL (for DELETE). The idea is to link the change to an object. I think it may make sense to never go further down in the hierarchy than AssignmentGroup for this _link_, meaning that this will be one of Node, Subject, Period, Assignment or AssignmentGroup. That way, we can list the log of changes for an entire AssignmentGroup fairly efficiently (show some types of log messages to all students on the AssignmentGroup, and the same for examiners).
- `changejson`: A blob of JSON data that sysadmins can use to dig for information about the change. Typically a dump of the entire change. For a feedback change, this will be a JSON dump of the entire feedback with all comments, grading system data, etc. Will not be user friendly, but it will be something that sysadmins can dig through if they suspect something strange has been done. Should be a JSONB field since that will make it possible to efficiently query this data.

**Comment by torgeirl** [comment]
We have since moved away towards writing delivery-relevant changes directly in the feedback feed. Combined with server-side logging (currently using Sentry) this seems to cover this issue.
