### ISSUE TITLE
Automatically add new students on existing assignments

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#783]
Add a new ChoiceField on `Period` named `sync_students_to_assignments_mode`. Possible values:
- `on-new-assignments` (default): Add all current students from the Period to assignments when they are created, but do not automatically add students to existing assignments.
- `sync`: Add all current students from the Period to assignments when they are created, AND add any students added to the Period to all existing assignments.

Add a new BooleanField named `sync_students_to_assignments_mode_selected` to Period, if this is not `True`, we show a clear message on the Period admin dashboard where they need to select `sync` or confirm that they want to use `on-new-assignments`.

The code for adding students to existing assignments should be added to the `Period` class in a method named `create_groups_for_students(user_queryset)`. The celery task should be added to `devilry.apps.core.tasks`, and the task should be triggered by the view where we add the students.

**Comment by torgeirl** [comment]
No longer relevant.
