### ISSUE TITLE
Devilry adminui student and examiner management views

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#797]
### Assign examiners to AssignmentGroups manually

Should be a two-step process, where page1 selects an examiner and page2 selects the students.

Examiner view should have the following information:
- Name and email/username
- Is examiner for any groups. (yes|no)
- Who they are examiner for (fade out if many) (not MVP)
- Tags?

Should be able to filter students by:
- Have no examiner.
- Have specific examiner.
- Has no feedback.
- Tag

Live filtering:
- AND and OR for various properties.
### Assign examiners to AssignmentGroups randomly

Should be able to select two or more examiners, and some students (or all), and assign the examiners randomly to the students (with even amounts of groups). Same page1 and page2 as the manual assign wizard. May want to have a shortcut for selecting all.
### Organize students in project groups manually

This means merging groups.
### Browse AssignmentGroups

Page1 is the same listview for students as the assign examiner views page2, but you can not perform multiselect, only browse down to the detail view for each group.
### Delete multiple groups wizard

Page1 is the same as as assign examiner views page2. Select the groups you want to delete, and show confirm and summary on page2.
### Without multiselect
- List all students (fetch from elasticsearch).
- 3 lines of information:
  - Full name + (username) + email (link to detail view)
  - Status (waiting for feedback, …) + grade
  - Digest of comment stream (number of files delivered, number of comments, …)
- Button to open detail view in new window.
- Filter and live search (same thing, but filters are buttons that add stuff to the live search field)
### With multiselect
- The name is no longer a link, but we keep the button to open the detail view in new window.
- Big “Select" button to the left of each group. Clicking the button adds the group to a column on the right side with overview of all selected groups, and a button to move to the next page.
- When no groups are selected, the sidebar only shows a help message (Select the groups you want to ….. (different for each wizard)).
- On mobile, the overview of selected groups are in the bottom, and we show a message about this on the top. Ideally, we should have a fixed indicator of selected groups (a 60px wide column), with shortcut that scrolls down to the overview of selected groups.
### Filter and search
- Search searches the entire AssignmentGroup document, with higher weight on name/email/username.
- Filter is a select menu with some simple and common filters (Have no examiner, Have specific examiner, Has no feedback, Tag), and an option to switch to advanced mode. Advanced mode shows a text field where you can type advaced queries (I.E.: `examiner.name:Peter AND (student.email:johnny OR student.email:peter)`) and expands a help box with examples and reference of supported queries. The select menu should use optgroup to group the various filters.

**Comment by espenak** [comment]
This will be implemented instead of #555.

**Comment by torgeirl** [comment]
No longer relevant.
