### ISSUE TITLE
Workflow for completing assignment setup

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#798]
The assignment dashboard should have an area in the top that pushes the admin to finish setting up the assignment. Should have:
- A progress indicator
- Shortcuts for adding examiners by common patterns, or manually (see #797).
- Ask the user to select a grading plugin, or confirm the default.

Should always have 1 focus, in this order:
- Select grading plugin.
- Add examiners.

**Comment by espenak** [comment]
We also need shortcuts for re-organizing the students on the assignment. Lets say a user creates "Assignment 2". It will automatically get all the students from "Assignment 1", but the admin wants to only have the students that passed "Assignment 1". This requires a wizard that works just like the "Add students" wizard, but this wizard ends up removing any existing students on the assignment and adding new students.

This should only be available when the assignment has not yet been published (assignments are not published immediately, and unpublished assignments will never have deliveries and feedback because it is not possible to change the publishing time of an assignment with feedback or deliveries).

**Comment by torgeirl** [comment]
No longer relevant.
