### ISSUE TITLE
Examiner UI, improvement suggestions

### ISSUE THREAD

**Issue by krisbrox** [devilry/devilry-django#801]
When correcting assignements in courses with many smaller obligatory assignements, the following UI-features would greatly improve user experience for examiners:
- Keyboard shortcut to write feedback, instead of having to click the "write feedback"-button.
- Keyboard shortcut to publish without preview, instead of having to scroll the screen down and click the "publish without preview"-button.

**Comment by espenak** [comment]
Great suggestions. We are working on an updated examiner UI for devilry 3.0 (will be released in the next weeks). May be able to get this implemented as part of that release.

**Comment by krisbrox** [comment]
Great news!

I would suggest ctrl+enter as publish shortcut, as that is what many people are used to from the gmail web client.

**Comment by espenak** [comment]
We actually already have that in the pipeline for v3 for all forms in Devilry, and ``ctrl/cmd+/`` to go to search fields.

**Comment by torgeirl** [comment]
This issue predates the release of Devilry 3.x and is therefore no longer relevant.
