### ISSUE TITLE
Can't add a delivery after having the deadline delayed

### ISSUE THREAD

**Issue by Dan-Mikkel** [devilry/devilry-django#804]
I have an issue with uploading a file now for one of my obligatory assignments.
I've gotten the deadline delayed and it looks like that is marked on top of the add delivery page with "egenmelding".
When i try to upload a file, there seems to be no troubles when uploading it, as you can see on this screenshot.
![image](https://cloud.githubusercontent.com/assets/1862070/9993839/43b1ff76-607a-11e5-8fa3-0f8ec96fcb2e.png)
After the uploading is done, however, i can't see the file being listed as delivered, although a red cross for deleting files from the list have appeared.
![image](https://cloud.githubusercontent.com/assets/1862070/9993854/5f98fdc0-607a-11e5-92ff-5a9f7430bb7f.png)
When i try to press the button for delivering the file to my course teacher, i only get an error message stating that i need to add at least one file before completing the delivery.

Right now, i am at a loss on what i can do, i've tried doing it on Google Chrome and Firefox with the same results.

**Comment by espenak** [comment]
Hi, I think this is caused by a full disk at UiO. I have reported this to IFI drift.

**Comment by torgeirl** [comment]
This issue predates the release of Devilry 3.x, and has been solved.
