### ISSUE TITLE
Not updated information string in Course Manager->assignment->Students->'student'

### ISSUE THREAD

**Issue by gardir** [devilry/devilry-django#805]
When looking at a student in students in an assignment, on the top it tells me "Note: Students can not see their points, only the grade, and if it is failed or passed.", which is not the case. The assignment is set up to show students the points they receieve - so I expect it to be missing a reference to the Grade System or similar. See attached pictures for more information.
![devilry](https://cloud.githubusercontent.com/assets/6617987/10333718/05379148-6ce6-11e5-95e2-4131df563760.jpg)
![devilry_info](https://cloud.githubusercontent.com/assets/6617987/10333717/05375ce6-6ce6-11e5-8eb1-6a3d08b92111.jpg)

**Comment by tworide** [comment]
Thanks.

Sorry for the late reply. This issue just passed through. You are right. The message does not comply with the current grading setup. We will fix this as soon as possible. Thanks for the notification

**Comment by torgeirl** [comment]
This issue predates the release of Devilry 3.x, and has been solved.
