### ISSUE TITLE
Would be nice to get notification when given new deadline without feedback

### ISSUE THREAD

**Issue by hanscje** [devilry/devilry-django#807]
Hi!
I got a new deadline on an assignment in Devilry with no feedback from the examiner. It would be nice if you could implement a function that sends you a email that you have gotten a new deadline. (I saw the new deadline too late).

**Comment by espenak** [comment]
This will be implemented for Devilry 3.0 (the next major version).

**Comment by torgeirl** [comment]
> This will be implemented for Devilry 3.0 (the next major version).

This was fixed in Devilry 3.x.
