### ISSUE TITLE
Add unique_together for RelatedStudent for candidate_id and period

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#808]
Add unique_together for RelatedStudent for candidate_id and period.

**Comment by apparator** [comment]
#792

**Comment by apparator** [comment]
I tried adding 
```python
    class Meta:
        unique_together = ('period', 'candidate_id')
```
but making a migration for it leads to this when running migrate:
```sh
django.db.utils.IntegrityError: could not create unique index "core_relatedstudent_period_id_5d571114cb81c9fa_uniq" DETAIL:  Key (period_id, candidate_id)=(1, ) is duplicated.
```
I could not find the reason for this, so I reset and am going to wait looking more for this until later.

**Comment by apparator** [comment]
The reason this migration does not work, is that in the current testdata it looks like this:
```sql
COPY core_relatedstudent (id, tags, candidate_id, automatic_anonymous_id, period_id, user_id, active) FROM stdin;
1				1	5	t
2				1	2	t
3				1	6	t
4				1	7	t
5				1	13	t
6				1	8	t
7				1	17	t
8				1	16	t
\.
```
in `devilry/project/develop/dumps/default.sql`. That is `candidate_id` and `period_id` "" and 1 exists multiple times here.

**Comment by apparator** [comment]
This will be handled in the view for adding candidate number.

**Comment by espenak** [comment]
We can do this if we:
- A schema migration that sets the ``RelatedStudent.candidate_id`` field to ``null=True``.
- A data migration that sets all empty values in ``RelatedStudent.candidate_id`` to ``None`` (``relatedstudent_model.filter(candidate_id='').update(candidate_id=None)``.
- Add a validator to ``RelatedStudent.candidate_id`` that does not allow empty value (with a test in ``test_relatedusers.py``).
- Add the ``unique_together`` restriction.

So re-opening the issue.

**Comment by torgeirl** [comment]
No longer relevant.
