### ISSUE TITLE
Datamigration that sets or creates Candidate.relatedstudent, and removes Candidate.student

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#810]
Instead of having a foreignkey from Candidate to User, we will use the new ``relatedstudent`` field. Instead of removing RelatedStudents, we will set ``RelatedStudent.active=False``.

The datamigration must create ``RelatedStudent`` with ``active=False`` for Candidates without a RelatedStudent within the period (``candidate.assignment_group.parentnode.parentnode``).

**Comment by apparator** [comment]
Set `relatedstudent` to null=False
And `old_reference_not_in_use_student` to null=True
