### ISSUE TITLE
Datamigration that sets or creates Examiner.relatedexaminer, and removes Examiner.user

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#812]
This means that removing a RelatedExaminer will remove the examiner from all their AssignmentGroups within the Period. This makes sense from an administrator perspective - the examiner looses access to the students when they are removed from a Period (semester). This should not be a problem because all metadata connected things the examiner has done is still available (we have ForeignKey to Examiner from Comment and FeedbackSet).

The datamigration must create RelatedExaminer for Examiners without a RelatedExaminer within the period (``examiner.assignmentgroup.parentnode.parentnode``).

See also #811 and #810.

**Comment by apparator** [comment]
Commit for fix of this issue:
https://github.com/devilry/devilry-django/commit/2bb1f6b945ca4a33a067a862c9c1f4194a2d0ebd
