### ISSUE TITLE
oblig ``bulk download'' not complete

### ISSUE THREAD

**Issue by MartinSteffen** [devilry/devilry-django#814]
Hi, I stumbled upon the following bug. In a role as "course examiner" I am supposed to correct a bunch of hand-ins. A very welcome feature of devilry is the "bulk-downlod" where I can get a zipped/archived bundle of all the solutions I need to correct.

Now: I just observed, that the "archived download" does /not/ contain all the solutions, i.e., those I can see (and click/download) when surfing the students entry in the given assignment individually. At least one was missing (I have not checked all).  That's disturbing, because this way, the off-line bulk-download is unreliable and needs to be cross-checked with the online-version not to miss out solutions. For large courses, that's quite some overhead, to check consistency.

Martin

**Comment by espenak** [comment]
That is something we need to dig into. It will help us a lot if you could send as much information as possible (course name, assignments and missing students) to devilry-core@ifi.uio.no.

**Comment by torgeirl** [comment]
Devilry's archive builder have been reworked quite a few times since this issue was opened so I assume this is no longer relevant.
