### ISSUE TITLE
Create a crmenu.Menu subclass for Devilry

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#820]
## Relation to the old menu

The old black vertical meny/navbar will be replaced by this.
### In the header
- The logo
- Breadcrumbs in a tree (each level indented, and the current level highlighted). Should have a "You are here" heading.
### In the body

Instance specific items (the apps for that instance).
### In the footer:
- Logout button
- Edit user profile.
- Search.

We may also want to consider a context aware help link in the footer. Could link to the assignment admin guide when you are in the assignment cradmin instance, and the period admin guide when you are in the period cradmin instance, and so on.

**Comment by torgeirl** [comment]
No longer relevant.
