### ISSUE TITLE
Consider unifying the frontpage for all roles into a single view

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#821]
This should be fairly straigt forward:
- Show upcoming assignments where you are student at the top.
- Show assignments where you are examiner ordered by what you should focus on next in the middle.
- Show administrator stuff at the bottom.

We can color these 3 boxes with the role colors, so for old users it will just feel like they (in the most common cases) do not have to use one extra click, while maintaining the clean separation between the different roles.

This will not add any significant time to the 3.0.1 release because:
- Most of the stuff for students and admins can just be moved into the new view.
- The examiner role frontpage has not been updated for 3.0 yet.

**Comment by torgeirl** [comment]
No longer relevant.
