### ISSUE TITLE
Assignment overview page

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#826]

**Comment by espenak** [comment]
## Design
![assignment 3](https://cloud.githubusercontent.com/assets/84501/12216735/efd92d20-b6eb-11e5-9f99-32e63bcba87b.png)

## Design details
The green box at the top is the (django messages) success message from the create new assignment view.

The blue box at the top is only visible when the assignment is not published.

Devilry core developers can [edit the design here](https://docs.google.com/drawings/d/1G5xiLC3Iw35HnXiFkAmeibMriHLmhJlkEeGDtBeKVTY/edit?usp=sharing)

**Comment by espenak** [comment]
## Missing handling of no students
Should show a warning.

## Missing backlink in header for edit views
```htmldjango
{% block pageheader-outer-extraclasses %}
    {{ block.super }}
    devilry-page-header-with-backlink
{% endblock %}

{% block pageheader-inner %}
    <a href="{% cradmin_appindex_url %}" class="devilry-page-header-backlink">
        <span class="sr-only">
            {% trans "Back to assignment overview" %}
        </span>
        <span class="{% cradmin_icon 'devilry-pageheader-back' %}" aria-hidden="true"></span>
    </a>
    {{ block.super }}
{% endblock pageheader-inner %}
```

**Comment by espenak** [comment]
## Do not show save and continue
Use ``django_cradmin.viewhelpers.crudbase.OnlySaveButtonMixin``.

**Comment by espenak** [comment]
## Handle no examiners configured for any groups
Show warning, explaining how this works.

**Comment by espenak** [comment]
#798 is a part of this issue.

**Comment by torgeirl** [comment]
No longer relevant.
