### ISSUE TITLE
Replace filter_is_examiner and filter_is_candidate on Assignement and AssignmentGroup

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#828]
In AssignmentGroup and Assignment (manager and queryset).

Remember to update the ``filter_*_has_access`` methods on AssignmentGroup. I think they may already be implemented in AssignmentGroupQuerySet.

**Comment by apparator** [comment]
These are replaced in AssignmentGroup, so reference this when doing this task.

**Comment by apparator** [comment]
`AssignmentQuerySet.filter_is_candidate` for model `Assignment` does not seam to be in use any other place than `AssignmentQuerySet.filter_student_has_access`. Renaming `filter_is_candidate` to `not_in_use_filter_is_candidate` did not make any tests fail, and also it seams like nothing fails when testing manually.
