### ISSUE TITLE
Rename filter_examiner_has_access to filter_examiner_user_has_access 

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#829]
Rename `Assignment.objects.filter_examiner_has_access` to `Assignment.objects.filter_examiner_user_has_access`. 

This to make sure we do not end up with false positives on running tests.

Must be done in AssignmentGroup too.

Run all tests in core, and then fix, before running all tests.

**Comment by torgeirl** [comment]
No longer relevant.
