### ISSUE TITLE
Preview AssignmentGroup as student or examiner?

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#832]
I am thinking of an option for the feedback feed view (in devilry_group) where an admin can view the assignment as it looks for a student or an examiner. The idea is to give admins an option to preview the assignment before publishing it.
## How?

I think the easiest solution here would be to provide two extra subclasses of FeedbackFeedBaseView. In these views we should mock/temporary create an AssignmentGroup where the admin (request.user) is both Examiner and Candidate, add a header to the top of the page that states clearly that this is a preview, and allow them to switch between viewing as student or examiner.
## Why?

Because admins often add themself as student or examiner on an assignment to test their configuration. If we have this we can avoid that, and we can provide the admins with an option to preview their assignment before publishing it.
## Editing?

I think we should create the AssignmentGroup with:
- `is_preview=True`
- `preview_created_datetime=<datetime>`
- `preview_delete_datetime=<datetime>`
- `preview_created_by=<User>`

We should automatically delete the AssignmentGroup at or sligtly after `preview_delete_datetime` (in a celery task). Admins can do whatever they want with this disposable AssignmentGroup. We should show something like `This preview will be deleted <datetime formatted> - <postpone for 3 hours button>` in the header.
## Is this hard to add?

@StianJul would this view be hard to add? The celery task should be fairly easy.

**Comment by torgeirl** [comment]
@espenak: I see you ask whether this would be hard to add using Celery tasks. I assume this could change with Celery now being replaced by RQ?

As you explained under 'Why?' a "View as..." function is a feature our course and semester administrators requests. I would rate at medium importance, possibly something that would be nice to have added with the Q2 milestone we discussed with @tworide (UI updates + FS integration).

**Comment by torgeirl** [comment]
No longer relevant.
