### ISSUE TITLE
Document permissions in the user docs

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#843]
## Administrators
- What semester admins have access to:
  - Show all non-anonymous assignments within their semesters.
  - see semester overview, but their overview does not include anonymous assignments (exams).
  - edit students on their semesters.
  - edit examiners on their semesters.
- What course admins have access to:
  - Everything that semester admins have access to.
  - see semester overview
  - qualified for final exams
  - add period admins
- What department admins have access to (superuser within their courses).
  - Everything that course admins have access to.
  - add course admins
  - edit candidate IDs for a semester and assignment
  - delete students (groups) with deliveries or feedback.
- What superusers have access to.
  - Everything that department admins have access to, but superusers automatically have access to all courses, not just the courses where they have been granted implicit access.
  - Access to the superuser UI (a fairly low level database editing UI). 
## Students

Have access only to published assignments within started semesters where they have been added as student on the assignment.
## Examiner

Have access only to published assignments within active semesters where they have been added as examiner.

**Comment by torgeirl** [comment]
No longer relevant.
