### ISSUE TITLE
Anonymization of fully_anonymized assignments for admins

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#846]
The following restrictions will apply to course admins (semester admins do not have access to fully anonymous assignments at all):
- In the overview of students. **Can not show any information about grades, status, examiners, group ID or candidate/anonymous IDs**. If we show status, a course admin that is also examiner can correlate username with their anonymized students in the examiner UI if they are the first to start giving feedback. So to the list will be simplified to only include search, ordering and list of names, and no link further down in the hierarchy. We must also avoid using DOM IDs/css classes that include `AssignmentGroup.id`.
- Remove access to organizing examiners.
- Can not change anonymizationmode..
- Can not change "publishing time" (this applies to non-anonymous assignments as well, but including it here because it is an important part of the anonymization process).
## Why remove access to certain things after the assignment has been published?

When the assignment has been published, the examiner UI is available to examiners. If they have access to both the students they are grading and information about the mapping between examiner and student in the admin UI, they can easily correlate anonymized named with real names.
## Why hide AssignmentGroup.id

Because it is part of the URL in the examiner UI.
## "But I need to see the candidateID to communicate with examiners!"

The whole point of fully anonymous assignments is to actually be fully anonymous from everyone except department admins and superusers. If you use "semi-anonymous", you get the ability to see candidate IDs. Also note that an intended workflow is:
- Setup the assignment in fully anonymous mode.
- Complete grading.
- When grading is finished, get a departmentadmin to set the anonymizationmode down to "semi-anonymous" to enable you to access the grading details.

**Comment by torgeirl** [comment]
No longer relevant.
