### ISSUE TITLE
Make RelatedExaminer.automatic_anonymous_id and RelatedStudent.automatic_anonymous_id required

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#852]
Must create a datamigration that generates `automatic_anonymous_id` for all existing RelatedExaminer objects. This data migration will have to:
- Loop through all periods in the database.
- Generate `automatic_anonymous_id` with https://github.com/appressoas/random_name_generator/issues/2. One list for RelatedExaminers and one list for RelatedStudents, using diffent namelists.
- Loop through all the RelatedStudents and set and save `automatic_anonymous_id`.
- Loop through all the RelatedExaminers and set and save `automatic_anonymous_id`.

**Comment by torgeirl** [comment]
No longer relevant.
