### ISSUE TITLE
How to handle changes to grading configuration after feedback has been published?

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#862]
If feedback has been published, I think we should add a FeedbackSet with `feedbackset_type="feedbackset_type_new_try"` to all groups where the last feedbackset is published. This means that the groups will no longer have the status of `"corrected"`. We should also require a comment from the admin that explains the reason for this, and that comment should be added to all the groups where we had to retract their current grade.

**Comment by espenak** [comment]
We could suggest a comment text. Something like this:

> We had to update the grading configuration for this assignment. You will get a new feedback for this assignment.

This could be pre-filled in the comment field or just a suggestion in the help text.

**Comment by torgeirl** [comment]
No longer relevant.
