### ISSUE TITLE
View with all comments the user has access to

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#865]
I think we should add a view where a user can browse all comments they have access to. This should be a simple listview with filters for read/unread and search.

We already have the data structure we need for this view except for a way to track if a user has read a comment. I think that we should just add a `read_by_users` ManyToManyField to Comment to track this. We should track this just as suggested in #838 (track a read when the user visits a view containing the comment).

**Comment by espenak** [comment]
This is probably mostly useful for examiners and students. The only issue is that the queries are fairly heavy, so I think we may want to use ElasticSearch for this.

**Comment by torgeirl** [comment]
This is probably better covered by #1127 (User data requests pipeline).
