### ISSUE TITLE
Should we support that examiners can be anonymous to other examiners?

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#866]
I have no idea if this has any real use cases. We can easily add this as an option for an anonymous assignment. It is also easy to provide feedback along with other examiners if the other examiners are anonymous:
- All communication between examiners can happen in Devilry.
- Each examiner gets an anonymous name that follows the examiner through an entire period.
- We have all of the code for this since we already anonymize examiners from students on anonymous assignments.

**Comment by torgeirl** [comment]
No longer relevant.
