### ISSUE TITLE
Tag system for deliveries

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#87]
We should be able to tag any _delivery_ belonging to an assignment. This has several use cases:
1. Examiner needs an opinion on a delivery. It may be he/she suspects a cheater, or it may be the delivery is very close to a failed, and the examiner requires the course administration to take a closer look.
2. Examiners want to highlight an especially good delivery.
3. There is often a group of students that misunderstand ill-defined assignment texts. This system could be used to tag such cases, and thus making it easy for the course administration to get an overview.
4. Other systems can tag a delivery to notify examiners. For example, a cheat checking system integrated with devilry may add tags indicating suspicious deliveries.

I propose that we add a tag system where any examiner can create a tag, and these tags instantly become available for use by others examiners. Administrators should also be able to create tags. Tags are primarily related to assignments, however I propose that administrators can add tags to any node, and these tags are inherited. Since tags are created by one person and used by many, I propose that a tag has to consist of a name and a description. Furthermore, I propose that the tag system should be Wiki-like in the context of an Assignments, thus anyone with permission to create tags on an assignment (examiners, admins), can change the tagname and description. The underlying implementation should use a numeric id, not the tagname as identifier, however the tagname must be unique.

We need a dashboard widget where tags are organized by assignment, with the ability to filter and prioritize.

**Comment by tworide** [comment]
This issue is closed due to prolonged inactivity and / or lack of relevance to the current state of the project.

Feel free to reopen it with an added comment of relevance.

The main incentive for closing old issues is to clean up the repository and to be able to proceed with relevant new ideas for the project without the old drag.

> Tor Ivar Johansen Project maintainer
> tor@appresso.no
