### ISSUE TITLE
Turn admin dashboard into a listbuilder view with listfilter

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#871]
Should list all subjects that the user has access to in a listbuilder list. Each entry in the list should have:
- The full_name of the subject.
- A primary button that links to the last active period in the the subject. Hide this if the user does not have access to the last active period.
- A default button that links to the subject overview.
## Challenges

How do we make this efficient? We need a query that:
- Find all subjects that the user has admin access to, or where the user has periodadmin access.
- Find the last active period within this subject, and check if the requesting user has access.
## Filters

We need the following filters for the subject list:
- Search (by short and long name)
- Order by (name, last_active_period_start_time)
- Is active (has `last_active_period_start_time`)
## Default ordering

``` python
('last_active_period_start_time', 'name')
```
## Buttons

At the top of the list, we should have a `create new course` button if the user is superuser. We should extend this to departmentadmins later.
## Needed updates to other views

We need to update the subject overview page to allow periodadmin access to a list over all periods that they have access to within the subject. I think this should be a separate view within the periodadmin cradmin instance.

**Comment by tworide** [comment]
Muligheter for filtrering på tags. Lager custom templatetags for visning av tags. Kutter bort common prefixes

**Comment by tworide** [comment]
https://docs.google.com/drawings/d/1N8Qtr0H25UE430-MajT5k7T9sZkCgOuLagLy7oxCL98/edit

**Comment by espenak** [comment]
## Required new methods in SubjectQuerySet:
- ``filter_user_is_admin_for_any_periods_within_subject(user)``: The same result as ``filter_user_is_admin(user)`` + any subjects where the user is in a PeriodPermissionGroup in a Period within the subject.
- ``annotate_with_has_active_period()``: We use this for the "Is active?" filter.
- ``prefect_active_periods()``: We use this to get the link for the active period. We may choose to just use the first active, or to have a button for each active.

**Comment by espenak** [comment]
The required methods are ready. Intended usage:

```python
# For filtering the queryset (in get_unfiltered_queryset_for_role()):
def get_unfiltered_queryset_for_role(self, role):
    return Subject.objects\
         .filter_user_is_admin_for_any_periods_within_subject(user=self.request.user)\
         .annotate_with_has_active_period()\
         .prefetch_active_periodobjects()


# In the listfilter filter for is active:
# - see devilry.devilry_cradmin.devilry_listfilter.assignmentgroup.IsPassingGradeFilter
def filter(self, queryobject):
     # ...
     if cleaned_value == 'true':
          return queryobject.filter(has_active_periods=True)  # May have to be 1 instead of True - see 
     elif cleaned_value == 'false':
          return queryobject.filter(has_active_periods=False)  # May have to be 0 instead of False


# Getting the last active period
subject.last_active_period.short_name   # See the docs devilry.apps.core.models.subject.Subject.last_active_period
```

**Comment by torgeirl** [comment]
No longer relevant.
