### ISSUE TITLE
Datamigration into the new data structure below AssignmentGroup for 3.0

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#882]
## Deadlines

Deadlines is migrated as FeedbackSet.

For non-electronic assignments, we just ignore deadlines, and add all deliveries as comments below the first feedbackset, and set the first_deadline of the assignment to the end of the semester. We should keep the non-electronic marker on the assignment, and alert course admins (via email) that they should set a deadline. We should also alert them on the assignment overview page. This means that we need to allow them to change the deadline if the assignment is non-electronic, and set it to "electronic" after they change the deadline.

Should add an `old_deadline_id` field to FeedbackSet, and store the ID of the old deadline there. This is in case something goes wrong (and we detect that after we are in production), and we need to make new migrations to fix the problem.
## Delivery

Migrated to GroupComment with empty comment text but same metadata (same creation time).

**TODO**: How do we migrate `copy_of`? Should probably wait for #881 before doing this.

Should add an `old_delivery_id` field to GroupComment, and store the ID of the old delivery there. This is in case something goes wrong (and we detect that after we are in production), and we need to make new migrations to fix the problem. The field must have `db_index=True` (for #883).
## FileMeta

Migrated to CommentFile. This means that we have to `read()` the data from the FileMeta, and save it into the `CommentFile`.

Should add an `old_filemeta_id` field to CommentFile, and store the ID of the old delivery there. This is in case something goes wrong (and we detect that after we are in production), and we need to make new migrations to fix the problem.

**Comment by torgeirl** [comment]
No longer relevant.
