### ISSUE TITLE
Oppdatert ElasticSearch cache for 3.0

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#885]
We at least need to add what we require for searching, but we also want to see if we can move the most expensive queries:
- AssignmentGroup overview (for students, examiners and admins)
- admin dashboard
- overview of all results for a period (should be the same dataset as AssignmentGroup overview)

**Comment by torgeirl** [comment]
I believe PostgreSQL fulltext search replaced the use of ElasticSearch in Devilry 3.x (see #927), and that this is no longer relevant.
