### ISSUE TITLE
Log all changes

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#888]
We need to ensure that all changes leave a log trail. This is important for debugging why an issue appears. For example, if we get problems with a cached field, it is important to know which part of the system (what code) actually lead to the issue.

Challenges:
- Avoid impacting performance with bulk operations. I guess we can do this by logging a single message for the change.
- Get all the important information, such as the person making the change, without impacting performance.

See also #777, #285, #474 and #456.

**Comment by torgeirl** [comment]
The debugging aspect seems to be well-covered by our current server-side logging (using Sentry) while the who-did-who part is covered by moving towards writing delivery-relevant changes directly in the feedback feed.
