### ISSUE TITLE
Deadline inactive after editing feedback

### ISSUE THREAD

**Issue by msoyland** [devilry/devilry-django#894]
The issue is that editing a failed feedback after creating a new deadline will make the new deadline inactive.

I discovered this when I as an examiner gave one of my students a failed grade on his first delivery, but immediately added a new deadline. Shortly after, I discovered a small mistake in the text feedback I gave him, so I made a quick edit. To my surprise this resulted in the new deadline becoming inactive, and the student was unable to make a new delivery. The deadline was still visible for me, and there was no indication that it was inactive, other than the student being moved from _waiting for deliveries_ to _corrected_.

I successfully reproduced the issue in a course made for testing purposes called test.testbug. I made myself both student and examiner, and observed that when I as examiner edited a few words in the failed feedback, I received a new mail and the possibility to make a delivery disappeared.

**Comment by tworide** [comment]
Thanks for reporting this. You're right. The usual workflow is to make a new feedback each time to just append to the history of feedbacks. So we have not noticed this edge-case. 

There is a whole new feedback-workflow coming up in the next version of Devilry so we will close this issue and label it with `bug-with-workaround` 

Workaround:

- Create a new deadline by failing the existing and provide a new attempt for the candidate.
