### ISSUE TITLE
Feedback sorting is sometimes wrong

### ISSUE THREAD

**Issue by torhus** [devilry/devilry-django#895]
![devilry_bug](https://cloud.githubusercontent.com/assets/19881605/19054884/ad1488d2-89c1-11e6-8b38-2b5707f08137.png)

**Comment by tworide** [comment]
Hi!

You're absolutely right @torhus. There are no specific default ordering defined in this view. Earlier we had the `Feedback time` column sortable to achieve sorting for newest/oldest feedbacks received. 

In the latest branch of development of Devilry, soon to be version 3.0 we have completely rewritten the whole feedbackflow and therefore we will label this issue as a minor `bad-user-experience` and keep it open under the 3.0.1 milestone to remind us that this should be checked upon release.

**Comment by torgeirl** [comment]
This has been solved in later releases so closing this issue.
