### ISSUE TITLE
Translation to Norwegian

### ISSUE THREAD

**Issue by rantonse** [devilry/devilry-django#898]
The word "eksporer" should be "eksporter" here:

https://github.com/devilry/devilry-django/blob/15dc771084ea14cb4083cf1feca1fb00cc441aa1/devilry/locale/nb/LC_MESSAGES/djangojs.po#L2125

**Comment by torgeirl** [comment]
This is still an issue:

https://github.com/devilry/devilry-django/blob/c0808c64b0aacd1195ef26defa15ab9bb36a3740/devilry/locale/nb/LC_MESSAGES/djangojs.po#L1700

**Comment by StianJul** [comment]
The translation has been automatically commented out since it's not in use anymore, so this just basically history from old javascript translations not in use anymore.
