### ISSUE TITLE
Scrolling in point input field for correctors

### ISSUE THREAD

**Issue by hptk** [devilry/devilry-django#900]
In the create feedback interface for correctors for an assignment where you are to give points, the field where you input the points is scrollable (without a good indication of this), meaning that I by mistake scrolled down this field and changed the score (dramatically) for an assignment when what I intended to do was to scroll down the page to submit my feedback.

Discovered it and fixed it because I pay attention, but I do not think this is good user interaction!

**Comment by tworide** [comment]
Thanks for the heads up @hptk :-)

This will not behave like this when the new version 3.0 is out. We are gradually releasing this as a closed beta now on IFI and will be released to the public before the next semester.
