### ISSUE TITLE
Folder names without spaces in download all deliveries

### ISSUE THREAD

**Issue by hptk** [devilry/devilry-django#902]
When downloading all deliveries, each student gets a folder like "151373 (groupid=353527)", at least for anonymous deliveries.

I think it would be better to avoid the space for easier terminal use to avoid the need for escaping the space. I wanted to copy a path from one terminal to another to cd, but space ruined it.

First world problem maybe, but with ver 3 coming soon I don't see why you'd want to keep this unless it's very important for legacy reasons. Other parts of created folders are using hyphens/dots/underscores for separation.

**Comment by torgeirl** [comment]
Not sure when (2018 or 2019), but this issue it solved. :heavy_check_mark:
