### ISSUE TITLE
Finalize feedbackfeed for students for 3.0

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#907]
- [ ] Cleanup styles. They are usable, but need some polish.
- [x] Make it clear that a comment is part of the delivery. It can still be questions, but you just add files to make a delivery. I suggest:
    - Change "Add comment" to "Add delivery or question"
    - Add help text: _Your delivery can be uploaded as one or more files or typed into the box above. You can also ask questions to your examiner(s), but be aware that some courses will consider how much help you needed when grading your delivery._

**Comment by torgeirl** [comment]
No longer relevant.
