### ISSUE TITLE
For period overview, change subheader from "Utilities" to "Result" on section for results

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#908]
On period update overview, change name from "Utilities" to "Result" on section for results. 
This section currently only shows results-related stuff. 

Later, if "functionality" that is more "Utilities" is made, this should be included in a new "Utilities"-section, unless it has to do with results.

**Comment by torgeirl** [comment]
Seems this section held onto the name «Utilities»! :shrug:
