### ISSUE TITLE
Digital vurdering på prelab-prøvene i FYS2150

### ISSUE THREAD

**Issue by dysthe** [devilry/devilry-django#911]
Vi trenger innspill på hvor lang tid en slik utvikling vil trenge.

I FYS2150 har vi de siste 8 årene gjennomført obligatoriske prøver før hver laboratorieøving, såkalte prelabber. Disse skal hjelpe studentene til å øve inn nødvendig forståelse og gi oss en pekepinn om vi trenger å gi studentene ekstra veiledning i løpet av labben. Vi har i en del år gjort dette elektronisk i Fronter, delvis med automatisk retting. I 7 år har vi strevd med formen og hvordan gi studentene flere forsøk uten å gi dem riktige svar. Vi har nå gitt opp å gjøre dette i Fronter. Vi mener at beste måte å få til en prøveform som er elektronisk, automatisk retting av deler av oppgavene, automatisk tilbakemelding og ny sjanse er å programmere det for innlevering i Devilry. 
Siden vi har lang erfaring med hva vi trenger er denne oppgaven klart definert.
Vi vil legge opp arbeidet med milepæler med fungerende innleveringssystem med stadig flere av funksjonalitetene vi ønsker. Da vil systemet kunne tas i bruk selv om ikke all funksjonalitet er implementert i første runde. Dette er en type vurdering med fokus på innlæring som mange andre kurs burde kunne ha nytte av. 

Vi tenker på å ansette en eller to sommerstudenter til en slik jobb. Kan dere gi oss en pekepinn på hvilke deloppgaver som vil ta tid og hvor mange studenter og uker de vil trenge?

Hilsen Dag Kristian Dysthe
Vennligst svar meg på dagkd@fys.uio.no da jeg nærmest aldri er innlogget på github

**Comment by tworide** [comment]
Henvendelsen er besvart over mail.
