### ISSUE TITLE
Make publishing feedback from preview quicker 

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#912]
Add a "Publish feedback" button below the "NOT PUBLISHED" text in the blue box to make publishing easier.

![image](https://cloud.githubusercontent.com/assets/652657/24285641/6b3d801c-1071-11e7-85f0-cc0a2207b03b.png)

**Comment by apparator** [comment]
How about adding a button like this:

![image](https://cloud.githubusercontent.com/assets/652657/24291000/70630e98-1087-11e7-89ea-8be709d9b11b.png)

**Comment by torgeirl** [comment]
No longer relevant.
