### ISSUE TITLE
Bug when updating examiners through REST

### ISSUE THREAD

**Issue by KGHustad** [devilry/devilry-django#914]
*This affects the version of Devilry currently deployed at IFI.*
I'm trying to send a PUT request on an assignment group to change the examiners of a group.

If the group initially has one examiner, Alpha, and one tries to set the new examiners to Alpha and Beta, Devilry responds with a 400 with the error message "The same user can not be examiner multiple times on the same group."

The json sent looks like this (with identifying data replaced with variables)
```
{'id': id1, 'candidates': [{'user': {'username': uname, 'displayname': X, 'id': id2, 'full_name': X, 'email': X}, 'id': id3, 'candidate_id': None}], 'examiners': [{'user': {'id': ex_uid_alpha}}, {'user': {'id': ex_uid_beta}}], 'is_open': True, 'tags': [{'tag': 'rettegruppeX', 'id': id4}]}
```

If I first remove all examiners, and then add Alpha and Beta, then everything works fine.

**Comment by espenak** [comment]
This should not be a problem with the APIs in the 3.x branch, but we need to look into it. I do not think we need to fix this in the 2.x branch since we have a workaround as explained in the issue description. @Eskalol can you check if this affects the 3.x APIs?

**Comment by Eskalol** [comment]
The 3.x APIs does not currently support adding or removing examiners from an assignment group. We should Implement APIs for the period admin role (head group teacher) which serves this purpose. Thank you @KGHustad for notifying us about this issue.
