### ISSUE TITLE
Make group and individual assignments visually distinguishable

### ISSUE THREAD

**Issue by anettegj** [devilry/devilry-django#915]
And which group the delivery was made with. 

There should be a visual clue when looking at the list of deliveries which are done as a group an which are not.  Also when making a delivery it would be good to be able to confirm that this is part of a group assignment.

**Comment by torgeirl** [comment]
Hi @anettegj. I assume you made this issue for Devilry 2.0.x. In Devilry 3.x.x group assignments (like many other things) looks a little different, but some improvements are still needed.

**Description**
In `3.x.x` group assignments still looks very similar to individual assignments from a student's perspective. The only difference seems to be a green link titled `Project group details` at the top of the feedback feed view (second image) which opens a new view listing the group members (third image).

![915a](https://user-images.githubusercontent.com/796053/40657607-c855209a-6348-11e8-8485-37bc7311a14d.png)

![915b](https://user-images.githubusercontent.com/796053/40657611-cae471ee-6348-11e8-91b6-d9f327a0ae39.png)

![915c](https://user-images.githubusercontent.com/796053/40657615-ce7ce0ca-6348-11e8-81c3-d0eed4539d8e.png)

**Solution**
Some suggestions to how this could be solved:

- Make group and individual assignments visually distinguishable from the student perceptive (both in the period assignment overview, and within the feedback feed view)
- Replace the `Project group details` link in the feedback feed view with a listing of group participants. If the list is N long, it should be folded.
