### ISSUE TITLE
Provide login through Feide

### ISSUE THREAD

**Issue by apparator** [devilry/devilry-django#916]
Want to test this lib:
https://github.com/fangli/django-saml2-auth

**Comment by henrist** [comment]
Just a little heads up: We have a Django application in Cybernetisk Selskab which is connected to Weblogin. However, we're on Python 3 and using _python3-saml_ by OneLogin:

https://github.com/cybrairai/internsystem/tree/master/samlauth
https://github.com/cybrairai/internsystem/blob/master/samlauth/prod/settings.json
https://github.com/onelogin/python3-saml

Demo: https://in.cyb.no/login

I'm not sure about the differences between _django-saml2-auth_ and _python3-saml_ (or _python2-saml_), but at least it might be some inspiration for later work.

**Comment by tworide** [comment]
@henrist Thank you so much.

We will look into this :-)
