### ISSUE TITLE
Easier Markdown/LaTeX editing workflow suggestions

### ISSUE THREAD

**Issue by TormodLandet** [devilry/devilry-django#917]
Bitbucket, github etc have a preview tab above the text editor which will render markdown and show the result without leaving the page. 

In devilry, when writing a more detailed response with some equations etc I need to press preview, get a new page and then press edit to go back. It would be faster and more seamless to have this preview functionality "inline" in the form.

What about using more "normal" markdown as well? The equation is a bit cumbersome and I cannot find a way to write inline math. supporting $xxx$ for inline math and and \[ss\] or $$sss$$ for expressions like e.g. Jupyter would be more handy
http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Working%20With%20Markdown%20Cells.html#LaTeX-equations

**Comment by KGHustad** [comment]
I really miss this feature. Are there any plans to implement it?

**Comment by torgeirl** [comment]
@KGHustad: we do intend to improve the comment editor (issue #1040), but I don't know when we'll get to it.

**Comment by torgeirl** [comment]
Devilry 5.4 included an improved comment editor, and among the improvements are easy Write/Preview toggling. Further improvements on the editor will be included in Devilry 5.5, including better support for code and LaTeX.
