### ISSUE TITLE
Explain terms on 'examinerstats' page

### ISSUE THREAD

**Issue by lexnederbragt** [devilry/devilry-django#919]
Some help text would be appreciated. 

The Norwegian ones are

> Grupper med bestått karakter
> Grupper med ikke-bestått karakter

These are fine

> Grupper som venter på tilbakemelding

I assume these have not been graded yet but that is not immediately obvious

> Grupper som venter på at innleveringsfristen skal utgå

Not yet delivered? Again, not obvious

> Lukket uten tilbakemelding

OK

**Comment by tworide** [comment]
@lexnederbragt 
Have you tried switching to English?
You can do that by clicking on the user icon on the right side of the header.

![image](https://user-images.githubusercontent.com/93136/29876253-8b0687d8-8d9c-11e7-9430-18f9c979fc7a.png)

**Comment by lexnederbragt** [comment]
Same problem for a first-time course leader like me (som snakker norsk). Is "Groups waiting for feedback" delivered but not yet graded? And "Groups waiting for deadline to expire" not yet delivered?

**Comment by tworide** [comment]
Oh sorry @lexnederbragt I misunderstood
There are more information about the Examiner role her
https://devilry.readthedocs.io/en/latest/user/examiner.html

I try to explain further here

| Phrase                                                 | Explanation                                                                                                                                                                                                                                                                                                                                                  |
|--------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Group                                                  | One or more students                                                                                                                                                                                                                                                                                                                                         |
| Grupper med bestått karakter                           | Groups that have passed their attempt for the assignment according configuration of the assignment. e.g. Passed/Not passed                                                                                                                                                                                                                                   |
| Grupper med ikke-bestått karakter                      | Groups that have NOT passed their attempt for the assignment according to the configuration of the assignment                                                                                                                                                                                                                                                |
| Grupper som venter på tilbakemelding                   | Groups that awaiting correction/examination of their attempt                                                                                                                                                                                                                                                                                                 |
| Grupper som venter på at innleveringsfristen skal utgå | Groups that have their deadline not yet expired. The Examiner may start correcting if there are provided any attempts. But the common rule is to correct the last attempt but many students deliver many times to make sure they have a valid attempt! And of course many students work fast and complete their assignment long before the deadline expires. |
| Lukket uten tilbakemelding                             | Groups that are closed without being corrected. There are groups(students) that never delivers any thing. The examiners may then close the groups. This mean that they are not even graded just closed for whatever reason.                                                                                                                                  |

**Comment by lexnederbragt** [comment]
Thanks! Takk!

Would it be possible to add these explanations somehere to the examinerstats page?

**Comment by torgeirl** [comment]
This issue was made for `v2.0.x`, and I believe it's well covered by the assignment statistics function that was added in `v3.4.2`:

![screenshot from 2018-11-26 13-00-01](https://user-images.githubusercontent.com/796053/49013008-a0739180-f17b-11e8-8e51-955c33f5dc7d.png)
