### ISSUE TITLE
Move the "add delivery button"

### ISSUE THREAD

**Issue by hvgab** [devilry/devilry-django#921]
Move the submit button up so it's "part of the form".
Right now it's like a "we use cookies" button.

![2017-09-30_16-33-35](https://user-images.githubusercontent.com/31376076/31046688-3a2b3a10-a5fd-11e7-9b49-e441524f7b18.png)

**Comment by espenak** [comment]
This is fixed in Devilry 3x (the whole delivery process has changed). Devilry 2x only receives bug-fixes at this stage unless someone submits a patch (with tests).
