### ISSUE TITLE
Devilry no longer sending out emails about feedback.

### ISSUE THREAD

**Issue by Berstad** [devilry/devilry-django#922]
I am a group teacher in INF3490 and INF4490, and we have been receiving some feedback that devilry is not sending out emails regarding feedback of the mandatory assignments. This is unfortunate as many will not see that they have not passed and been given a new deadline until it may be too late. We have asked the students to check devilry often, but it would be much better if the system would notify the students of feedback as it did in previous semesters.

I'm not sure if this is a problem with devilry itself or an administrative error, but I am submitting here just in case.

**Comment by torgeirl** [comment]
This happened due to a backend issue of that specific Devilry instance (not directly a devilry-django issue), and the issue got solved on September 5th

I assume the deliveries your students didn't get notified about were due long before you made this issue on October 2nd.
