### ISSUE TITLE
"Closed Without Feedback" bug.

### ISSUE THREAD

**Issue by Stormseer** [devilry/devilry-django#923]
Heyo!

Found a (reproducable) bug with the "Closed Without Feedback" tag on students that missed a deadline.

1. Student is "Closed Without Feedback".
2. Course Manager makes himself Examiner, adds new Deadline. 
3. Student is now able to see delivery.
4. Course Manager removes himself as Examiner.
5. Student is now "Closed Without Feedback" & unable to see the active Deadline.
(Even though it is still an active deadline)

Would love a fix, so I can remove myself without hindering the student :)

**Comment by tworide** [comment]
Thanks for reporting.

Will look into this.

**Comment by torgeirl** [comment]
I believe this was solved in our 3.x releases (2018).
