### ISSUE TITLE
URLObject too old for automatic pip installation

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#925]
**Issue**
[URLObject 2.0.1](https://pypi.python.org/pypi/URLObject/2.0.1) (required in [devilry-django/setup.py](https://github.com/devilry/devilry-django/blob/master/setup.py)) can't be installed automatically with pip after [PyPI disabled non-HTTPS access for APIs](https://mail.python.org/pipermail/distutils-sig/2017-October/031714.html) last year.

**Suggested solution**
A newer version than 2.0.1 (from March 2012) properly works.

**Workaround**
1. Download URLObject 2.0.1 tar.gz manually
2. `tar -xzf URLObject-2.0.1.tar.gz`
3. Edit source in `URLObject-2.0.1/distribute_setup.py` from HTTP to HTTP**S**
4. Install it from file: `pip install -e URLObject-2.0.1`

**Comment by tworide** [comment]
I think it is safe to upgrade this package to the latest version.
