### ISSUE TITLE
Production requirements insists on too old psycopg2

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#926]
**Issue**
[devilry-django/requirements/production.txt](https://github.com/devilry/devilry-django/blob/master/requirements/production.txt) imports common requirements including psycopg2==2.6.2, but insists on psycopg2==2.4.6, which is too old for psycopg2.extras.DateRange (requires psycopg2<=2.5.X) required in Devilry 3.0.X.

**Suggested solution**
Bump production to at least psycopg2 2.5.X

**Workaround**
Newest psycopg2 (2.7.3.2) seems to work fine.

**Comment by tworide** [comment]
Perfect @torgeirl It should be of no concern to bump this version. We will fix
