### ISSUE TITLE
Search server support without django-haystack

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#927]
[Devilry's documentation on search servers](http://devilry.readthedocs.io/en/latest/sysadmin/elasticsearch.html)

While the End of Life (EOL) for Elasticsearch 2.4.x is [set for February 28, 2018](https://www.elastic.co/support/eol) django-haystack [seems to not move past Elasticsearch 2.x](https://github.com/django-haystack/django-haystack/issues/1383) while its fork for Elasticsearch 5.x support ([django-haystack-elasticsearch](https://pypi.python.org/pypi/django-haystack-elasticsearch)) doesn't seems to be maintained.

If we don't need the flexibility of using other search servers an alternative would be [django-elasticsearch-dsl](https://github.com/sabricot/django-elasticsearch-dsl), a wrapper for [elasticsearch-dsl-py](https://github.com/elastic/elasticsearch-dsl-py) (maintained by the Elastic team). [Example Django project using Elasticsearch](https://github.com/HonzaKral/es-django-example)

Unsure how much of Devilry's code that would need to be updated and what priority this should have.

**Comment by espenak** [comment]
This is solved in Devilry 3.x since we use postgres fulltext search there instead of haystack.
