### ISSUE TITLE
Possible logging issue

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#930]
**Description**
It seems to be a logging issue with Devilry 3.0.0b0 that wasn't present in 3.0.0a25. Not all environment factors are equal (redis vs rabbitmq, systemd vs supervisor) between the tested instances so it could be a configuration issue.

**Schedule**
3.0 milestone (January 2018)

**Comment by espenak** [comment]
This is hard to test without more information. What exactly is the issue?

**Comment by torgeirl** [comment]
@espenak: you're right; I discussed it with @tworide, but should have went more in detail here as well.

With few exceptions the gunicorn logs don't contain any valuable information. Ie. when running with loglevel=debug the 500 server error we experienced in the admin UI (issue #929) didn't register in the gunicorn logs. As far as I can tell server issues displayed to the user should be logged at any log level.

As I said it could be a local issue so please involve me if you need help debugging.
