### ISSUE TITLE
Upgrade Django to 1.11 LTS

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#932]
**Description**
Extended support for Django 1.9 ended on April 4, 2017. We should get up to 1.11 LTS now. The next upgrade should be done between the release of 2.2 LTS in April 2019 and the 1.11's end of extended support in April 2020.

We should also check the about 40 other dependencies once we upgrade to 1.11, and at least bump them to their latest patch release.

**Schedule**
3.0 milestone (January 2018)

**Comment by espenak** [comment]
Seems to be working - all tests pass, and I have done some manual testing. Closing this, but we may re-open it during QA.
