### ISSUE TITLE
Text suggestions student, examiner and admin

### ISSUE THREAD

**Issue by jimma1** [devilry/devilry-django#937]
This issue is a summarise of text suggestions ment to improve Devilry when logged in as a student. Those suggestions which are to be implemented, should be organised in one or several new issues.

## Updating grading configurations
When updating the grading configurations there is no success message after hitting "Save". The values in the overview field is updated as desired. So seems like it's only the message it self which is missing.
https://v.usetapes.com/MhM7qME9RN

## Saving a group comment as examiner
_After working on this for 30 minutes, I start to think that this should stay as it is. The GroupComment is saved, so it should say Saved. And the second success message does provide more information about the saved object. Maybe that is a good thing. So I leave it as it is_

Today when an examiner edits a group comment, the first part of the success message is a bit confusing for me as a new user of Devilry.
![image](https://user-images.githubusercontent.com/10887266/35324502-2f096702-00f1-11e8-917a-3bb8919e9023.png)

One solution to make it less confusing, is to remove the "save" part in the first line.
Than it may look something like:
![image](https://user-images.githubusercontent.com/10887266/35324574-69408888-00f1-11e8-8729-cfd9ff482aaf.png)

## New deadline for assignment
Today the word "or" ("eller" in Norwegian) is shown above the suggested dates when moving a deadline. 
![image](https://user-images.githubusercontent.com/10887266/35273466-01737b24-0039-11e8-9864-c41469248d60.png)

If we comment out the span-tags in the template `suggested-deadlines.django.html` which is used for holding the separator the word is removed. This looks good enough, and one can easily understand the choices.

Then it may look something like this:
![image](https://user-images.githubusercontent.com/10887266/35273561-43be8a1e-0039-11e8-9409-baedc834fae8.png)

## Dashboard for student
Today it looks like this:
![image](https://user-images.githubusercontent.com/10887266/35263575-9d4e3fe0-0019-11e8-81a4-99507c006cb0.png)

I suggest we add a h2/h3-tag in a container before the courses in the dashboard so we better describe what is shown. Because now I am having problems understanding the difference between the dashboard and the view for a student's courses.

Further we it may be a good idea to change the text on the button at the bottom. When clicking it, you are taken to a view showing "Your courses". The button text should reflect this.

Than it looks something like this:
![image](https://user-images.githubusercontent.com/10887266/35263761-5859fe6e-001a-11e8-97e2-61145ebe6ddc.png)

## Your Courses
There should be a sub-header on this page, so the user easily understands that one can see assignments for a course by clicking it. This eases the mental payload when looking at the page. 

Today it looks like this:
![image](https://user-images.githubusercontent.com/10887266/35264158-f1bb4814-001b-11e8-8208-d35a3d348b22.png)

If a sub-header is added, it may look something like this:
![image](https://user-images.githubusercontent.com/10887266/35264124-c4198326-001b-11e8-84c2-d59a2edb6f09.png)

**Comment by espenak** [comment]
Good suggestions. Could you add these headers/extra explanations (with english texts first) in a separate branch @jimma1 ? Then we can review it and merge it into master before adding norwegian translations.

**Comment by jimma1** [comment]
@espenak Oh yes, I will.
