### ISSUE TITLE
Error when admin wants to see feedback

### ISSUE THREAD

**Issue by jimma1** [devilry/devilry-django#938]
If you're logged in as a administrator and goes to the groupdetails view, and than wants to see the feedback details for a group/student, I get an error

View:
![image](https://user-images.githubusercontent.com/10887266/35388747-49bf4050-01d5-11e8-824d-5ca9997db8c3.png)

Error message:
![image](https://user-images.githubusercontent.com/10887266/35388765-5a0ea054-01d5-11e8-8186-3877b7b7915a.png)

**Comment by jimma1** [comment]
Anonymization is sat to OFF for the assignment
![image](https://user-images.githubusercontent.com/10887266/35389066-833f8f78-01d6-11e8-8fb1-e66ebaf71c90.png)

**Comment by espenak** [comment]
Can not reproduce this. Probably something messed up with test/debug data.
