### ISSUE TITLE
Support dataporten login hints [6]

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#942]
https://docs.dataporten.no/docs/openid/#loginhints. We want to be able to enable login hints through a setting (`DEVILRY_DATAPORTEN_LOGIN_HINTS`). The default behavior should be the current behavior.

The reason for this is that we want to be able to skip the provider select screen in cases where this list always contains a single element.

**Comment by StianJul** [comment]
This requires us to create a new django app configured as you can see here:  http://django-allauth.readthedocs.io/en/latest/advanced.html

**Comment by tworide** [comment]
Estimert til *6* timer

**Comment by espenak** [comment]
This seems to be a bit more work, since django-allauth does not seem to have any kind of openid support builtin to the oauth2 flow. We will need to dig further into this (we have used several hours just to find out if it can be plugged into django-allauth already).

**Comment by torgeirl** [comment]
There's no longer a need for this since Dataporten/Feide has significantly improved the user flow for OAuth2.
