### ISSUE TITLE
[NEW] Option to expose Devilry version in branding templates

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#946]
**Description**
Devilry 3.0.0 introduced [simple branding with templates](https://devilry.readthedocs.io/en/latest/sysadmin/branding.html). In the future, it would be nice to add the option to expose the running version of Devilry in the footer.

Ie. "Devilry v{% DEVILRY_VERSION %}" should display "Devilry v3.0.2"

**Reason**
Users aren't able to see what version of Devilry that is running. Added a version to the footer gives a visible indication of progress, and allows more advanced users to keep up on what bug fixes that can be expected if the future gets accompanied by a version log.

**Comment by espenak** [comment]
Should already be available as ``{{ DEVILRY_VERSION }}`` in the templates. This only gives the version number (3.0.2).

**Comment by espenak** [comment]
This is now added in a separate _Available template variables_ section in the branding guide.
