### ISSUE TITLE
Add support for custom favicon [1]

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#948]
In certain browsers Devilry "inherits" Dataporten's favicon, but it seems the actual issue is that the icon is missing and some browsers just keep the last one around.

/static/devilry_theme3/3.0.3/media/images/favicons/favicon.ico gives a `404 Not Found`

Did it get lost in one of the lastest patches?

**Comment by tworide** [comment]
We do not have a new favicon for devilry. The last one of the devil with his fork is no longer in use.

**Comment by torgeirl** [comment]
Is a replacement favicon in the makings? 

Since the application points to a (non-existent) static file I assume it's intended to be provided differently than pictures in the footers?

**Comment by torgeirl** [comment]
@tworide: updated the title as it seems clear this would have to be included as part of the [branding](https://devilry.readthedocs.io/en/latest/sysadmin/branding.html).

**Comment by torgeirl** [comment]
As we discussed, the solution should be an `/image/` path from `devilry_settings.py` that sysadmins already should handle with their reverse proxy server (ie Nginx) as it's the same solution as images in footers.

**Comment by tworide** [comment]
Estimert til *1* time
