### ISSUE TITLE
List counters not displayed

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#950]
Previous versions (v2.x) would display counters for the number of objects (subjects, examiners, students, ...) when a number of objects are displayed, and partial counters when a filter is active to indicate how large the portion that are displayed with that filter.

A backside of the faster UI is that is hard to get a feeling of a list of students contain 50, 150 or 500 students. Counters also works as an assurance by allowing admins and examiners easily double check the size of participants match their expectation.

**Comment by espenak** [comment]
Counters should not be a problem, at least not in most places. It will just require some work since there are a lot of views to update. The performance impact of an count query will normally be very small (I do not think it will be a problem in any of the currently available views).
