### ISSUE TITLE
[docs] User-centered changelog

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#954]
The docs should include changelog meant for regular users to read. It should be sorted from newest to oldest.

The URL should be version agnostic.

**Comment by espenak** [comment]
This is now available via the new ``DEVILRY_CHANGELOG_URL`` branding template variable. This variable points to file:///Users/espenak/code/devilry-django/not_for_deploy/docs/_build/user/changelog_overview.html.

**Comment by espenak** [comment]
Hmm wrong URL in the comment above - edited
