### ISSUE TITLE
Shorter deadline increments

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#956]
It seems manage deadline doesn't allow for adjustments in deadlines for less than three days.

![dato](https://user-images.githubusercontent.com/796053/36156092-6a43f392-10d6-11e8-878c-9ce3b1f1d5eb.JPG)

It's fine that the default is three days, but would be preferable if the examiner/administrator could adjust it down as some deadline adjustments could be technical or for other reasons shorter than the full three days.

Since the shorter increments isn't a default it would be advisable that regular examiners aren't allowed to give less than the default three days.

**Comment by StianJul** [comment]
We just add a quickfix for this until we decide how we want manage this, which will probably be on the assignment level. Maybe we can add some configuration for this, but we'll look into that later.

For now we just restrict this to be somewhere in the future.

**Comment by torgeirl** [comment]
@StianJul: yes, that is fine for now :+1:
