### ISSUE TITLE
Display error when a file is too big

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#958]
**Description**
In the current build, trying to upload a file that exceeds the Content-Length request header limit (for nginx, the limit would be specified using `client_max_body_size`) doesn't result in a user-friendly error. The file line is just set to red:

<img width="1198" alt="skjermbilde 2018-02-15 kl 15 57 53" src="https://user-images.githubusercontent.com/796053/36300570-2969d908-1302-11e8-83cf-873dba61e652.png">

The user is still able to press add delivery, but only the text and other files are delivered (the UI does however correctly say "comment added" if the too large file was your only file).

Since no server error occurred, the only indication of an error for a sysadmin is the error log of nginx, that notes a `client intended to send too large body` error.

Example from the nginx error log:
`2018/02/16 12:34:56 [error] 28930#0: *3 client intended to send too large body: 72606203 bytes, client: <ip address>, server: <nginx server_name>, request: "POST /cradmin_temporaryfileuploadstore/temporary_file_upload_api HTTP/2.0", host: "<server URL>", referrer: "<server URL>/devilry_group/student/123456/feedbackfeed/"
`

**Solutions**
1. Yield an error when a delivery contains files with errors to ensure the user understands certain files wasn't included in the otherwise successful upload.
2. Test for Content-Length request header errors, show an error when it occurs including the maximum size allowed (probably difficult).
3. Include a `DEVILRY_MAX_UPLOAD_SIZE` in `settings.py` that sysadmins needs to set what their server will accept and display that limit in upload UI. If possible, improve the error displayed when files are too big to included telling the user that the file was too big.

A combination of 1. and 3. would probably be a good solution.

**Comment by espenak** [comment]
I agree with (1). (3) may be possible, but can not be guaranteed since uploads of large files on slow connections can result in timeouts.

**Comment by torgeirl** [comment]
The issue is almost identical for Devilry 2.x.
