### ISSUE TITLE
[ui] Deadline dialog lack participants' name [1]

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#961]
**Description**
It's vital for department administrators to be able to see who issued a deadline extension. The current dialog for individual assignments does however only displays the role of the participants, not the name or any other identifier.

![screenshot from 2018-02-16 15-12-38](https://user-images.githubusercontent.com/796053/36311891-0ff203da-132d-11e8-87a0-a08f3bed8b3e.png)

**Solution**
The name of a participant should be visible next to their role.

**Comment by StianJul** [comment]
This happens because the examiner was removed from the group.

We need a templatetag that renders the examiner name based on the `RelatedExaminer`-model, not the `Examiner`-model. We need to handle this for students as well

**Comment by tworide** [comment]
Estimert til *1* time
