### ISSUE TITLE
Deletion of user data

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#963]
We need a way to periodically delete user data. Since such a functionality brings the possibility catastrophe it should present the result before any action is done.

It should delete the following:
- Users and their user history
- Everything in a semester
- All uploads associated with those semesters

A scenario would be that you in August 2018 would like to delete the 2016 spring semester and semesters older than it (all semesters older than two years), their uploads, and any user that hasn't logged in since July 31, 2016.

**Comment by torgeirl** [comment]
It seems issue #1036 would solve this issue.

**Comment by StianJul** [comment]
Issue #1036 is for fixing deletion of semesters "older than .." with it's underlying data, and should not include deletion of a user. This is mainly meant as supporting functionality for importing v2 data to a clean v3 database for now. 

We should have separate functionality for specifically deleting user data.

**Comment by torgeirl** [comment]
```
$ python manage.py devilry_delete_inactive_users "2017-01-01 23:59"
EXITING... There are no users with last login before Jan 1. 2017 23:59.
```

The command seems to be working, but since something alternated the `date joined` field to August 9, 2018 it doesn't delete anyone. I believe it was the migrations we ran for Devilry 3.3.0b3.
