### ISSUE TITLE
[ui] Empty delivery comments counted as comments in student overview

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#965]
**Description**
The assignment overview lists the number of comments and files a student has delivered for the given assignment, but if the student uploads files without leaving a comment it is still counted as one comment.

**List view**
![inf2440comment](https://user-images.githubusercontent.com/796053/36375222-b9595520-156e-11e8-8559-369cb564f0b5.JPG)

**Assignment view**
![inf2440comment2](https://user-images.githubusercontent.com/796053/36375225-bb4cac74-156e-11e8-9b46-3b9ba1e1ee0f.png)

**Solution**
Either change the counter to something other than 'comment[s]', or stop counting empty comments.

**Comment by espenak** [comment]
The same issue/challenge is, of course, also for the examiner comments/files counters.

**Comment by torgeirl** [comment]
> We have a couple of possible solutions here:
> 
> 1. Rename `Comments: <number>` to something else. I have no good ideas for what this something else could be, but perhaps someone else does?
> 2. Do not count comments with empty text. This will require some modifications to the postgres triggers that generate the cache I think, but I do not think it should be too hard to do.
> 3. ... other ideas ...?

@espenak: I would prefer 2. since being able to distinguish deliveries with comments from those without possible has some added benefit for examiners, but 1. isn't too bad either.
