### ISSUE TITLE
[ui] Not all assignment warnings are displayed

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#971]
**Description**
In the assignment view, it seems the warning `There are no examiners on the assignment` is given a higher priority than `There are still students who are on the semester, but not on the assignment` so when both are the case only the first warning is displayed.

![screenshot from 2018-02-20 12-40-53](https://user-images.githubusercontent.com/796053/36422283-ae0c9844-163b-11e8-8765-f3eee3550eb3.png)

**Solutions**
- All warnings should be displayed.
- Perhaps a `Warnings` headline or symbol should be added.
- Perhaps the warning about missing examiners should be displayed until after the deadline since it's normal to only distribute delivered assignments among active examiners.

**Comment by StianJul** [comment]
We'll rework the warnings when resolving #1021. We'll probably move away from the whole "banner warning", and rather add a warning inside each box where they "belong".
