### ISSUE TITLE
Add metadata to feedbackfeed timeline

### ISSUE THREAD

**Issue by StianJul** [devilry/devilry-django#972]
When a deadline is moved, we should show a timestamp of when the move occurred with the "deadline moved"-text.

![screen shot 2018-02-20 at 13 41 57](https://user-images.githubusercontent.com/3988175/36424527-dd1ef322-1643-11e8-8891-5f3e34d0c36f.png)

We already have the data, so we only need to render it in the UI.

**Comment by torgeirl** [comment]
@StianJul: it also looks like who moved the deadline isn't included in the "deadline moved" text, only in the comment box. Since a comment isn't required it would be nice to include the name and/or username of who moved it.

**Comment by StianJul** [comment]
We only have metadata about when the deadline was moved, not the user that moved it. We'll start implementing this now, but as for deadlines moved before this change is releasd we'll have no way of knowing. We add two different messages for this, one with the user and one without.

**Comment by torgeirl** [comment]
@StianJul: I believe [there's a `changed_by`](https://github.com/devilry/devilry-django/blob/ee02c3073e71f12de74ceba38b57ee74d4156d5b/devilry/devilry_group/models.py#L669-L687) that you can use.

**Comment by StianJul** [comment]
The ``FeedbackSetDeadlineHistory`` model has a field for that which can be NULL, yes, but an entry of that model is generated automatically by a postgres trigger that "records" changes based on a specific field or fields of the "FeedbackSet" model.

**Comment by torgeirl** [comment]
Ups, I didn't notice it can be null and blank.

Why isn't this always set, @espenak? Should I make another issue, ask for it to always be set?

**Comment by StianJul** [comment]
This field should be able to be set to NULL in case the user is deleted. We do not want the "record" to be removed.

**Comment by StianJul** [comment]
This issue will be continued in #976
