### ISSUE TITLE
Feedbackfeed edit grade metadata [2]

### ISSUE THREAD

**Issue by StianJul** [devilry/devilry-django#976]
Add `grade edited` events to the feedbackfeed.

We need another model `GroupCommentEditHistory`(or something like that) and a postgres trigger that saves an entry of this model in the database everytime the text on a GroupComment is edited(only for public comments, we don't need a history for private comments).

**Comment by tworide** [comment]
Estimert til *2* timer.

**Comment by espenak** [comment]
Editing of comments is removed from this issue - that requires new functionality that we have just started to "formalize" in #1016 (it has been discussed verbally before several times too).
