### ISSUE TITLE
Assignment-level deadline handling missing [2]

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#979]
In v2 course administrators or higher were able to set deadline handling for each assignment if they wanted it to be different than the default (set with `DEFAULT_DEADLINE_HANDLING_METHOD`).

This feature seems to be missing from the assignment overview.

**Comment by espenak** [comment]
Related to #978

**Comment by tworide** [comment]
Estimert til *2* timer for selve arbeidet med å lage en switch-mulighet mellom **HARD** og **SOFT** deadline handling.

**Comment by StianJul** [comment]
This is now implemented but the functionality is disabled until we resolve issue #978.
