### ISSUE TITLE
Multiple student uploads generates duplication issues for examiner Zip files

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#984]
**Description**
All the files uploaded by a student gets added to the compressed archives for examiners (the only exception is uploads after the deadline, that gets put into a sub-directory). This causes issues when a student uploads multiple files with the same file name.

A normal work pattern for students is to upload early version of the delivery in good time before the deadline, and then an updated version closer to the deadline. The compressed archive file generated for the examiner would then contain the files from both uploads: 

![screenshot from 2018-02-27 10-38-37](https://user-images.githubusercontent.com/796053/36722674-730aad1c-1bae-11e8-8c9d-e5acd7e03895.png)

Depending on what method the examiner uses to unzip the archive file this could lead to some unexpected results:

- UNIX: the default seems to just unzip the newest version of files with identical names, leading to the group directory containing a mix of each student delivery (expected behavior).
- Windows: depending on what program you use to unzip, the program might prompt you for each possible overwrite and while doing so it might present the time for the file existing on your file system instead of when it was created/changed by the student on their machine (terrible behavior).

**Solution**

- With identical file names, only add the latest version uploaded before the deadline to the group directory of the compressed archives for examiners.

**Comment by StianJul** [comment]
We're currently working on a solution for this related to issue #973. The structure of a zipped folder will be redone. Better folder and file names, and handling of old duplicate files will be addressed in this fix.

**Comment by StianJul** [comment]
The issue was not closed as it isn't implemented yet. We intend to implement this is the near future, but it hasn't been prioritized yet.

**Comment by torgeirl** [comment]
The issue is solved in the final `3.3.0` build.
