### ISSUE TITLE
Deadline management lack sorting, links and grounds [4]

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#988]
The current deadline management view is a unsorted list of the deadlines for the assignment:

![screenshot from 2018-02-28 16-52-02](https://user-images.githubusercontent.com/796053/36797618-b14221c8-1ca8-11e8-8eba-317c594ee2ab.png)

The view I've screenshot has 18 (!) deadlines, in as far as I can tell random order.

**Suggestions**
- Sort the deadlines, chronological order should be a fine default.
- Add a sorting menu to the right.
- Make the user name of each listed student a link to the students delivery conversation.
- Display the reason why the deadline was moved in this view.

**Comment by espenak** [comment]
May be a bit hard to add a sort filter to the right hand menu because we are not working with database models, but a grouping og objects that we group in python code. Unless being able to sort in different orders is very important, it will not be worth the work I think. Should not be a problem to order the list in chronological order by default.

**Comment by torgeirl** [comment]
That sounds OK.

Would you also be able to make the usernames links and put the reason for the deadline in the view?

**Comment by tworide** [comment]
> Would you also be able to make the usernames links and put the reason for the deadline in the view?

Yes this will be possible

**Comment by tworide** [comment]
Estimert til *4* timer

**Comment by StianJul** [comment]
> Would you also be able to make the usernames links and put the reason for the deadline in the view?

No problem adding the links, but adding a reason for why is problematic for both how the view actually works and how this would be solved UX-wise.

This view only gathers groups with the same deadline on the assignment to make it easier to bulk move deadlines for a collection of groups, but the reason for why the deadline was moved may vary for each individual group with the same deadline. The view is meant to support all deadlines within an assignment regardless of when it was moved, by who or why(this is instead shown as a comment in the feed).

Here's an example: 
Two groups have the same deadline. Group_1 has its deadline moved, with reason "A". Group_2 is then moved to the same deadline as Group_1 with reason B. Which reason do we show?

The conclusion is that we will not be able to solve this with the current view as this is not what it was designed for.

**Comment by StianJul** [comment]
We consider this closed for now.

**Comment by torgeirl** [comment]
@StianJul 

> No problem adding the links, but adding a reason for why is problematic for both how the view actually works and how this would be solved UX-wise.

I understand. The most important part is that we includes the links backs to the feedbacks, which it seems included with your first commit. :+1:
