### ISSUE TITLE
Unnecessary step before viewing feedback [1]

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#992]
Between viewing the list of all students on an assignment to viewing one particular feedback dialog, there is an unnecessary middle step. It previews the same information as you see from the list view, and only adds the rarely used feature to splitting the feedback group.

**Example**
The list view:
![screenshot from 2018-03-09 12-13-55 copy](https://user-images.githubusercontent.com/796053/37207275-8bfc0546-239c-11e8-98a6-1b0546551039.png)

Middle step:
![screenshot from 2018-03-09 12-06-59](https://user-images.githubusercontent.com/796053/37207279-90c077e2-239c-11e8-9682-e3e1d4e908a5.png)

**Solution**
Move the option of splitting the feedback group to the right side of the feedback dialog, and just drop the middle step all together.

**Comment by tworide** [comment]
Estimert til *1* time
