### ISSUE TITLE
Add deadline management shortcut to feedback dialog view [12]

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#993]
To manage deadline of one students, a normal workflow for a department administrator or course/semester administrator would be to view the feedback dialog for the assignment first to verify it's the students in question etc. They then have to move back to the student overview and choose manage deadlines:

![screenshot from 2018-03-09 12-13-55](https://user-images.githubusercontent.com/796053/37207680-506c2360-239e-11e8-9f4a-713b33ad4fc8.png)

**Solution**

- Add a shortcut to manage the deadline for one assignment from the feedback dialog view.
- The shortcut should lead to a partly filled form as it already knows the assignment and student(s).

**Comment by espenak** [comment]
This is not possible with the structure of that view. So we need some other solution for this. I guess the need for this feature is the admin shortcut where they could search for a student, get all the information about that student, and quickly add a new deadline for the student?

**Comment by espenak** [comment]
I suggest that we add a wizard with:

- Page 1: Search for and select a student.
- Page 2: List their assignments (in reality AssignmentGroups) sorted by last deadline descending.
- Page 3: Go to the feedback feed with an extra querystring argument that adds some help text for adding or moving a deadline. I guess this help text can be styled as "fixed" to the bottom of the screen.

**Comment by torgeirl** [comment]
A wizards from the administrator dashboard would work, yes. A few notes: 

> - Page 2: List their assignments (in reality AssignmentGroups) sorted by last deadline descending. Will get all assignments that the admin has access to (same permission query as everywhere else in the system).

Just making sure: this would include all assignments from all active semesters (waiting for delivery, passed, failed, etc)?

From the same view, would it be possible to include the delivery status of previous assignments in the same subject when listing the assignments? In v2, department administrator also have to take this into account up this when giving a delayed deadline (also helps them noticing if passed previous hasn't be added, etc).

**Comment by tworide** [comment]
> From the same view, would it be possible to include the delivery status of previous assignments in the same subject when listing the assignments? In v2, department administrator also have to take this into account up this when giving a delayed deadline (also helps them noticing if passed previous hasn't be added, etc).

yes this is possible but will increase the time estimate

**Comment by tworide** [comment]
Estimert til *12* timer
